### ISSUE TITLE
Closing old issues and pull requests

### ISSUE THREAD

**Issue by dcbaker** [pazz/alot#1010]
We have quite a few issues and pull requests that are opened, with no work being done toward them. Most if not all of these old pull requests no longer merge cleanly, but haven't been updated. Many of the issues should probably be closed as "wont fix", are actually fixed already, or we need more information on them.

I think it would be worth our effort to go through and have a look at many of these older issues and pull requests, and close them if they're not worth having opened anymore.

Opinions?

**Comment by pazz** [comment]
certainly! I like that you've opened a new issue for this ;D

**Comment by lucc** [comment]
I would start with open issues. In my opinion it is more important to fix long standing bugs or misbehaviors than implementing long standing feature requests.

@pazz you have many old issues with little comments in them, can you go through them and add some pointers for us how to reproduce (on current master ;) and what was the intension.

**Comment by pazz** [comment]
will do over the weekend, sure.

**Comment by dcbaker** [comment]
I think we're working on this, so I'll close the issue.
