### ISSUE TITLE
More documentation on using reply_prefix

### ISSUE THREAD

**Issue by the-solipsist** [pazz/alot#1018]
Hi.  I'm checking out alot to see if I can use it as my mail mail client instead of Thunderbird, and so far I really like it and its extensibility.  

I couldn't find [clear documentation](https://alot.readthedocs.io/en/latest/configuration/hooks.html) on how I can get my reply prefix to look like this:

Ex Example <example@example.com> [2017-01-31 11:33:40 +0530]:
fullname <from-email> [yyyy-mm-dd hh:mm:ss ±offset]:

**Comment by dcbaker** [comment]
you're going to need to write a `reply_prefix` hook. Something like:

```python
def reply_prefix(realname, address, timestamp, ui=None, dbm=None):
    return '{} {} [{}]'.format(realname, address, timestamp.format(...))
```

I'll leave it up to you to replace the ... with the format you actually want, the table explaining the different formatters is [here](https://docs.python.org/2/library/datetime.html#strftime-strptime-behavior).

**Comment by dcbaker** [comment]
just as a note since you mentioned you're not really a programmer: you'll need to quite the identfiers like this ```"%Y/%m/%d"```, but you have more specific requirements than that.

**Comment by pazz** [comment]
I think we can close this.

**Comment by ysubach** [comment]
Another example if anyone else interested: https://gist.github.com/ysubach/646ff6f744b367321476cffad5a63abe

My problem with default "Quoting ..." message was that it's not recognized by Gmail and others, so this line is not hidden when my recipient open the reply.
