### ISSUE TITLE
Queue sent mail when failure sending

### ISSUE THREAD

**Issue by dcbaker** [pazz/alot#1020]
One of the features of email is that it is asynchronous, and can be queued while an internet connection is unavailable. There are lots of reasons you might not have an internet connection but want to write emails and queue them, patch review in spotty or no internet settings eems the most likely.

**Comment by pazz** [comment]
https://wiki.archlinux.org/index.php/Msmtp#Using_msmtp_offline
https://github.com/Stebalien/msmtp-queue

I think this should not be an alot feature actually. I use the above.

**Comment by dcbaker** [comment]
Okay. I'll agree with that. We should definately document this somewhere though.

**Comment by dcbaker** [comment]
I got bored and wrote my own queueing daemon, it's python, but uses NetworkManager over dbus to check network connectivity. It's also all asynchronous using asyncio, and sends emails immediately when the network is online. I think it's pretty nifty.

https://github.com/dcbaker/py-mailqueued

**Comment by pazz** [comment]
Quoting Dylan Baker (2017-02-06 22:47:23)
> I got bored and wrote my own queueing daemon, it's python, but uses
> NetworkManager over dbus to check network connectivity. It's also all
> asynchronous using asyncio, and sends emails immediately when the network is
> online. I think it's pretty nifty.
> 
> https://github.com/dcbaker/py-mailqueued

Very nice.
FTR, I've set things up some tome ago using cron and
 * msmtp's own scripts `msmtp-[en|list|run]queue.sh`
 * a bash script that contains roughly

 ```
 set -e
 nm-online -x
 msmtp-runqueue.sh
 ```

**Comment by pazz** [comment]
re your project: I think it needs a script to list the queue contents and more importantly: a catchy name!

**Comment by dcbaker** [comment]
How about "right now?" for a catchy name?

**Comment by pazz** [comment]
good one. Or how about  'senditlater' ? 'letterbox' ?

**Comment by dcbaker** [comment]
ooh, "pythonexpress"?

**Comment by pazz** [comment]
because it is delayed? :-)

**Comment by dcbaker** [comment]
What can I say, I like ironic names.
