### ISSUE TITLE
Test coverage checklist

### ISSUE THREAD

**Issue by lamarpavel** [pazz/alot#1021]
As per the discussion in #917 we will try to maintain a checklist of test coverage per module. When you write tests or add a new module (or remove one), please do reference this issue in your git commit message so that the people subscribing this issue get a notice and can update the checklist.

### List of Modules (checked = 100% test coverage)

- [ ] account
- [ ] buffers
- [ ] completion (7)
- [ ] crypto
- [ ] errors
- [ ] helper (32)
- [ ] ui
- [ ] walker  
- addressbook  
  - [ ] abook
  - [ ] external  
- commands  
  - [ ] bufferlist
  - [ ] envelope (4)
  - [ ] globals
  - [ ] init (3)
  - [ ] search
  - [ ] taglist
  - [ ] thread (9)
  - [ ] utils
- db  
  - [ ] attachment
  - [ ] envelope (1)
  - [x] errors
  - [ ] manager
  - [ ] message
  - [ ] thread (2)
  - [ ] utils
- settings  
  - [x] errors
  - [ ] manager
  - [ ] theme
  - [ ] utils
- utils  
  - [ ] argparse (16)
  - [ ] configobj (2)
- widgets  
  - [ ] bufferlist
  - [ ] globals (1)
  - [ ] search
  - [ ] thread
  - [ ] utils

The number in parenthesis is not a progress meter but the total count of tests for that module. It is a quick overview of where work has started.

**Comment by pazz** [comment]
great, thanks!
Could this help at all?: https://github.com/codacy/python-codacy-coverage

**Comment by lamarpavel** [comment]
@pazz Probably, but my experience with python development and the surrounding ecosystem is very limited. Maybe whoever set up the CI could add some automated coverage analysis and I can update this issue accordingly whenever I get a notification? This is new territory for me.

**Comment by lucc** [comment]
To get a rough estimate about the number of functions and methods defined in each module you can do `grep --count '\bdef\b' alot/**/*.py`.

**Comment by lamarpavel** [comment]
@lucc I used `ag "\bdef test_" -c` to get the number of test-functions. I didn't want to calculate a ratio between that and the total number of functions since it wouldn't be correct and I thought I'd ask first. The problem here would be if there are 6 test-functions for 6 functions in the module and I would write `6/6` but not check the "100% coverage" box - it would be confusing rather than helpful, wouldn't it?

**Comment by dcbaker** [comment]
If we can get a tool like codacy to track coverage I think that's best (I also know of [coveralls](https://coveralls.io/)).

In the meantime, here's the output of coverage (through pytest):
```
---------- coverage: platform linux2, python 2.7.12-final-0 ----------
Name                           Stmts   Miss  Cover
--------------------------------------------------
alot/__init__.py                   8      0   100%
alot/__main__.py                  71     71     0%
alot/account.py                  108     76    30%
alot/addressbook/__init__.py      21     11    48%
alot/addressbook/abook.py         20     13    35%
alot/addressbook/external.py      40     30    25%
alot/buffers.py                  437    334    24%
alot/commands/__init__.py         80     14    83%
alot/commands/bufferlist.py       21     21     0%
alot/commands/envelope.py        332    257    23%
alot/commands/globals.py         525    418    20%
alot/commands/search.py          134    134     0%
alot/commands/taglist.py          10     10     0%
alot/commands/thread.py          604    492    19%
alot/commands/utils.py            43     33    23%
alot/completion.py               312    239    23%
alot/crypto.py                   102     86    16%
alot/db/__init__.py                4      0   100%
alot/db/attachment.py             49     30    39%
alot/db/envelope.py              180    124    31%
alot/db/errors.py                  8      0   100%
alot/db/manager.py               211    211     0%
alot/db/message.py               132     93    30%
alot/db/thread.py                139     96    31%
alot/db/utils.py                 187    156    17%
alot/errors.py                    16      2    88%
alot/helper.py                   281    149    47%
alot/settings/__init__.py          3      0   100%
alot/settings/errors.py            2      0   100%
alot/settings/manager.py         239    181    24%
alot/settings/theme.py            65     54    17%
alot/settings/utils.py            46     39    15%
alot/ui.py                       377    377     0%
alot/utils/__init__.py             0      0   100%
alot/utils/argparse.py            55     12    78%
alot/utils/configobj.py           77     55    29%
alot/walker.py                    58     44    24%
alot/widgets/__init__.py           0      0   100%
alot/widgets/bufferlist.py        14      6    57%
alot/widgets/globals.py          208    153    26%
alot/widgets/search.py           141    124    12%
alot/widgets/thread.py           236    190    19%
alot/widgets/utils.py             23     13    43%
--------------------------------------------------
TOTAL                           5619   4348    23%
```

**Comment by The-Compiler** [comment]
FWIW what I use for qutebrowser is [codecov.io](https://codecov.io/) - shouldn't be hard to set up as soon as you got basic coverage tracking working. Quick rundown:

- Set up local coverage tracking by using `coverage run` (with [coverage.py](https://coverage.readthedocs.io/)) or by using pytest as a runner and the `pytest-cov` plugin
- Turn on codecov for this repo on their website
- Do `pip install codecov` in your build and run `covecov` after the tests.

**Comment by lucc** [comment]
You are right about the ratio and confusion. But for counting tests there is a better method: just run the them, there will be a report at the end :)

**Comment by lamarpavel** [comment]
Ah, I didn't know pytest could output coverage stats. So the tools like codacy, coverall and codecov really just query the coverage calculated by (eg.) pytest and present them to us on github?

**Comment by The-Compiler** [comment]
Correct.

**Comment by dcbaker** [comment]
They all (including pytest) wrap the same tool, coverage.

**Comment by lucc** [comment]
I think we can close this issue as we have set up a coverage report with the CI. It is linked in the README as a badge.

**Comment by pazz** [comment]
yes, thanks
