### ISSUE TITLE
empty thread list

### ISSUE THREAD

**Issue by meskio** [pazz/alot#1041]
For me the commit 237499e631741dbb3837e5ef99cc66f842e8a92e produces an empty thread view.

I believe the problem is that PipeWalker now uses the focus property instead of the get_focus method, that is used by the parent class ListWalker. In https://github.com/pazz/alot/blob/master/alot/buffers.py#L277 an instance of PipeWalker gets passed to ListBox, that will be calling `get_focus` that now is not anymore a reimplementation from the PipeWalker but the original implementation of ListWalker.

**Comment by lucc** [comment]
Please see #1040

**Comment by meskio** [comment]
I thought I did search for it. Sorry for the noise then.

Thanks for the fast fix :)
