### ISSUE TITLE
Recommended installation via pip fails at notmuch dependency

### ISSUE THREAD

**Issue by varac** [pazz/alot#1045]
I like [pipsi[(https://github.com/mitsuhiko/pipsi), a " a wrapper around virtualenv and pip which installs scripts provided by python packages into separate virtualenvs to shield them from your system and each other."

However, alot fails to install via pipsi and I don't know how to solve it:

```
--- ~/.local » pipsi install alot
Running virtualenv with interpreter /home/varac/.local/venvs/pipsi/bin/python2
Using real prefix '/usr'
New python executable in /home/varac/.local/venvs/alot/bin/python2
Also creating executable in /home/varac/.local/venvs/alot/bin/python
Installing setuptools, pkg_resources, pip, wheel...done.
Collecting alot
  Downloading alot-0.4-py2-none-any.whl (121kB)
    100% |████████████████████████████████| 122kB 1.9MB/s 
Collecting urwid>=1.1.0 (from alot)
  Using cached urwid-1.3.1.tar.gz
Collecting configobj>=4.7.0 (from alot)
  Using cached configobj-5.0.6.tar.gz
Collecting notmuch>=0.13 (from alot)
  Could not find a version that satisfies the requirement notmuch>=0.13 (from alot) (from versions: )
No matching distribution found for notmuch>=0.13 (from alot)
Failed to pip install.  Aborting.
```

**Comment by varac** [comment]
Ugh, I followed the [installation guide](http://alot.readthedocs.io/en/latest/installation.html) and the recommended installation fails as well: 

```
--- notmuch/alot ‹master› » pip install --user https://github.com/pazz/alot/archive/master.zip

Collecting https://github.com/pazz/alot/archive/master.zip
  Downloading https://github.com/pazz/alot/archive/master.zip
     / 1.6MB 437kB/s
Collecting configobj>=4.7.0 (from alot==0.6.0.dev0)
  Using cached configobj-5.0.6.tar.gz
Collecting notmuch>=0.13 (from alot==0.6.0.dev0)
  Could not find a version that satisfies the requirement notmuch>=0.13 (from alot==0.6.0.dev0) (from versions: )
No matching distribution found for notmuch>=0.13 (from alot==0.6.0.dev0)
```

**Comment by varac** [comment]
Just for the record, `python setup.py install --user` works. Still I'd prefer pipsi/pip.

**Comment by varac** [comment]
I got recommended this fix:

```
git clone from https://github.com/notmuch/notmuch
pip install ./notmuch/bindings/python/
```

but this should be documented in the official installation guide.

**Comment by pazz** [comment]
Quoting varac (2017-04-25 10:34:27)
> I got recommended this fix:
> 
> git clone from https://github.com/notmuch/notmuch
> pip install ./notmuch/bindings/python/
> 
> but this should be documented in the official installation guide.

Please be my guest to send a PR to ammend the installation notes as you see fit!
As stated in other places, I do not see it as my responsibility to package alot on pypi.

Also, you really have to ensure that the notmuch bindings and the library version you've installed match!
As far as I understand, there is no easy way to compile and install libnotmuch from within pypi.
HTH,
p

**Comment by dcbaker** [comment]
You can't install notmuch from pip, it's too tightly coupled to the c
library. What I do to put alot in a virtualenv is symlink notmuch from my
system into the virtualenv. I use pyenv for developing though, and use my
package manager to install stem wide versions, so YMMV.

I'm on mobile, please excuse autocorrect fail.

**Comment by dcbaker** [comment]
This isn't really our bug, and it seems to be resolved, so I'm going to close it. Feel free to re-open if needed.
