### ISSUE TITLE
feature: reload command

### ISSUE THREAD

**Issue by opensamba** [pazz/alot#1046]
Hi,
I checked out the docs and the code in alot but seems there's no way to reload the conf from commandline into alot.

I've also try some combinations of calling ```pkill -SIGUSR1 alot``` from alot with no luck.

I think this could be a very nice issue for those who are configuring alot and want to see the change in realtime.

So, I'm asking if there's a way for now and if can be possible to implement a **reload** command.
tnx

**Comment by pazz** [comment]
Yes, there is currently no such command, you just have to start a new
instance to test the settings.
I've never used long running alot instances myself, so never saw the
need for such things.
But of course it's possible to implement this: just add a new global
command that re-reads the config files and replaces
alot.settings.settings with a new SettingsManager; and reload..
HTH

**Comment by dcbaker** [comment]
I do use long running alot sessions with tmux (sometimes for multiple days), and would be happy to help such a feature land :)
