### ISSUE TITLE
FAIL: test_future_seconds on MacOS

### ISSUE THREAD

**Issue by matthewbauer** [pazz/alot#1048]
Here's the error:

```
======================================================================
FAIL: test_future_seconds (tests.helper_test.TestPrettyDatetime)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/private/var/tmp/nix-build-python2.7-alot-0.5.1.drv-0/alot-0.5.1-src/tests/helper_test.py", line 248, in test_future_seconds
    self.assertEqual(actual, expected)
AssertionError: u'12:00pm' != u'12:00p'
- 12:00pm
?       -
+ 12:00p
```

full log is available here: http://hydra.nixos.org/build/53107329/nixlog/3

**Comment by pazz** [comment]
Thanks for reporting this. It should be easy to adjust this test.
Slightly surprising representation though :)
Cheers,
P

Quoting Matthew Justin Bauer (2017-05-24 20:51:00)

**Comment by dcbaker** [comment]
I wonder if it's because we use `%P`, which is a gnu extension? I don't know what C library macOS uses, but it's quite possible that `%P` does something different. That probably means we need to fix the code too.

**Comment by lucc** [comment]
Not sure if that is up to date but it only lists %p not %P:
https://developer.apple.com/legacy/library/documentation/Darwin/Reference/ManPages/man3/strftime.3.html

**Comment by dcbaker** [comment]
It looks like [freebsd](http://www.unix.com/man-page/FreeBSD/3/strftime/) doesn't have `%P` either (which makes sense given that macOS is forked from an old version of freebsd). We should probably stick to the C89 required specifiers only if we care about platforms not using glibc.
