### ISSUE TITLE
Search view line format

### ISSUE THREAD

**Issue by mkaito** [pazz/alot#1058]
I asked on IRC, but got no reply. Reading the docs, it seems like this is not currently implemented.

I'd like to change the way things are displayed in search buffers. Right now, it displays the date, then a message count for the thread, tags, sender, and then subject. I'd like to reorder these to show subject first, then sender, then tags. But this is subjective, and should arguably be configurable.

Unix tradition dictates that this option be a format string where a user can arrange placeholders, perhaps with filters to mangle output such as truncating or changing the date format.

**Comment by lucc** [comment]
You are looking for [search.threadline.parts](http://alot.readthedocs.io/en/latest/configuration/theming.html#highlighting-thread-lines-in-search-mode).
