### ISSUE TITLE
Use python gpg instead of pygpgme

### ISSUE THREAD

**Issue by dcbaker** [pazz/alot#1069]
Debian is planning to drop pygpgme, as it is unmaintained. It's also just a good idea not to rely on unmaintained libraries. There was a pull request (#915) that started this work but didn't finish it.

**Comment by jljusten** [comment]
@dcbaker: I talked to @dkg on irc, and he is okay with you picking up and finishing his patch.

**Comment by dcbaker** [comment]
Thanks, I'll start looking into it.

Quoting Jordan Justen (2017-07-05 13:57:04)
