### ISSUE TITLE
Tests failures on travis for forked repo

### ISSUE THREAD

**Issue by lucc** [pazz/alot#1076]
The travis tests for lucc/alot [fail](https://travis-ci.org/lucc/alot/builds) recently. Normally it's an `AttributeError: 'module' object has no attribute 'abook_test'` when the tests are run. Does this happen for any body else? Apearently master in this repo builds just fine.

Also there is a supressed error for the command `pip install .[test]` in the install step. pip also doesn't understand that command locally on my end. @dcbaker you added it in 3e0e2d463. How should that work? Does it work for you?

**Comment by pazz** [comment]
I cannot reproduce this:
https://gist.github.com/pazz/384fb847a047476d44a5c20269f49ea1

**Comment by dcbaker** [comment]
I have the same bug.

**Comment by dcbaker** [comment]
I'll look into it. thanks for bisecting @lucc

**Comment by dcbaker** [comment]
It's due to updates to some dependent library. After updating my virtualenv I can reproduce this an similar errors on my own machine. I'll keep looking into it.

**Comment by dcbaker** [comment]
Okay, I finally broke out git bisect, and this is broken as soon as the abook tests are added. I think it's actually tickling a real bug in the settings module (I've traced it back to something in `settings.utils.read_config`), but I'm still not exactly sure what it is or why it only manifests on travis.
