### ISSUE TITLE
Sign release tags and tarballs

### ISSUE THREAD

**Issue by jljusten** [pazz/alot#1077]
Would it be possible to sign future release tags and provide associated .asc signature files?

This page might be helpful:
https://wiki.debian.org/Creating%20signed%20GitHub%20releases

It would be too late to sign the tags, since that must be done at tag creation time, but I think the tarballs could still be signed on previous releases.

**Comment by jljusten** [comment]
I removed 'future' from the title, because it would be good to sign (at least) the latest release tarball, even though the same is not possible for the previous release tags.

**Comment by pazz** [comment]
Sure: I'll have a look at this later this week. It's not urgent due to
some upcoming debian deadline or so is it?

**Comment by jljusten** [comment]
> It's not urgent due to some upcoming debian deadline or so is it?

No, it is not urgent, but #1069 is getting to be. (We might be dropped soonish if pygpgme is dropped.) Hopefully @dcbaker will get it sorted out soon enough.

This issue (signed tarballs) wouldn't block the package from being used in debian, so it is more of a nice-to-have.

**Comment by pazz** [comment]
Quoting Jordan Justen (2017-07-10 09:57:08)
>     It's not urgent due to some upcoming debian deadline or so is it?
> 
> No, it is not urgent, but #1069 is getting to be. (We might be dropped soonish
> if pygpgme is dropped.) Hopefully @dcbaker will get it sorted out soon enough.
> 
> This issue (signed tarballs) wouldn't block the package from being used in
> debian, so it is more of a nice-to-have.

OK great, thanks for bringing this up Jordan!

**Comment by dcbaker** [comment]
I'm working on #1069 currently, I'll go ahead and assign it to myself.

**Comment by pazz** [comment]
done: https://github.com/pazz/alot/releases/tag/0.5.1
I will sign new release tags from now on as well. Thanks.

**Comment by jljusten** [comment]
The 0.7 release: https://github.com/pazz/alot/releases/tag/0.7
contains a 0.7.asc file. What does it sign?

Would it be possible to get a signature of the 0.7.tar.gz with a filename like 0.7.tar.gz.asc or alot-0.7.tar.gz.asc? The 0.6 release used alot-0.6.tag.gz.asc.

**Comment by pazz** [comment]
sure (updated the release just now)
