### ISSUE TITLE
Suggestion: tag implication and TaskWarrior integration

### ISSUE THREAD

**Issue by pdigiglio** [pazz/alot#1080]
I'd like to propose two features:

__Tag implication__ Maybe this is more a `notmuch` enhancement, but I think it could be useful to implement a tag hierarchy, e.g.
```
            -- thesis
           /
university --- physics --- QFT
                       \
                        -- classical_mechanics
```
So that, if one tags an e-mail as `QFT`, (s)he automatically gets the `physics` and `university` tags.

__TaskWarrior Integration__ Some sort of integration with [TaskWarrior](https://taskwarrior.org/) could also be cool, e.g. to associate a deadline to an e-mail.

**Comment by lucc** [comment]
Something like this can easily be emulated with a script:
```sh
notmuch +physics -- tag:QFT or tag:classical_mechanics
notmuch +university -- tag:thesis or tag:physics
```

Then you can execute this as the last step in a notmuch-new or notmuch-insert hook. Or you can use the exit hook of alot or even some buffer leaving hook to execute this script (in the background?).

**Comment by lucc** [comment]
There is also a `post_global_tag` hook which might be interesting for both scripts.

**Comment by dcbaker** [comment]
The first is easily implemented in a notmuch tagging script. For example, mine has this in it:

```sh
notmuch tag +mesa        to:mesa-dev@lists.freedesktop.org and not tag:mesa
notmuch tag +piglit      to:piglit@lists.freedesktorp.org and not tag:piglit
notmuch tag +mailinglist '(' tag:piglit or tag:mesa ')' and not tag:mailinglist
```

I have this shell script set up to be called after mbsync pulls my email in a systemd user unit file.

**Comment by pdigiglio** [comment]
Thanks everybody! About TaskWarrior, I was not thinking about emulating its behavior with tags. My idea was that one should have the ability to add a task in TaskWarrior, with a summary that links to the e-mail, maybe with a ` -- see id:<mail_id>` suffix.

As an example, let's say I book a bus ticket to Rome for February the 30th, 2018. When I receive the booking confirmation, I type `:add-task` (or whatever the command would be called), and a TaskWarrior task template shows up. It looks somethink like that:
```
# The 'task <id> edit' command allows you to modify all aspects of a task
# using a text editor.  Below is a representation of all the task details.
# Modify what you wish, and when you save and quit your editor,
# Taskwarrior will read this file, determine what changed, and apply
# those changes.  If you exit your editor without saving or making
# modifications, Taskwarrior will do nothing.
#
# Lines that begin with # represent data you cannot change, like ID.
# If you get too creative with your editing, Taskwarrior will send you
# back to the editor to try again.
#
# Should you find yourself in an endless loop, re-editing the same file,
# just quit the editor without making any changes.  Taskwarrior will
# notice this and stop the editing.
#
# Name               Editable details
# -----------------  ----------------------------------------------------
# ID:                1
# UUID:              ec39c2d8-ac81-48f2-8cf3-44ca7f793166
# Status:            Pending
# Mask:              
# iMask:             
  Project:           
# Separate the tags with spaces, like this: tag1 tag2
  Tags:              
  Description:       Trip to Rome -- see id:whatever
  Created:           2017-07-12 13:08:10
  Started:           
  Ended:             
  Scheduled:         
  Due:               2018-02-30 10:00:00
  Until:             
  Recur:             
  Wait until:        
# Modified:          
  Parent:            
# Annotations look like this: <date> -- <text> and there can be any number of them.
# The ' -- ' separator between the date and text field should not be removed.
# A "blank slot" for adding an annotation follows for your convenience.
  Annotation:        2017-07-12 13:08:17 -- 
# Dependencies should be a comma-separated list of task IDs/UUIDs or ID ranges, with no spaces.
  Dependencies:      
# User Defined Attributes
  UDA priority:      
# End
```
So the user can fill in the relevant data (often, at least `Description` and `Due`) and have the task show in the `task next` list.

**Comment by pazz** [comment]
Sounds like an awesome feature that would best be implemented in a hook!

Recall that you can call (and thus keybind) hook code using `call hookname`.
(Note to self: maybe we should advertise this better)
You will find [examples in our wiki](https://github.com/pazz/alot/wiki/Contrib-Hooks#manually-marking-a-github-notification-as-read) how to do this.
It should not be difficult to write a python hook that 

- extracts the mail + thread ID and mail content from the current (thread) buffer,
- builds a tempfile and points $EDITOR to this
- calls task
- uses `alot.ui.UI` to provide some feedback (e.g. notifications).

I'll close this here as it makes little sense as feature in alot proper.
Have fun!
