### ISSUE TITLE
Quantified code shutting down

### ISSUE THREAD

**Issue by dcbaker** [pazz/alot#1087]
Quantified code is due to shut down on July 22nd (which is in ~5 days). The service is pretty useful I think, and having something that looks at our code is worthwhile.

I see two popular options: coverall and code climate. I haven't really evaluated either of them, and I haven't done a ton of looking, but I'm hoping by picking a popular product it wont fold on us like quantified-code is.

Suggestions, comments, opinions?

**Comment by lucc** [comment]
I am all for automated code reviews, linters, whatnot. So if any of these can be activated and does provide some information, I am all for it.

As @pazz mentioned recently quantify code was running bandit. This can also be run from the command line, just like pylint, pycodestyle and maybe others. I recently used coverage to get a nice html overview of our test coverage. So maybe we can also make a list of command line programs (and their switches or config options) that we use or recomend for developing on alot.

**Comment by pazz** [comment]
It seems there are so many of these code review integration tools around, but in the end I suppose they all run a hand full of standard cmd line tools.

activated for this repo so far:

* codacy
* https://codeclimate.com/dashboard

alternative:

* https://www.codefactor.io/features
* https://docs.ebertapp.io/engines/

**Comment by pazz** [comment]
I'll replace the QC badge by a codacity one for now: <a href="https://www.codacy.com/app/patricktotzke/alot?utm_source=github.com&amp;utm_medium=referral&amp;utm_content=pazz/alot&amp;utm_campaign=Badge_Grade"><img src="https://api.codacy.com/project/badge/Grade/fa7c4a567cd546568a12e88c57f9dbd6"/></a>

@lucc I could make codacy also produce a coverage badge if you'd want one, but I think it needs a [config file or something](https://github.com/codacy/python-codacy-coverage#setup). Got one?

**Comment by pazz** [comment]
[![Issue Count](https://codeclimate.com/github/pazz/alot/badges/issue_count.svg)](https://codeclimate.com/github/pazz/alot)

[![Code Climate](https://codeclimate.com/github/pazz/alot/badges/gpa.svg)](https://codeclimate.com/github/pazz/alot)

[![Test Coverage](https://codeclimate.com/github/pazz/alot/badges/coverage.svg)](https://codeclimate.com/github/pazz/alot/coverage)

**Comment by dcbaker** [comment]
@pazz Quantified code has completely shut down now. Can you remove the integration from the repo? It blocks anyone but you from merging code since it never returns an "all good"

**Comment by lucc** [comment]
And here I was wondering why it took so long on #1097

**Comment by pazz** [comment]
done :-)

**Comment by dcbaker** [comment]
thanks!

**Comment by lucc** [comment]
@pazz about coverage: If I read the docs correctly we have to calculate the coverage report ourselfs and then send it to them. This means we need travis to do that for us. If you want it I can try to look into it.

**Comment by pazz** [comment]
@lucc if you'd like that coverage badge yes, please do so, thanks!

**Comment by lucc** [comment]
@pazz I think I need your help to generate some API token to access the codacy project from travis. See [here](https://github.com/codacy/python-codacy-coverage#updating-codacy). I think that token should be stored as a secure env var in travis: [howto](https://docs.travis-ci.com/user/environment-variables/#Defining-encrypted-variables-in-.travis.yml)
