### ISSUE TITLE
Incorrect message count after running untag --all

### ISSUE THREAD

**Issue by samdmarshall** [pazz/alot#1098]
I noticed that the message count of currently displayed items is incorrect after running (for example) `untag --all unread`. Please see attached screenshots and the numbering in the lower right.

Before:
![img_0043](https://user-images.githubusercontent.com/1087718/28839344-589b24e4-76c1-11e7-9759-6826aa1d7bd9.PNG)

After:
![img_0044](https://user-images.githubusercontent.com/1087718/28839345-58a382d8-76c1-11e7-8cd1-0823dcf4bd41.PNG)

**Comment by lucc** [comment]
I can reproduce this. Move to any message in any search buffer and then do
```
tag some_random_foobar_tag
search tag:some_random_foobar_tag
untag --all some_random_foobar_tag
```

**Comment by lucc** [comment]
If you search for something which returns no threads in the first place the count is 0 though.
