### ISSUE TITLE
insufficient warning for sending encrypted messages without key

### ISSUE THREAD

**Issue by dcbaker** [pazz/alot#1105]
If you attempt to send an email to one or more recepients that you don't have an encryption key for alot breifly flashes a warning, and then continues to your editor. This seems less than ideal.

**Comment by pazz** [comment]
agreed. This should show just before sending (in envelope.SendCommand)

**Comment by lucc** [comment]
Do you want to make the delay for the notification longer or do you want to make the notification blocking? I use the `encrypt` and get this notification for many recipients. For me (my workflow) it might be bothersome if it were blocking.

**Comment by pazz** [comment]
it aounds like that this warning is triggered in the global compose command, just before it ends and calls EditCommand. If thats indeed the case we could move the warning into envelope.SendCommand or similar?
I think the nicest solution would be one blocking notification between the user hitting 'send' and it actually happening

**Comment by dcbaker** [comment]
I think there's two problems:
1) the editor it opened immediately after the warning effectively hiding it
2) the warning doesn't really explain the problem.

The biggest issue to me is that when you're encrypting, if you can't encrypt to all of the recepients it's worthless, and we should probably have a prompted message similar to the one we have for the bcc issue, "your are about to send an encrypted message to the following people: {}, who will not be able to decrypt it, do you want to continue?" This issue is compounded in complexity by `encrypt_by_default`.

I think what we really want is another option, `encrypt_to_missing` (or similar), that is a `['yes', 'no', 'prompt']` setting that controls what happens when sending to recipients who wouldn't be able to read it. Does that make sense?

**Comment by pazz** [comment]
I agree that we need a better warning text in a reliably visible notification.
I'm not sure about the config issue, as 'prompt' sounds like a pretty sensible default and don't think many people will want to change it. But if you prefer to have such an option, sure.

**Comment by lucc** [comment]
I agree that the notification should be moved to the envolope buffer. There are many options which control the behaviour when executing `compose` (spawn a new term, in a new thread, or not, what type of editor, ...) so a notification at this point is hard to get consistent for all users.

**Comment by meskio** [comment]
Hasn't this issue being solved by 6acea172e02f9c30712bbf8ae9a81656c67ff3c5?

**Comment by varac** [comment]
Indeed, imo this issue can get closed.

**Comment by lucc** [comment]
@dcbaker can we close this or do you still want to track the feature request for the new `encrypt_to_missing` here? Or is that feature request invalid by now?
