### ISSUE TITLE
Can pip install for python3, but alot doesn't support python 3

### ISSUE THREAD

**Issue by hsanson** [pazz/alot#1118]
Alot can be installed via pip3 for python3 but it does not run in python3.

**Comment by lucc** [comment]
People are working on it: #800, #1055, https://github.com/pazz/alot/milestone/10

You can open a PR to check the python version in setup.py if you want.

**Comment by dcbaker** [comment]
I think this is actually a problem with our setup.py, I think there's some
metadata you set to tell pypi (and pip) what versions you support.

I'm on mobile, please excuse autocorrect fail.

**Comment by dcbaker** [comment]
This is a real issue. we do need to add a `python_requires` field in setup.py. I'll send a PR
