### ISSUE TITLE
pip version out of date

### ISSUE THREAD

**Issue by dcbaker** [pazz/alot#1121]
alot in pip is still at version 0.4. It looks like maybe @geier is the owner of that package? Do the current owners have interest in maintaining it? If not I'd be willing to take over that duty.

**Comment by geier** [comment]
You are right, I'm one of the owner's of the package. I'm interested in maintaining it, I missed the last releases though (I just uploaded 0.5.1 though). If you send me your PyPI username, I'll add you as an owner.

**Comment by dcbaker** [comment]
It's dcbaker, thanks!

I'll go ahead and close this.

**Comment by geier** [comment]
I have just added you as an owner.

Quoting Dylan Baker (2017-08-18 18:35:44)

**Comment by seschwar** [comment]
The pypi version is still at 0.5.1 even with 0.6 available.

**Comment by geier** [comment]
Thanks and fixed.

Quoting Sebastian Schwarz (2017-09-04 13:48:24)
