### ISSUE TITLE
prep for 0.6 release?

### ISSUE THREAD

**Issue by dcbaker** [pazz/alot#1123]
We have alot (heh) of patches since the 0.5 release; including replacing pygpgme (which debian would like to have). And I don't see any series outstanding that are critically needed immediately. How would we feel about making a release next week (pending any regressions from 0.5.1 being reported in the mean time) and not merge anything but fixes or comment/documentation updates until then?

**Comment by lucc** [comment]
I also don't have any bugs bugging me :)

**Comment by pazz** [comment]
cool with me

**Comment by dkg** [comment]
On Thu 2017-08-17 19:58:56 +0000, Dylan Baker wrote:
> We have alot (heh) of patches since the 0.5 release; including
> replacing pygpgme (which debian would like to have). And I don't see
> any series outstanding that are critically needed immediately. How
> would we feel about making a release next week (pending any
> regressions from 0.5.1 being reported in the mean time) and not merge
> anything but fixes or comment/documentation updates until then?

I'm sorry i haven't had any time to devote to alot recently.  But I'm
happy to see the progress made, and i'd be happy to see a 0.6 release :)

   --dkg

**Comment by pazz** [comment]
github suggests adding a CONTRIBUTING text file that outlines this projects procedures.
We do have a [section on this](http://alot.readthedocs.io/en/latest/api/contributing.html) in the docs..
Do you want to update/extend this? how about that CONTRIBUTING file?

**Comment by pazz** [comment]
Quoting Dylan Baker (2017-08-18 17:37:35)
> I think that would be good. May I suggest that we use restructured text for the
> format (like the sphinx documentation) and have CONTRIBUTING.rst? Github will
> automatically format it nicely for anyone viewing from a web browser.

Ideally, we could somehow let sphinx pick up this file as well when it
generates the docs.
Or we can just drop the contributing subsecion from the html docs..

**Comment by dcbaker** [comment]
I think we can get sphinx to do that. I think I've done it. I'll look at it.

**Comment by dcbaker** [comment]
I filed a pull request with a CONTRIBUTING file and an issue template.

**Comment by pazz** [comment]
anything else you want to land/change/wait for?

**Comment by dcbaker** [comment]
No I think we're good to go.

**Comment by pazz** [comment]
did you have a preference for the version string? `0.6` or `0.6.0`?

**Comment by dcbaker** [comment]
0.6.0 I think. Since we've had a 0.5.1 we might as well have 0.6.0

**Comment by pazz** [comment]
i was thinking 0.6 since we had 0.5 and 0.4 before as 'major' release bumps..

**Comment by dcbaker** [comment]
That would be fine, I don't have a strong preference either way.

**Comment by pazz** [comment]
ok cool, I've just pushed the release tag :)

**Comment by jljusten** [comment]
@pazz: Can you sign the tarball too?

**Comment by pazz** [comment]
Quoting Jordan Justen (2017-08-20 16:03:59)
> @pazz: Can you sign the tarball too?

Oh! thanks for reminding me (again).
I've just done it, and also updated my release todo file, so let's hope
I won't forget next time :)
cheers,
