### ISSUE TITLE
Can not `:send` mail,  TypeError: 'unicode' does not have the buffer interface

### ISSUE THREAD

**Issue by lucc** [pazz/alot#1132]
Software Versions
-----------------

Python version: 2.7.13

Alot version: master+lucc/fix/hash (20dab95640592bd4f539a8a781f0c80c21cc5708)

Observed behavior
-----------------

I compose a mail, when I `:send` it I get a notification for this exception:

```
DEBUG:__init__:ARGS: [u'send']
DEBUG:__init__:cmd parms {}
DEBUG:envelope:signing plaintext: Content-Type: text/plain; charset="utf-8"
MIME-Version: 1.0
Content-Transfer-Encoding: quoted-printable

hans

ERROR:ui:Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/home/luc/vcs/alot/alot/ui.py", line 679, in call_apply
    return defer.maybeDeferred(cmd.apply, self)
  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 1532, in unwindGenerator
    return _inlineCallbacks(None, gen, Deferred())
--- <exception caught here> ---
  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 1386, in _inlineCallbacks
    result = g.send(result)
  File "/home/luc/vcs/alot/alot/commands/envelope.py", line 217, in apply
    self.mail = email_as_string(self.mail)
  File "/home/luc/vcs/alot/alot/helper.py", line 611, in email_as_string
    g.flatten(mail)
  File "/usr/lib/python2.7/email/generator.py", line 83, in flatten
    self._write(msg)
  File "/usr/lib/python2.7/email/generator.py", line 115, in _write
    self._write_headers(msg)
  File "/usr/lib/python2.7/email/generator.py", line 142, in _write_headers
    print >> self._fp, '%s:' % h,
exceptions.TypeError: 'unicode' does not have the buffer interface
```

Expected behavior
-----------------

Mail should be send with the external command.

Further notes
-------

@dcbaker it looks like this is a bug in the recent changes about StringIO and BytesIO. I will try to look into it but if you know what is going on feel free to send a fix.

**Comment by lucc** [comment]
This seems to fix it:

```diff
diff --git a/alot/helper.py b/alot/helper.py
index ce307875..1c569a23 100644
--- a/alot/helper.py
+++ b/alot/helper.py
@@ -10,6 +10,7 @@ from datetime import timedelta
 from datetime import datetime
 from collections import deque
 from io import BytesIO
+from cStringIO import StringIO
 import logging
 import mimetypes
 import os
@@ -606,7 +607,7 @@ def email_as_string(mail):
     :param mail: email to convert to string
     :rtype: str
     """
-    fp = BytesIO()
+    fp = StringIO()
     g = Generator(fp, mangle_from_=False, maxheaderlen=78)
     g.flatten(mail)
     as_string = RFC3156_canonicalize(fp.getvalue())
```

But that just undoes part of fa3dd1b04567c4ea03fa658c3838b569531c79f5. All I can learn from that is that the other changes in fa3dd1b04567c4ea03fa658c3838b569531c79f5 seem fine, but not why this particular line needs a `cStringIO.StringIO()` object.

**Comment by dcbaker** [comment]
I'm actually surprised that fixes it. My understanding was
cStringIO.StringIO was io.BytesIO.

I think this would fix it:
Ifinstance(mail, unicode):
     mail =mail.encode()

Either that or use io.StringIO if mail is a Unicode.

I'm on mobile, please excuse autocorrect fail.


On Aug 20, 2017 6:29 AM, "Lucas Hoffmann" <notifications@github.com> wrote:

This seems to fix it:

diff --git a/alot/helper.py b/alot/helper.py
index ce307875..1c569a23 100644--- a/alot/helper.py+++
b/alot/helper.py@@ -10,6 +10,7 @@ from datetime import timedelta
 from datetime import datetime
 from collections import deque
 from io import BytesIO+from cStringIO import StringIO
 import logging
 import mimetypes
 import os@@ -606,7 +607,7 @@ def email_as_string(mail):
     :param mail: email to convert to string
     :rtype: str
     """-    fp = BytesIO()+    fp = StringIO()
     g = Generator(fp, mangle_from_=False, maxheaderlen=78)
     g.flatten(mail)
     as_string = RFC3156_canonicalize(fp.getvalue())

But that just undoes part of fa3dd1b
<https://github.com/pazz/alot/commit/fa3dd1b04567c4ea03fa658c3838b569531c79f5>.
All I can learn from that is that the other changes in fa3dd1b
<https://github.com/pazz/alot/commit/fa3dd1b04567c4ea03fa658c3838b569531c79f5>
seem fine, but not why this particular line needs a cStringIO.StringIO()
object.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/pazz/alot/issues/1132#issuecomment-323585092>, or mute
the thread

**Comment by lucc** [comment]
I have not yet managed to construct a failing test for this: https://github.com/lucc/alot/compare/fix/hash...lucc:test/bug-1132 So I am not yet sure what the object we pass to email_as_string does or has or is that makes it fail.

By the way it is not an unicode object but `isinstance(mail, email.message.Message)`. So there is no encode method on that.

**Comment by lucc** [comment]
When I use `io.StringIO` instead of `io.BytesIO` (2to3 would replace python2's `cStringIO.StringIO` with python3's `io.StringIO`) like this
```diff
diff --git a/alot/helper.py b/alot/helper.py
index ce307875..81798c43 100644
--- a/alot/helper.py
+++ b/alot/helper.py
@@ -10,6 +10,7 @@ from datetime import timedelta
 from datetime import datetime
 from collections import deque
 from io import BytesIO
+import io
 import logging
 import mimetypes
 import os
@@ -606,7 +607,7 @@ def email_as_string(mail):
     :param mail: email to convert to string
     :rtype: str
     """
-    fp = BytesIO()
+    fp = io.StringIO()
     g = Generator(fp, mangle_from_=False, maxheaderlen=78)
     g.flatten(mail)
     as_string = RFC3156_canonicalize(fp.getvalue())
```
I get this exception instead (trace and exception type are teh same, only message differs)
```
ERROR:ui:Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/home/luc/vcs/alot/alot/ui.py", line 679, in call_apply
    return defer.maybeDeferred(cmd.apply, self)
  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 1532, in unwindGenerator
    return _inlineCallbacks(None, gen, Deferred())
--- <exception caught here> ---
  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 1386, in _inlineCallbacks
    result = g.send(result)
  File "/home/luc/vcs/alot/alot/commands/envelope.py", line 215, in apply
    self.mail = self.envelope.construct_mail()
  File "/home/luc/vcs/alot/alot/db/envelope.py", line 189, in construct_mail
    plaintext = helper.email_as_string(inner_msg)
  File "/home/luc/vcs/alot/alot/helper.py", line 613, in email_as_string
    g.flatten(mail)
  File "/usr/lib/python2.7/email/generator.py", line 83, in flatten
    self._write(msg)
  File "/usr/lib/python2.7/email/generator.py", line 115, in _write
    self._write_headers(msg)
  File "/usr/lib/python2.7/email/generator.py", line 142, in _write_headers
    print >> self._fp, '%s:' % h,
exceptions.TypeError: unicode argument expected, got 'str'
```

**Comment by lucc** [comment]
> I'm actually surprised that fixes it. My understanding was
cStringIO.StringIO was io.BytesIO.

How could it not fix the bug? That was the code we had there before fa3dd1b04567c4ea03fa658c3838b569531c79f5.
