### ISSUE TITLE
Hooks example not working?

### ISSUE THREAD

**Issue by pazz** [pazz/alot#1143]
I've just tried to use some of the new user contributed hooks and initially forgot to call them as `call hooks.X` instead of just `call X`..
Anyway, the example hook from the docs (belog) seems to do nothing at all any more, on the master branch. Any idea why?

```
cat .config/alot/hooks.py                                                        
import logging
from alot.settings import settings
def pre_global_exit(**kwargs):
    accounts = settings.get_accounts()
    if accounts:
        logging.info('goodbye, %s!' % accounts[0].realname)
    else:
        logging.info('goodbye!')
```

```
alot --debug=info --log log
cat log
INFO:account:Deprecation warning: The format for the encrypt_by_default option changed.  Please use 'none', 'all' or 'trusted'.
INFO:ui:setup gui in 256 colours
```

So logging generally works, and so do other hooks that I call directly, [like the one for version strings](https://github.com/pazz/alot/wiki/Contrib-Hooks#knowing-which-versionbranchcommit-of-alot-you-are-using)

**Comment by pazz** [comment]
the code seems to be incompatible with the master branch:

```
[~] alot pyshell                                                                     
Python 2.7.13 (default, Jan 19 2017, 14:48:08) 
[GCC 6.3.0 20170118] on linux2
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from alot.settings import settings
Traceback (most recent call last):
  File "<console>", line 1, in <module>
ImportError: cannot import name settings
>>> 

```

**Comment by dcbaker** [comment]
Yeah. the settings instance was moved into alot.settings.const before 0.6. That was what was causing alot tests to fail on travis for eveyone but you, in some cases it could create a circular import.

**Comment by dcbaker** [comment]
I guess we should really check the hooks before making a release.

**Comment by pazz** [comment]
Quoting Dylan Baker (2017-08-25 18:13:46)
> I guess we should really check the hooks before making a release.

next time.. :)

Thanks for the pointer. I think it's OK for now if we just adjust the
docs. I'll do this later unless s/o beats me to it.

**Comment by dcbaker** [comment]
@pazz I remember a patch about hooks landing, did you fix this?

**Comment by pazz** [comment]
yes, I adjusted the hook in the docs to use the new interface.
