### ISSUE TITLE
.github/CONTRIBUTING.rst is not picked up as expected

### ISSUE THREAD

**Issue by pazz** [pazz/alot#1145]
It seems that it has to live in the root dir?

**Comment by dcbaker** [comment]
It shows up fine for me. Maybe because you're the repo owner? I can send a
screenshot later if you like.

I'm on mobile, please excuse autocorrect fail.

**Comment by pazz** [comment]
I'm not sure exactly where it should show but I cannot see it on the
"new issue" page, and if if click on  project insights -> community (https://github.com/pazz/alot/community)
it asks me to put up a CONTRIBUTING file still..

**Comment by dcbaker** [comment]
File a pull request. I see it there. The documentation for that says all of
the GitHub stuff can go in a .github folder

I'm on mobile, please excuse autocorrect fail.

**Comment by lucc** [comment]
I can see the link to the contributing file when I try to open a new issue. I also see the "missing" status under community that pazz mentioned. A bug on github's side?

**Comment by dcbaker** [comment]
Maybe because the extension is rst?

I'm on mobile, please excuse autocorrect fail.

**Comment by pazz** [comment]
I was just typing a support request when I saw that the file is now picked up as expected under https://github.com/pazz/alot/community. I still don't see it in the web interface when opening new PR's, but I don't really mind (I usually do this with [hub](http://hub.github.com/) from the command line)..
