### ISSUE TITLE
Email with no 'From' header crash alot

### ISSUE THREAD

**Issue by dcbaker** [pazz/alot#1150]
Software Versions
-----------------
Python version: 2.7.13
Alot version (either a number or sha for master): de56be946af8a25a172ee37b02cd9a66d31d83df

Observed behavior
-----------------
Alot crashes while trying to compare email adresses since the from is set to `('', '')`, the later of which cannot be split by `@` in the Address class.

Expected behavior
--------------------------
Not crashing.

I'm looking into this, but it's a difficult one to fix since we actually set the from to '' at several points in the code base.

**Comment by pazz** [comment]
how do you even receive mails without that header? :-)

**Comment by dcbaker** [comment]
It's actually a draft email. It might have been generated by outlook (Sometimes I have to use outlook for work, sometimes I can use alot)

**Comment by pazz** [comment]
oh i see. thx

**Comment by dcbaker** [comment]
closed by #1151
