### ISSUE TITLE
multiple values for sync_maildir_flags prevents sent mail saving to db

### ISSUE THREAD

**Issue by NoctuaNivalis** [pazz/alot#1154]
Python version: 2.7.13
Alot version: current master (afcdc5f)
[Configuration](https://github.com/NoctuaNivalis/dotfiles/blob/master/config/alot/config)
notmuch --version: notmuch 0.25+76~gec37900
pip2 freeze: notmuch==0.25

__Observed behavior__: Mails I send aren't saved upon sending. I get an error message instead. Mails are sent, and I receive them shortly after by IMAP. Traceback is below.

__Expected behavior__: Mail I send are saved.

```
ERROR:ui:Traceback (most recent call last):
  File "/home/noctua/.local/lib/python2.7/site-packages/twisted/internet/defer.py", line 321, in addCallback
    callbackKeywords=kw)
  File "/home/noctua/.local/lib/python2.7/site-packages/twisted/internet/defer.py", line 310, in addCallbacks
    self._runCallbacks()
  File "/home/noctua/.local/lib/python2.7/site-packages/twisted/internet/defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/home/noctua/.local/lib/python2.7/site-packages/alot/ui.py", line 679, in call_apply
    return defer.maybeDeferred(cmd.apply, self)
--- <exception caught here> ---
  File "/home/noctua/.local/lib/python2.7/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "/home/noctua/.local/lib/python2.7/site-packages/alot/commands/globals.py", line 576, in apply
    ui.dbman.flush()
  File "/home/noctua/.local/lib/python2.7/site-packages/alot/db/manager.py", line 143, in flush
    msg, _ = db.add_message(path, sync_maildir_flags=sync)
  File "/home/noctua/.local/lib/python2.7/site-packages/notmuch/database.py", line 474, in add_message
    self.index_file(self, filename, sync_maildir_flags=sync_maildir_flags)
exceptions.TypeError: index_file() got multiple values for keyword argument 'sync_maildir_flags'
```

**Comment by dcbaker** [comment]
What version of notmuch are you running?

**Comment by pazz** [comment]
hi, welcome to alot!
Are you using a recent version of not much and its python bindings?

**Comment by NoctuaNivalis** [comment]
I've editted the issue to include the notmuch version.

**Comment by dcbaker** [comment]
That's a notmuch bug. I'll send a patch for it. Thanks for reporting this.

**Comment by dcbaker** [comment]
patch for notmuch here: https://notmuchmail.org/pipermail/notmuch/2017/025256.html

**Comment by pazz** [comment]
what's happening here? why is this not a problem for anyone else? Is this a recent issue with notmuch master?

**Comment by dcbaker** [comment]
Yes, it's a commit that's not in a released version of notmuch.

**Comment by pazz** [comment]
Quoting Dylan Baker (2017-09-11 23:57:42)
> Yes, it's a commit that's not in a released version of notmuch.

Oh wow, great catch! thanks

**Comment by NoctuaNivalis** [comment]
Oh, sorry for getting the origin wrong, I should've read the traceback better. Thanks for fixing this so quickly.

**Comment by NoctuaNivalis** [comment]
I've been reading the linked threads (and my issue's fixed). I noted how `add_message` has been deprecated. Perhaps below trivial patch should be applied to alot:

```diff
diff --git a/alot/db/manager.py b/alot/db/manager.py
index dfd681d..0ece852 100644
--- a/alot/db/manager.py
+++ b/alot/db/manager.py
@@ -140,7 +140,7 @@ class DBManager(object):
                     if cmd == 'add':
                         logging.debug('add')
                         path, tags = current_item[2:]
-                        msg, _ = db.add_message(path, sync_maildir_flags=sync)
+                        msg, _ = db.index_file(path, sync_maildir_flags=sync)
                         logging.debug('added msg')
                         msg.freeze()
                         logging.debug('freeze')
```

**Comment by dcbaker** [comment]
that would bind alot to notmuch 0.25.1 (which was released today), in the long run yes we will, but that would make new versions of alot not work with fairly recent versions of notmuch.
