### ISSUE TITLE
The hooks object is of NoneType

### ISSUE THREAD

**Issue by hsanson** [pazz/alot#1156]
Software Versions
-----------------

Python version: 2.7.12

Alot version (either a number or sha for master): 0.7.0dev

Observed behavior
-----------------

None of my defined hooks work within alot. 

With the following hooks.py file with two simple hooks:

```python
import logging
import subprocess
from alot.settings import settings

def hello()
    pass

def getmail(ui=None):
    ui.notify("fetchinig %s email...")
    cmd = "~/.config/alot/mailcheck.sh"
    msg=subprocess.Popen(cmd.split(),stdout=subprocess.PIPE,stderr=subprocess.PIPE)

```

If I call any of the hooks with *call hooks.hello()* or *call hooks.getmail(ui)* results in the following error:

```
INFO:ui:setup gui in 256 colours
INFO:globals:open command shell
ERROR:globals:'NoneType' object has no attribute 'hello'
Traceback (most recent call last):
  File "/home/ryujin/.local/lib/python2.7/site-packages/alot/commands/globals.py", line 393, in apply
    exec(self.command)
  File "<string>", line 1, in <module>
AttributeError: 'NoneType' object has no attribute 'hello'
```
The error occurs when binding the call to a key or when invoking it directly in alot command prompt (:).

Note that I also tried specifying the hook file option in the configuration and the error still occurs.

Expected behavior
-----------------

Hooks should execute without any errors.

**Comment by hsanson** [comment]
Just found the issue minutes after posting this. If there is a syntax error in the hooks.py file it will silently be ignored.

The debug/log should show an error or warning if the hooks.py file is not loading correctly. A simple way to check is to open python interpreter and import hooks file there.

**Comment by lucc** [comment]
There is a log entry but it is only a debug entry. Maybe we should upgrade it to info or warning, is there any reason why it is only debug? (@pazz)

PS: alot/settings/manager.py line 94

**Comment by pazz** [comment]
@lucc i agree. This should at least trigger a warning level log entry.
