### ISSUE TITLE
Selected thread/email does not show their content/body. Only From, To and Subject are shown.

### ISSUE THREAD

**Issue by mbauhardt** [pazz/alot#1162]
Software Versions
-----------------

OS: osx 10.11.6

Python version: 2.7.10

Notmuch version: 0.25.1

Alot version (either a number or sha for master): 0.6 (installed via brew)

Observed behavior
-----------------

Some messages does not show any body. Only from,to and subject are shown.
The emails are text emails. with and without any gpg information like signing/encryption.
```
DEBUG:__init__:ARGS: [u'move', u'down']
DEBUG:__init__:cmd parms {'movement': [u'down']}
DEBUG:search:down
DEBUG:ui:Got key (['enter'], [10])
DEBUG:ui:cmdline: 'select'
DEBUG:ui:search command string: "select"
DEBUG:__init__:mode:search got commandline "select"
DEBUG:__init__:ARGS: [u'select']
DEBUG:__init__:cmd parms {}
INFO:search:open thread view for thread:000000000000cf5d: ***
DEBUG:utils:unquoted header: |***|
DEBUG:utils:unquoted header: |***|
DEBUG:utils:unquoted header: |***|
DEBUG:utils:unquoted header: |***|
DEBUG:buffers:Tbuffer: auto remove unread tag from msg?
DEBUG:buffers:Tbuffer: No, cursor on summary
DEBUG:buffers:Tbuffer: auto remove unread tag from msg?
DEBUG:buffers:Tbuffer: No, cursor on summary
DEBUG:ui:Got key (['d'], [100])
DEBUG:ui:cmdline: 'bclose'

```

Expected behavior
-----------------

I expect to see the content/body of my email. (neomutt is able to show me the body.)

**Comment by dcbaker** [comment]
Is this the last email in a long thread by chance?

**Comment by mbauhardt** [comment]
No, can be a single email. some emails has content, some not. i didn't figured out what the difference between those emails is.

**Comment by pazz** [comment]
Quoting Marko Bauhardt (2017-09-28 21:44:32)
> No, can be a single email. some emails has content, some not. i didn't figured
> out what the difference between those emails is.

please check the FAQ, point 5:
https://alot.readthedocs.io/en/latest/faq.html

**Comment by mbauhardt** [comment]
:)
thx. we figured that out before some minutes as well.
Sorry for that confusion. My `malcap` file was under my `~/.mutt` folder.
Maybe a warning message about unknown mime-type would helped me to understand what happened.

Anyway, thx for the fast reply.
