### ISSUE TITLE
Cannot select key for encryption by number keys

### ISSUE THREAD

**Issue by mschaaf** [pazz/alot#1164]
Please ensure that the following information is filled before filing
--------------------------------------------------------------------

I want to write an encrypted email and get two keys presented for encryption. The second is the one matching the email address. If I press the key 2 to select nothing happens. If I press the key 1 to select the first but wrong key is used.
Please run alot again with the options `-d debug -l log`.

```
DEBUG:ui:Got key ([':'], [58])
DEBUG:ui:cmdline: 'prompt'
DEBUG:ui:envelope command string: "prompt"
DEBUG:__init__:mode:envelope got commandline "prompt"
DEBUG:__init__:ARGS: [u'prompt']
DEBUG:__init__:cmd parms {'startwith': ''}
INFO:globals:open command shell
DEBUG:ui:Got key (['e'], [101])
DEBUG:ui:Got key (['n'], [110])
DEBUG:ui:Got key (['c'], [99])
DEBUG:ui:Got key (['r'], [114])
DEBUG:ui:Got key (['y'], [121])
DEBUG:ui:Got key (['p'], [112])
DEBUG:ui:Got key (['t'], [116])
DEBUG:ui:Got key (['enter'], [10])
DEBUG:globals:CMDLINE: encrypt
DEBUG:ui:envelope command string: "encrypt"
DEBUG:__init__:mode:envelope got commandline "encrypt"
DEBUG:__init__:ARGS: [u'encrypt']
DEBUG:__init__:cmd parms {'action': 'encrypt', 'trusted': False, 'keyids': []}
DEBUG:utils:encryption keys: [u'mb@datameer.com']
DEBUG:ui:Got key (['2'], [50])
DEBUG:ui:Got key (['2'], [50])
DEBUG:ui:Got key (['2'], [50])
DEBUG:ui:Got key (['2'], [50])
DEBUG:ui:Got key (['right'], [27, 91, 67])
DEBUG:ui:unhandled input: right
DEBUG:ui:Got key (['left'], [27, 91, 68])
DEBUG:ui:unhandled input: left
DEBUG:ui:Got key (['2'], [50])
DEBUG:ui:Got key (['1'], [49])
DEBUG:utils:encrypt to self: DF5137228A1A6B8F72E70C58868A83F8A86137C1
DEBUG:ui:Got key (['q'], [113])
DEBUG:ui:cmdline: 'exit'
DEBUG:ui:envelope command string: "exit"
DEBUG:__init__:mode:envelope got commandline "exit"
DEBUG:__init__:ARGS: [u'exit']
DEBUG:__init__:cmd parms {}
DEBUG:ui:Got key (['y'], [121])
DEBUG:globals:flush complete
```

Software Versions
-----------------

Python version: 2.7.12

Notmuch version: 0.25.1

Alot version (either a number or sha for master): master (0.7.0dev)

Observed behavior
-----------------
`
ambiguous keyid! Which key do you want to use?
(1):name <email 1> (2):name <email 2>
`
I can't select the second key. It didn't respond.
I can only select the first one.
Also pressing the key 1 did send the email but the mail is not encrypted with the choosen key.

Expected behavior
-----------------

Select the specified key.

**Comment by mbauhardt** [comment]
I have similar behaviour.
i have also an ambiguous key in my recipient list. But i can't select key (1), only key (2).

**Comment by dcbaker** [comment]
This should be resolved now, if it's not feel free to reopen.
