### ISSUE TITLE
GPG error: The 'gpg' distribution was not found and is required by alot

### ISSUE THREAD

**Issue by mor3dr3ad** [pazz/alot#1166]
Hello there,

I am trying to set up my Mail accounts using notmuch/afew and alot. Mail is grabbed by offlineimap.

I have run into problems when trying to start alot, specifically the error below is thrown.

Has somebody run into this problem?

Help is appreciated

Observed behavior
-----------------

Traceback (most recent call last):
  File "/usr/local/bin/alot", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3074, in <module>
    @_call_aside
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3058, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3087, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 664, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 981, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 867, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'gpg' distribution was not found and is required by alot

**Comment by pazz** [comment]
Hi. It seems you do not have python-gpg installed.
Please check out http://alot.readthedocs.io/en/latest/installation.html
or try 'pip install gpg' and close this issue if it solves your problem. Thanks

**Comment by mor3dr3ad** [comment]
Hey Pazz,

thanks for the quick reply. however, pip install gpg throws the following error:
'''''''
Need at least GPGME version 1.7, found 1.6.0.
'''''''

I tried installing gpgme from source, but the dependencies keep failing to install.

**Comment by pazz** [comment]
I'm not very familiar with pip.
If you're on debian/ubuntu a "sudo apt-get install libgpgme11 python-gpg" should do.

Anyway, this is not an issue with alot but with installing python-gpg.
You might want to try the gnupg mailing list for more help:
https://gnupg.org/documentation/mailing-lists.html

**Comment by dcbaker** [comment]
what version of python are you running? the latest version of python-gpgme in pypi (installed via pip) is 1.8.0.

**Comment by pazz** [comment]
i thought its python-gpg on pip?

**Comment by mor3dr3ad** [comment]
Hey, python -V shows python 2.7.12 running. pip install gpg throws an 
"error: command 'swig' failed with exit status 1". 

after installing swig the installation of gpg worked. 

But now alot says:
"The 'python-magic' distribution was not found and is required by alot"

However, I have python-magic installed from universe.

**Comment by pazz** [comment]
Quoting mor3dr3ad (2017-10-04 15:03:50)
> However, I have python-magic installed from universe.

From where now?

**Comment by dcbaker** [comment]
that's the Ubuntu equivalent of Debian's non-free repo

**Comment by pazz** [comment]
Oh I see, thanks.
Well. The whole issue seems only related to alot in that it seems
difficult to install all dependencies on ubuntu. That's odd given that alot is packaged for ubuntu.
When this is resolved, maybe it is worth extending the INSTALL notes re
ubuntu?

**Comment by dcbaker** [comment]
@mor3dr3ad, which version of ububtu are you running?

@pazz I suspect that the packages will trickle down from debian in artful, but we may need to have an ubuntu specifc section in the install notes. Or find someone willing to run a PPA.

**Comment by mor3dr3ad** [comment]
@pazz: yes, I agree. after installing python-magic via pip, alot started up. so it seems that installing the dependencies via pip instead of apt-get seems to be a workaround for now. however that leaves you with two versions of the same program installed which some users surely will find rather unsatisfying. glad to provide more information if needed.

@dcbaker: running ubuntu 16.04 lts with kernel 4.10.0-35-generic

**Comment by dcbaker** [comment]
Ah, LTS distros. getting dependencies to work on them is somewhat painful. how did you install alot? via pip or via setuptools?

**Comment by mor3dr3ad** [comment]
So, I finally managed to install alot from source. however, the given directory for the config file (~/.config/alot/config) does not exist. any clues where the config could be instead?

Another question: if I installed via 'python setup.py install', is there a way to uninstall?

**Comment by mor3dr3ad** [comment]
closing issue, opening new thread
