### ISSUE TITLE
Issue with .config/alot/config - uninstall alot when installed from source?

### ISSUE THREAD

**Issue by mor3dr3ad** [pazz/alot#1167]
Hey there,

I finally managed to install alot from source. However, for me (ubuntu 16.04 lts) no ~/.config/alot/config shows up (where it is supposed to be according to the doc). 

Anybody run across the same issue?

I would like to try and install alot from repositories to see if this changes things. Before that I want to uninstall the current version. How can alot be uninstalled when originally installed via 'python setup.py install' ?

Thanks!

**Comment by NoctuaNivalis** [comment]
I'm not sure I recall this correctly, but shouldn't you just create it yourself?

**Comment by dcbaker** [comment]
Yes. you're expected to create it yourself.
