### ISSUE TITLE
Hook for calling 'offlineimap && notmuch new && afew --tag --new' not working

### ISSUE THREAD

**Issue by mor3dr3ad** [pazz/alot#1168]
Hey, 

I am trying to set up a hook to call offlineimap, notmuch and afew to fetch and tag my mail when I exit or refresh alot. 

This is the code in the ~/.config/alot/hooks.py file. It is supposed to call 'getmail' which is an alias for 'offlineimap && notmuch new && afew --tag --new'. 

However the hook is not working. 

hook
-----------------
    import logging
    import subprocess

    from alot.settings.const import settings

    def pre_global_exit(**kwargs):
        accounts = settings.get.accounts()
        logging.info('Syncing mail with offlineimap')

        subprocess.call(['getmail'])

        if accounts:
            logging.info('goodbye, %s!' % accounts[0].realname)
        else:
            logging.info('goodbye!')

    def pre_global_refresh(**kwargs):
        logging.info('Syncing mail with offlineimap')

        subprocess.call(['getmail'])

Observed Behaviour
-----------------

:call pre_global_refresh()
within alot throws 'name not defined'

:call hooks.pre_global_refresh()
within alot throws 'NoneType' object has no attribute pre_global_refresh()

Can somebody point me in the right direction?

Cheers

**Comment by pazz** [comment]
Have you seen https://github.com/pazz/alot/wiki/Contrib-Hooks#getting-new-msg-while-alot-is-running?

**Comment by mor3dr3ad** [comment]
Thanks, yeah I have seen the hook. And I have also been through the documentation ;), sorry if I am spamming.

I only tried to call the hooks manually in order to see if they work. 

For debugging I have tried the https://github.com/pazz/alot/wiki/Contrib-Hooks#getting-new-msg-while-alot-is-running. However, it also results in 'None Type' object has no attribute getmail.

**Comment by pazz** [comment]
are you sure that your hooks.py file is syntactically correct? IIRC, if it's not, alot will simply continue as if it's not present (not great, i know). Does the logfile say anything about this?

By the way: that "getmail" hook from the wiki behaves as expected for me. Are you sure that you added it to your hooks.py? (the above code doesn't include it). In any case, instead of using a hook, you could also directly call your shellscript, using the `shellescape` command:

```
[bindings]
% = "shellescape '/home/pazz/bin/pullmail.sh'; refresh"
```

**Comment by pazz** [comment]
FWIW: https://github.com/pazz/alot/wiki/pazz's-mail-setup
