### ISSUE TITLE
which gpg python library is in use ?

### ISSUE THREAD

**Issue by teto** [pazz/alot#1169]
I've had a hard time tracking the dependancy from https://pypi.python.org/pypi/gpg . It says the homepage is gnupg.org but thre I could not find the python gpg bindings (and there are lots via google).
I suppose I finally found it, but could you confirm ? I need to package it for my distrib and would like to patch it.
https://git.gnupg.org/cgi-bin/gitweb.cgi?p=gpgme.git;a=tree;f=lang/python;hb=refs/heads/master

**Comment by dkg** [comment]
The python `gpg` module is distributed with (and generally built from) the [gpgme](https://www.gnupg.org/software/gpgme/) sources.

The python module is already packaged from gpgme [for debian](https://packages.debian.org/unstable/python3-gpg) and [fedora](https://koji.fedoraproject.org/koji/rpminfo?rpmID=10951210) and [ubuntu](https://packages.ubuntu.com/zesty/python3-gpg) and [arch](https://www.archlinux.org/packages/core/x86_64/python-gpgme/) and [gentoo](https://packages.gentoo.org/packages/app-crypt/gpgme).  

> I need to package it for my distrib

What is "my distrib" ?

> and would like to patch it.

You might want to use upstream's [source repository](https://dev.gnupg.org/source/gpgme/) and [bugtracker](https://dev.gnupg.org/maniphest/task/edit/form/1/) (you should put "gpgme" in the "tags" field when reporting a bug).

Feel free to reopen this bug report if you have more questions.

**Comment by teto** [comment]
Thanks for the detailed answer, the distrib is "nixos". 
I've a working package though 3 of the tests fail, if you have any idea especially for the unicode ones, that would be nice:
https://github.com/NixOS/nixpkgs/issues/30392#issuecomment-336627575
