### ISSUE TITLE
startup hook

### ISSUE THREAD

**Issue by deadc0de6** [pazz/alot#1185]
Is there any specific hook similar to [exit()](https://alot.readthedocs.io/en/latest/configuration/hooks.html#exit) that would be called when alot is starting ?

**Comment by lucc** [comment]
The hooks file will be sourced so you can put your code at the top level of that.

**Comment by pazz** [comment]
But I agree that a dedicated hook would be nice. One that could assume that the whole UI is properly initialized..

**Comment by lucc** [comment]
Obviously it would be nice to have. If one really needs to run code at startup that has the full ui available one can either use the initial command to run some python code (with `:call`) or it should be possible to simulate a startup hook with a post_buffer_focus hook. It could set a (module) global variable to check that it did run already (so it will only run once at startup). Something like:
```py
did_run = False
def  post_buffer_focus(*args, **kwargs):
    global did_run
    if not did_run:
        did_run = True
        do_startup_stuff()
    do_other_post_buffer_focus_stuff()
```

**Comment by dcbaker** [comment]
I'm in the camp that thinks using global means you need to refactor. I
think an init hook could be useful, and certainly wouldn't object to one.

I'm on mobile, please excuse autocorrect fail.

**Comment by lucc** [comment]
Ups, after several edits the "meanwhile" after my first sentence above is missing.

**Comment by lucc** [comment]
By the way: the `:call` thing is already in the wiki: https://github.com/pazz/alot/wiki/Tips,-Tricks-and-other-cool-Hacks#calling-arbitrary-python-code-on-startup

**Comment by deadc0de6** [comment]
Nice, thank you all for the tips, the `:call` thing is exactly what I needed.
