### ISSUE TITLE
interface is frozen when returning from external calls (editor, shellescape, ...)

### ISSUE THREAD

**Issue by deadc0de6** [pazz/alot#1191]
Software Versions
-----------------

Python version: 2.7

Notmuch version: 0.25.2

Alot version (either a number or sha for master): 0.6

It happens on the current stable (*v.0.6*) and the one from git (*v.0.7.0dev*)

Observed behavior
-----------------

Before anything, thanks a lot of alot, it's an awesome mua, love it!

This happened recently on both Arch linux and Debian stretch. When using alot, and calling external commands (through the `editor_cmd` config option or through `shellescape` for example), the interface is not responding anymore to any keystroke when coming back from the external call.

Here's my two *external* callers:

* `editor_cmd = 'vim -c "set textwidth=80" -c "set wrap" -c "set spell" -c "set nocp"'`
* `shellescape --refocus=true '<some-script>'; refresh`. 

Both of these were working fine.

Moreover, the entire interface is working perfectly as long as I don't call any of the two above.

Test
-------------------------

Here is the minimal setup I used to test it:

```
mkdir -p /tmp/mails ~/.config/alot
```

notmuch config (`~/.notmuch-config`)
```
[database]
path=/tmp/mails

[user]
name=test
primary_email=test@test.com

[new]
tags=unread;inbox;
ignore=

[search]
exclude_tags=deleted;spam;

[maildir]
synchronize_flags=true
```

alot config (`~/.config/alot/config`):
```
editor_cmd = 'vim -c "set textwidth=80" -c "set wrap" -c "set spell" -c "set nocp"'

[accounts]
    [[test]]
        realname  = test
        address   = test@test.com
        sent_box  = maildir:///tmp/mails/
        sent_tags = inbox,
        sendmail_command = echo "ok"
```

walkthrough:

* init notmuch: `notmuch new`
* start alot: `alot`
* type `m` to compose new email, fill fields and enter something
* exit editor
* everything is frozen (even `CTRL+c` doesn't work)

I'm not sure where to look or how to debug that, nothing is displayed in the logs. Any help is appreciated.

**Comment by pazz** [comment]
Hey! thanks for the detailed bugreport!
I cannot immediately reproduce this though. Here are some quick thoughts:
- the same editor_cmd works as expected in my setup.
- there should be no connection to notmuch's config.
- you do not have any hooks set? in particular 'touch_external_cmdlist'?
- in the debug log (alot -d debug -l logfile) do you see get the expected
  command details from this statement?
  https://github.com/pazz/alot/blob/master/alot/commands/globals.py#L212
- Do you get to the point where the logs say "refocussing"?
  https://github.com/pazz/alot/blob/master/alot/commands/globals.py#L265
  If not, you could try to sprinkle more debug statements in between those lines
  and see if you can pinpoint where things go wrong.
- did it ever work for you? if so, can you bisect the commit that broke it for
  you?

Thanks and best wishes,
P


Quoting deadc0de (2018-01-21 12:45:57)

**Comment by deadc0de6** [comment]
Thanks for the answer, here are a few points:
- I use some hooks but disabled those to isolate the issue (I actually tested it using the above *clean* setup)
- when using debug logs, here are the information I get when issuing a `shellescape` (cleaned for privacy)
```
DEBUG:ui:Got key ([','], [44])
DEBUG:ui:cmdline: 'shellescape --refocus=true '<some-script>'; refresh'
DEBUG:ui:search command string: "shellescape --refocus=true '<some-script>'"
DEBUG:__init__:mode:search got commandline "shellescape --refocus=true '<some-script>'"
DEBUG:__init__:ARGS: [u'shellescape', u'--refocus=true', u'<some-script>']
DEBUG:__init__:cmd parms {'spawn': None, 'shell': True, 'refocus': True, 'cmd': u'<some-script>', 'thread': None}
DEBUG:globals:{'spawn': None}
DEBUG:globals:cmdlist: [u'<some-script>']
INFO:globals:calling external command: [u'<some-script>']
INFO:globals:refocussing
DEBUG:ui:search command string: " refresh"
DEBUG:__init__:mode:search got commandline " refresh"
DEBUG:__init__:ARGS: [u'refresh']
DEBUG:__init__:cmd parms {}
DEBUG:manager:Worker process 20840 spawned
DEBUG:manager:Worker process 20840 exited successfully
...
DEBUG:walker:EMPTY PIPE
```
and here the logs from an editor session:
```
DEBUG:ui:Got key (['m'], [109])
DEBUG:ui:cmdline: 'compose'
DEBUG:ui:search command string: "compose"
DEBUG:__init__:mode:search got commandline "compose"
DEBUG:__init__:ARGS: [u'compose']
DEBUG:__init__:cmd parms {'spawn': None, 'sender': None, 'attach': None, 'cc': None, 'omit_signature': False, 'rest': [], 'bcc': None, 'to': None, 'template': None, 'subject': None}
DEBUG:envelope:TEMPLATE: None
DEBUG:ui:Got key (['enter'], [10])
DEBUG:globals:True
...
DEBUG:globals:SUBJECT: ""
DEBUG:globals:No encryption by default, encrypt_by_default=none
INFO:envelope:editable headers: set(['To', 'From', 'Subject'])
DEBUG:globals:using editor_cmd: vim -c "set textwidth=80" -c "set wrap" -c "set spell" -c "set nocp"
DEBUG:globals:{'spawn: ': False, 'in_thread': False}
DEBUG:globals:{'spawn': False}
DEBUG:globals:cmdlist: ['vim', '-c', 'set textwidth=80', '-c', 'set wrap', '-c', 'set spell', '-c', 'set nocp', '/tmp/alot.QlRvxX.eml']
INFO:globals:calling external command: ['vim', '-c', 'set textwidth=80', '-c', 'set wrap', '-c', 'set spell', '-c', 'set nocp', '/tmp/alot.QlRvxX.eml']
DEBUG:envelope:GoT: """
To: test.com
From: xxx
Subject: 


"""
```
There's two different behaviors (even though the result is the same). With `shellescape` I get a *refocussing*, the interface is frozen but I can exit it with `CTRL+c`. With the editor session, I don't get any *refocussing* in the log and am unable to exit with `CTRL+c` and need to kill the job/shell/window to exit. When hitting `CTRL+c` after the editor session, the logs show `INFO:ui:shut down cleanly` but the interface doesn't actually shut down.

- Yes it worked for me for the past 2 years and I was really happy with alot! It only started recently but I have been unable to identify a specific package/update that could have triggered that. 

It could also be linked to something outside of alot but was unable to identify what (tried with different distros, different hosts, different terminals, different shells (zsh+bash), different configs, disable any vim configs, ...). I used the setup I described in my first post above to test the issue since it is minimal.

Since you cannot reproduce it, I guess it is some configs/setup on my side. I'll try to start fresh with a clean slate to see if I'm able to identify where the issue is.

**Comment by lucc** [comment]
If you can trigger the bug from the command line with `alot compose` or `alot mailto:...` (without any interaction) you could try `git bisect` to find the offending commit. You can also try to use `timeout(1)` in your bisect command to `kill -9` the hanging alot automatically.

**Comment by tomjnixon** [comment]
Hi,

I found the cause of this issue in urwid, documented in https://github.com/urwid/urwid/issues/285

This was easily reproduced on arch, with python 2.7.14, with the latest urwid and alot, and a minimal config:

    [accounts]
        [[foo]]
            realname = foo
            address = foo@foo.foo

- Make sure a notmuch database exists.
- Run alot with `EDITOR=vim`
- Run `:compose`, press enter a few times to get into vim, run `:wq` to exit. alot should now be hung.

This can be worked around by running an old version of urwid (e.g. 1.3.1).

To fix this in alot, these lines could be changed to `ui.mainloop.stop()` and `ui.mainloop.stop()`:

https://github.com/pazz/alot/blob/0b03f06125db7fa507592143a0c1f6fec0d8b6a2/alot/commands/globals.py#L287-L289

Note that these functions only exist since urwid 1.3.0, so the required version should be changed if this is implemented.

This works for me, but i'm a bit new to alot/urwid so it's not clear to me if this might breaks something else; I could send a PR if this seems sensible, but it's a 3 line change...

Thanks!

**Comment by pazz** [comment]
Thanks for this Thomas, great find.
Would you mind sending us a pull request for the suggested changes (ideally with a test that explicates the bug)?
Cheers,
P
