### ISSUE TITLE
alot from Macports is not working

### ISSUE THREAD

**Issue by m2habert** [pazz/alot#1203]
Installed alot using macports; it's not working (see "tracebac errors" below)

I don't know Python, so have no idea where to start. Usually my noob problems with "traceback"s are solved by paying attention to the python27 vs python34 selection/care.

Can't find no complains like mine: ¿Am I the only one using Macports for this?

Thanks!

Software Versions
-----------------

Python version: 
                (python27 selected by python_select)
  python2_select @0.0_2 (active)
  python3_select @0.0_1 (active)
  python27 @2.7.14_0 (active)
  python34 @3.4.7_1
  python34 @3.4.8_0 (active)
  python_select @0.3_7 (active)

Notmuch version:
              notmuch @0.26_0 (active)

Alot version (either a number or sha for master):
              alot @0.3.4_0 (active)

              py27-urwid @1.3.1_0 (active)
              libmagic @5.32_0 (active)

Observed behavior
-----------------
```
 Traceback (most recent call last):
  File "/opt/local/bin/alot", line 19, in <module>
    from alot.init import main
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/alot/init.py", line 11, in <module>
    from alot.db.manager import DBManager
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/alot/db/__init__.py", line 5, in <module>
    from thread import Thread
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/alot/db/thread.py", line 6, in <module>
    from message import Message
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/alot/db/message.py", line 8, in <module>
    from notmuch import NullPointerError
ImportError: No module named notmuch

```

**Comment by dcbaker** [comment]
I don't know of anyone else using macports, but the version in there is quite old. You will need python 2.7, which it looks like you have, but for some reason it looks like you don't have the notmuch python bindings, or they're not in a place that python is finding.

**Comment by m2habert** [comment]
I gave up. Installed Homebrew + alot, and it seems to be working.

Only caveat it's that it installed a second notmuch under /usr/local/bin/, which I guess is no big deal. 

I just wonder if there's any risk of a port from Homebrew activating both other ports equally installed in both /opt/local/bin/ (MacPorts ) and /usr/local/bin/ (Brew) that I'm unaware of; thus bringing new problems...

**Comment by pazz** [comment]
Closing this. We are not "officially supporting" homebrew/macports scripts anyway. In case you take up macports again, feel free to discuss this on #alot at Freenode though, maybe you'll find some knowledgeable macports user there..
