### ISSUE TITLE
0.7 not on PyPI

### ISSUE THREAD

**Issue by ilovezfs** [pazz/alot#1208]
I notice 0.7 is here https://github.com/pazz/alot/releases but not here https://pypi.python.org/pypi/alot

**Comment by lucc** [comment]
See #1121.

CC @dcbaker , @geier

**Comment by dcbaker** [comment]
I've uploaded 0.7 and signed the release with my gpg key, finger print "71C4B75620BC75708B4BDB254C95FAAB3EB073EC"

**Comment by pazz** [comment]
cheers
