### ISSUE TITLE
PyPI package has been accidentally deleted

### ISSUE THREAD

**Issue by geier** [pazz/alot#1213]
The original creator of the alot package on PyPI has accidentally deleted the package completely on PyPI yesterday and send me a notice afterwards. So we need to recreate it, which is easy. The problem is, that [PyPI does not allow for a filename to be reused, even once a project has been deleted and recreated.](https://upload.pypi.org/help/#file-name-reuse).

Solutions could be to a) upload all packages as new versions, e.g., 0.7_1, or b) send the people who run PyPI a message and see if that policy is negotiable.

What are your opinions?

cc @dcbaker

**Comment by dcbaker** [comment]
So we can recrete the alot project, but not alot 0.7?

**Comment by geier** [comment]
I believe that is correct.

**Comment by dcbaker** [comment]
Well, lets start with recreating the project. I guess we can call the artifact 0.7.0.

**Comment by dcbaker** [comment]
I've uploaded a new alot project and a 0.7.0 artifact, signed with the same key. @geier, is your pypi name the same as your github name? I'll add you as a co-owner again.

**Comment by geier** [comment]
@dcbaker yes, I'm also `geier` on PyPI. Thank you for adding me.

**Comment by dcbaker** [comment]
Added! Thanks for bringing this up.
