### ISSUE TITLE
Refresh gpg recipients after adding more recipients in evelope buffer

### ISSUE THREAD

**Issue by varac** [pazz/alot#1227]
Software Versions
-----------------

Python 2.7.14
notmuch 0.26
alot 0.7.0dev

Observed behavior
-----------------

I compose a mail to alice, exit the edit buffer. The envelope buffer indicates the mail will get encrypted to alice (and myself). Then I decide to CC: bob, but the mail will still get only encrypted to alice and me.
I manually need to toggleencrypt twice until the mail gets encrypted to bob.

This is annoying because I already sent out mails other people couldn't decrypt from this scenario.

Expected behavior
-----------------

Whenever recipients change in envelope mode, alot should try to encrypt to new recipients without manual intervention.

**Comment by dcbaker** [comment]
I've reproduced this.
