### ISSUE TITLE
Warn if mail is not encrypted to all recipients

### ISSUE THREAD

**Issue by varac** [pazz/alot#1232]
After moving to alot (yay!) I accidentially sent several mails which were not encrypted to all recipients. This is annoying, and alot should warn the user before sending the mail.
Thunderbird/Enigmail does this job quite well.

**Comment by pazz** [comment]
This sounds like a job for a small `pre_envelope_send` hook similar to the [one reminding of you of forgotten attachments](https://github.com/pazz/alot/wiki/Contrib-Hooks#check-for-missing-attachment-before-sending).

**Comment by dcbaker** [comment]
I think this is worth having in core alot, if you send an encrypted message but do not have keys for all recipients you're sending them garbage.

**Comment by drebs** [comment]
Here's a first draft of the functionality:

```python
from twisted.internet import defer

#
# Warn if message is not encrypted to all recipients
#
@defer.inlineCallbacks
def pre_envelope_send(ui, dbm, cmd):
    e = ui.current_buffer.envelope
    if not e.encrypt:
        # do nothing, message is not encrypted (why not!?)
        return

    # get all recipient addresses
    recipients = set(map(lambda s: parseaddr(s)[1], e.headers.get('To', [])))
    recipients.union(map(lambda s: parseaddr(s)[1], e.headers.get('Cc', [])))
    recipients.union(map(lambda s: parseaddr(s)[1], e.headers.get('Bcc', [])))
    if not recipients:
        return

    # get all email addresses of encryption keys
    keys = set()
    for key in e.encrypt_keys.values():
        for uid in key.uids:
            keys.add(uid.email)

    # fail if both sets are not equal
    if not recipients.issubset(keys):
        msg = 'Message is not encrypted to all recipients. Send anyway?'
        if not (yield ui.choice(msg, select='yes')) == 'yes':
            raise Exception()
```

Some things that come to mind:

* Is that the correct way to handle addresses in the `Bcc` header? Would the encryption keys to Bcc'ed addresses also appear in the envelope's `encrypt_keys` attribute?
* Should we handle sets comparison differently? I always encrypt to my own key, even though I am not a recipient of the message. Are there other use cases?
* Should we allow for refreshing the set of keys? If so, how?

Once we get to a nice state I can move the code to the contrib hooks page.

**Comment by varac** [comment]
@drebs Do you like to submit a pull req based on your patch ?

**Comment by pazz** [comment]
@drebs: I think it'd be best to add your code to envelope.SendCommand, shortly befor the mail is constructed in https://github.com/pazz/alot/blob/master/alot/commands/envelope.py#L209 .

**Comment by varac** [comment]
@drebs Ping

**Comment by varac** [comment]
\o/ Thanks !!!
