### ISSUE TITLE
Saving any part of a multipart email

### ISSUE THREAD

**Issue by josch** [pazz/alot#1242]
Is there a way to save any part of a mutlipart message to the disk?

For example I have an email with a text and a html part and I want to print the html part as it is rendered in a browser. For this purpose I'd have to extract the html part somehow and extracting the html from the Email source is quite tedious.

Or: an email contains a part that is not marked as an attachment but I still want to look at it. For that purpose I'd need to save it to the disk first.

Is there any way to do this already?

My workflow right now, is to lookup the Message-ID, find the file with notmuch-search and then extract the right multipart part using Python.

But surely, there is an easier way because alot already parsed the message?

**Comment by pazz** [comment]
Unfortunately, there is no easier way at the moment, I think.
Alot does not give you access to individual mime parts, other than
through they email API.

The way alot (still) parses mails is simply using a (depth fist) walk
through its mime-tree, and concatenating (text translations) of
everything it considers displayable (leafs which are not attachments).

#528 #862 #894

**Comment by josch** [comment]
Thanks for the pointers!

Yes, I guess these issues would have to be fixed before a feature could be added that allows saving each of these parts to disk.
