### ISSUE TITLE
make docs fails

### ISSUE THREAD

**Issue by pazz** [pazz/alot#1249]
I cannot locally make the sphinx docs any more using just "make html" in the docs dir.
Probably, this is python3 related.

 
Software Versions
-----------------
```
python --version
Python 2.7.15
python3 --version
Python 3.6.5
sphinx-build --version
sphinx-build 1.7.4
```

Alot version: master

Observed behavior
-----------------

```
~/alot/docs: make html
python source/generate_configs.py
Traceback (most recent call last):
  File "source/generate_configs.py", line 13, in <module>
    from alot.commands import COMMANDS
  File "source/../../alot/commands/__init__.py", line 12, in <module>
    from ..settings.const import settings
  File "source/../../alot/settings/const.py", line 6, in <module>
    from .manager import SettingsManager
  File "source/../../alot/settings/manager.py", line 19, in <module>
    from ..utils import configobj as checks
  File "source/../../alot/utils/configobj.py", line 8, in <module>
    from urllib.parse import urlparse
ImportError: No module named parse
make: *** [Makefile:50: source/configuration/accounts_table] Error 1
```

**Comment by lucc** [comment]
Did you try `make -C docs PYTHON=/usr/bin/python3`? I am on arch linux and `python` is `python3` and it works for me.

**Comment by pazz** [comment]
I didn't try that, thanks. The result is still not as expected.
There are several encoding issues like the one below. The full log is [here](https://gist.github.com/pazz/2f2ffc55f09d61a18d7d6084b4f8c07a).

```                                                                    
WARNING: autodoc: failed to import module u'alot.commands.globals'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/ext/autodoc/importer.py", line 140, in import_module
    __import__(modname)
  File "/home/pazz/projects/alot/alot/commands/globals.py", line 23, in <module>
    from .utils import set_encrypt
  File "/home/pazz/projects/alot/alot/commands/utils.py", line 14, in <module>
    from .. import crypto
  File "/home/pazz/projects/alot/alot/crypto.py", line 2
SyntaxError: Non-ASCII character '\xc2' in file /home/pazz/projects/alot/alot/crypto.py on line 2, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```

**Comment by lucc** [comment]
And what is the python version that sphinx uses? `head $(which sphinx-build)`? The makefile also has a variable for sphinx.

**Comment by pazz** [comment]
Quoting Lucas Hoffmann (2018-06-19 14:50:13)
> And what is the python version that sphinx uses? head $(which sphinx-build)?
> The makefile also has a variable for sphinx.

```
head $(which sphinx-build)                            
#!/usr/bin/python

ll /usr/bin/python                                                            
lrwxrwxrwx 1 root root 9 Apr 16 15:31 /usr/bin/python -> python2.7
```

This must be it then. Apparently python2.7 is still the default
interpreter on debian testing.

**Comment by pazz** [comment]
@mjg: I'm on debian testing and have both `python3-sphinx` and `python-sphinx` installed and do not have this binary in the system path..

**Comment by lucc** [comment]
On Arch Linux I have `python`=`python3` but only `sphinx-build` (for py3) and `sphinx-build2`. No `sphinx-build3`. On Cent OS I also have `python3` and I don't know about sphinx.

I think the python executable `python3` is common but it seems that for sphinx there is no such thing. The make file variables can be used by the user in any case so the solution we pick doesn't really matter.

**Comment by pazz** [comment]
It seems that the presence of `python-sphinx` meant that the python2 version had preferece over the python 3 version, at least for me on debian testing. I removed the former and now the tests run as expected, using the v3 interpreter.
