### ISSUE TITLE
No requirements.txt?

### ISSUE THREAD

**Issue by vinisalazar** [pazz/alot#1272]
I am having dependency problems to install this. Have you thought about including a req.txt file? It would be greatly appreciated. I saw the install notes but having this file would be much more practical.

Thank you for your attention.
V

**Comment by lucc** [comment]
Did you check the `install_require` section in `setup.py`?  How would the req.txt be different from that?

**Comment by pazz** [comment]
I think this file is used by pip to automate some resolution of dependencies.
They thing is that notmuch is not on pip, and most of us already have a packaging system.
