### ISSUE TITLE
inline (apparmor) signing/encryption

### ISSUE THREAD

**Issue by pazz** [pazz/alot#128]
damn UoE mta wraps the complete mail, breaking pgpmime mails for thunderbird and co

**Comment by binaryplease** [comment]
any progress on this?

**Comment by pazz** [comment]
check out https://github.com/pazz/alot/wiki/Tips,-Tricks-and-other-cool-Hacks#read-a-pgp-incline-encrypted-email on how to read inline pgp text.
Producing inline signed or encrypted message is not planned for now.
