### ISSUE TITLE
sendmail return values ignored

### ISSUE THREAD

**Issue by pazz** [pazz/alot#1303]
I've recently updated my account list and while debugging some strange behaviour I noticed that calls to my MTA (msmtp) are unusually snappy.
It turns out that its error code and return values are completely ignored.
The offending commit seems to be 3c0097c3.

**To Reproduce**
Steps to reproduce the behaviour:
1. change your sendmail command to `sendmail_command = fail`
2. compose + send a mail
3. notice that `fail` is a MTA now :)

**Error Log**
nothing special, it looks as if the command succeed:
```
DEBUG:helper:CMD = [b'fail']
INFO:account:sent mail successfully
```

**Comment by lucc** [comment]
Checking my journalctl logs (which record the activity of msmtp for me) I can see that I did not retry to send an email if it failed during the last month but did retry (similar log entry shortly after a failure) some time earlier. So I conclude that this also happened here.
