### ISSUE TITLE
Sorting by tag

### ISSUE THREAD

**Issue by ajmedford** [pazz/alot#1307]
I would like to be able to view all emails, but prioritize based on tag. This would provide similar functionality to the "priority inbox" feature Gmail had for a while. For example, place all "unread" emails above others.

This could be achieved by allowing tag arguments to the `sort` command:

`sort tag:unread`

would prioritize mails with the unread tag. Ideally this could support multiple arguments and logical operators as well. For example, something like:

`sort (tag:unread and tag:important) tag:work`

would place unread+important tags first, followed by work tags, and then by all others.

As far as I can tell this feature is not currently available. Any suggestions on if it makes sense, and how to add it (and how difficult it would be)?

**Comment by pazz** [comment]
I think this would be a nasty hack at best:
Alot does not sort threads but rather requests the result-set from notmuch in a particular order.
But notmuch (see man notmuch-search) only supports oldest/newest first.

**Comment by ajmedford** [comment]
I see - thanks for a fast response! Another possible way to achieve it would be to use "previews" in the bufferlist view.  For example, by including the first N lines of a buffer underneath the buffer name you could see a number of emails from specific searches, which could be set up with `initial_command`. The number of lines to view as a preview could also be set in the config file. You would still need to go into the buffer to access the emails, but at least you could see everything at once. Maybe this is an even harder route though...

**Comment by NoctuaNivalis** [comment]
Maybe it's easier to just allow multiple queries in a search? You show the results of these queries in order. A simple `search tag:unread + tag:inbox AND NOT tag:unread` would mimick the gmail feature you describe.

**Comment by ajmedford** [comment]
This is a brilliant solution! Seems to do exactly what I want, and no need for backend development. The next question is whether I can color-code by tag combinations to make the categories more visually distinct. I'll do some reading but any quick hints are appreciated. I can open another issue if needed.

**Comment by lucc** [comment]
You can assign replacement strings and colors to any single tag. No combinations can be assigned a special color.

**Comment by ajmedford** [comment]
Ok, I finally got around to looking into this but can't seem to figure it out (even for a single tag). Any hints on where in the docs to look? Figured I'd ask here since you all have been so responsive.

**Comment by lucc** [comment]
@ajmedford I have this in my alot config file: 
```
[tags]
  [[flagged]]
    translated = ⚑
    normal = '','','light red','','light red',''
    focus = '','','light red','','light red',''
  [[unread]]
    translated = ✉
    normal = '','','dark red','','dark red',''
    focus = '','','dark red','','dark red',''
  [[todo]]
    normal = '','','dark red','','dark red',''
    focus = '','','dark red','','dark red',''
  [[bug-example]]
    normal = '','','dark magenta','','dark magenta',''
    focus = '','','dark magenta','','dark magenta',''
  [[encrypted]]
    translated = #⚷🔒🔑🔐
    normal = '','', 'dark green', '', 'dark green', ''
  [[signed]]
    translated = ✔#✓🗸🗹🖒
    normal = '','', 'dark green', '', 'dark green', ''
  [[inbox]]
    translated = #↘#➘➥⇘⇲⤷➷⬊⬂📥📩
    normal = '','', 'dark cyan', '', 'dark cyan', ''
  [[sent]]
    translated = ↗#⇗⬈⬀➹➶⤴↗➚➦📤
    normal = '','', 'dark blue', '', 'dark blue', ''
  [[replied]]
    translated = ↻#⏎
    normal = '','', 'dark blue', '', 'dark blue', ''
  [[draft]]
    translated = ✍
    normal = '','', 'dark cyan', '', 'dark cyan', ''
  [[music]]
    translated = ♫#♪
    normal = '','', 'dark magenta', '', 'dark magenta', ''
  [[lists/.*]]
    translation = 'lists/(.*)','l/\1'
  [[lists]]
    translated = ''
```
The relevant docs are here: https://alot.readthedocs.io/en/latest/configuration/theming.html#tagstring-formatting

But the chapter before that proofs me wrong. It seems you can actually define highlighting for tag combinations: https://alot.readthedocs.io/en/latest/configuration/theming.html#dynamic-theming-of-thread-lines-based-on-query-matching
