### ISSUE TITLE
Search <query> in a thread(s)

### ISSUE THREAD

**Issue by psic** [pazz/alot#1311]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when opening a mail or group of threads, and I want to search a word or group of word in this bunch of text. I will be very usefull when I receive log mail report from my server for instance.

**Describe the solution you'd like**
Have a commande like :searchText <text> and all the matched query string will be highlighted. Can also navigate throught different occurence of those matched strings.

**Describe alternatives you've considered**
I try something like :pipeto grep <queryString> , but I can not achieve to make it work

**Comment by pazz** [comment]
> Describe the solution you'd like
> Have a commande like :searchText and all the matched query string will be
> highlighted. Can also navigate throught different occurence of those matched
> strings.


Yes, such a feature would indeed be nice. It would require some non-trivial restructuring of the urwid-widgets we use.
PRs with concrete proposals would be much appreciated!

> Describe alternatives you've considered
> I try something like :pipeto grep , but I can not achieve to make it work


As a temporary workaround, you could `pipeto less` or whatever pager you prefer, and use its search functionality.

**Comment by psic** [comment]
I do not know what is a PR.
pipeto (which I pronouce in my head as a unique italian word "pipeto" which mean, I guess, little pipe) do the trick. Very Nice.
When I use such nice piece of software as alot is, I like to have a brief list with what the software does and what it does not do. For each "missing" feature, a simple document workaround it's great to have in doc such as this "less trick"

**Comment by pazz** [comment]
Quoting psic (2018-09-11 22:05:19)
> I do not know what is a PR.

stands for "pull request", githubs feature to propose code changes.


> pipeto (which I pronouce in my head as a unique italian word "pipeto" which
> mean, I guess, little pipe) do the trick. Very Nice.
> When I use such nice piece of software as alot is, I like to have a brief list
> with what the software does and what it does not do. For each "missing"
> feature, a simple document workaround it's great to have in doc such as this
> "less trick"

Sounds like a good idea. Feel free to start such a list as a new document in our wiki (here on github).

**Comment by psic** [comment]
Ok. I will.

**Comment by pazz** [comment]
cool :)
