### ISSUE TITLE
Move screenshots/ to root?

### ISSUE THREAD

**Issue by polyzen** [pazz/alot#1333]
**Is your feature request related to a problem? Please describe.**
Make it easier for people to find them and know they exist.

The main reason I wanted this was for easy theme installation:
`install -Dm644 -t "$pkgdir"/usr/share/alot/themes extra/themes/*`

However, for that, I will add the themes to `MANIFEST.in` along with what's necessary to build the manual. Edit: And switch to sourcing from PyPI.

Edit 2: This would also make it simpler for `MANIFEST.in` theme inclusion.

**Comment by lucc** [comment]
I agree that they are hard to discover but I would not move them to the root of the repo.  We could instead use them in the readme or the wiki. Or if we do not want to use them we could also remove them. They are not directly related to the code but rather belong on a website (that we don't have).

**Comment by pazz** [comment]
I like the idea of moving them (or new ones) to the wiki and not having them part of the distributed tarball / git checkout.

**Comment by lucc** [comment]
I added the [gallery](https://github.com/pazz/alot/wiki/Gallery). Now we can move the screenshots from the main repo to the wiki repo as soon as we want to. Currently the images are linked to the main repo.

**Comment by polyzen** [comment]
When trying to push via HTTPS:
> remote: Permission to pazz/alot.wiki.git denied to polyzen.
> fatal: unable to access 'https://github.com/pazz/alot.wiki.git/': The requested URL returned error: 403

via SSH:
> ERROR: Permission to pazz/alot.wiki.git denied to polyzen.
> fatal: Could not read from remote repository.

https://ptpb.pw/oczb.patch

**Comment by pazz** [comment]
@lucc: very nice, thanks! Could you send a PR removing the screenshots from the repo?
@polyzen: Sorry, I don't get what you're trying to do. If you cannot write to the wiki then this is a github issue?

**Comment by polyzen** [comment]
@pazz, I'm working on PR's to remove the screenshots and update `MANIFEST.in`

I was just saying that I tried to push the wiki changes, but that's apparently only you or other members could do. You can apply the patch with `git am`.

**Comment by lucc** [comment]
I copied them to the wiki, we can remove the screenshots from the main repo.
