### ISSUE TITLE
UnicodeEncodeError in formataddr

### ISSUE THREAD

**Issue by pazz** [pazz/alot#1347]
This should not happen when replying to a msg from someone with a funny unicode name:
```
DEBUG:thread:Replying to own message, set recipients to: ['"Michaël C <mc@X>, DC <d@Y>"']
ERROR:ui:Traceback (most recent call last):
  File "/home/pazz/projects/alot/alot/ui.py", line 709, in apply_command
    await cmd.apply(self)
  File "/home/pazz/projects/alot/alot/commands/thread.py", line 239, in apply
    to = ', '.join(self.ensure_unique_address(recipients))
  File "/home/pazz/projects/alot/alot/commands/thread.py", line 321, in ensure_unique_address
    urecipients = [formataddr((n, str(a))) for a, n in res.items()]
  File "/home/pazz/projects/alot/alot/commands/thread.py", line 321, in <listcomp>
    urecipients = [formataddr((n, str(a))) for a, n in res.items()]
  File "/usr/lib/python3.6/email/utils.py", line 91, in formataddr
    address.encode('ascii')
UnicodeEncodeError: 'ascii' codec can't encode character '\xeb' in position 5: ordinal not in range(128)
```

**Software Versions**
- Python version: 3.6.7
- Alot version: master (b6606a5402aa2c50d202e7feb27e74d2c7202681)

**Comment by pazz** [comment]
This happens only when group replying to self-sent messages.
the problem is that the in line [213](https://github.com/pazz/alot/blob/master/alot/commands/thread.py#L213),
`recipients` contains strings that have not yet been encoded into ascii.
In case it is a normal reply, those have been encoded in the preceeding line.

**Comment by pazz** [comment]
It turns out that the mail has a bad To header:

```
From: "Michaël C <mc@X>, DC <d@Y>"
```

This means that `email.Message.get_all('To', [])` returns `'"Michaël C <m@c>"'`.
Now,

```
ReplyCommand.clear_my_address([],['"Michaël C <m@c>"'])
```
fails
but 
```
ReplyCommand.clear_my_address([],['Michaël C <m@c>'])
Out[32]: ['=?utf-8?q?Micha=C3=ABl_C?= <m@c>']
```

**Comment by varac** [comment]
I also get this when trying to tab-complete a recipient from an address book lookup that returns Special characters like german Umlauts.

**Comment by pazz** [comment]
i think this might not be related. can you provide a trace?

**Comment by pazz** [comment]
On debian, `python` also still links to python v2.7, so I make the docs (which need v3, as you point out) by setting the `PYTHON` var like this:

```
make PYTHON="python3" -C docs cleanall html
```

**Comment by pazz** [comment]
My problem is that the message contains

```
To: '=?utf-8?q?Micha=C3=ABl=2CC?= <mc@X>, DC <d@Y>"
```

`email.utils.parseaddr(msg.get_all('To'))`
turns this into
`email_address = '=?utf-8?q?Micha=C3=ABl=2CC?= <mc@X>, DC <d@Y>''`, and `realname = ''`.
When I then use `email.utils.formataddr` to join it back into one string, then it fails because [it assumes that the address part is by convention and RFC!](https://docs.python.org/3/library/email.utils.html#email.utils.formataddr) ASCII encoded.

Perhaps we should keep things as is, or raise some more meaningful error that explains that the message is broken!
