### ISSUE TITLE
editnew - local variable 'fromaddress' referenced before assignment (probably duplicate of #1351?)

### ISSUE THREAD

**Issue by stefanfriedel** [pazz/alot#1353]
#### Describe the bug
Editing a draft mail with "editnew" is not possible:

`local variable 'fromaddress' referenced before assignment`

#### Software Versions
Python 3.7.1
Notmuch 0.28
alot 0.8
Arch Linux

#### Error Log

    ERROR:ui:Traceback (most recent call last):
        File "/usr/lib/python3.7/site-packages/alot/ui.py", line 709, in apply_command
            await cmd.apply(self)  
        File "/usr/lib/python3.7/site-packages/alot/commands/globals.py", line 863, in apply
            account = settings.account_matching_address(fromaddress)
        UnboundLocalError: local variable 'fromaddress' referenced before assignment

#### Steps to reproduce:
- Start writing a new mail
- Save in Draft folder with "P"
- Try to edit again with "n" / editnew
 
(probably duplicate of #1351?)

**Comment by lucc** [comment]
Did you try to reproduce the problem with current master?

**Comment by stefanfriedel** [comment]
I've to admit: no...I'll test it asap

**Comment by stefanfriedel** [comment]
ok, sorry, works in master - thank you!
