### ISSUE TITLE
test_env_set fails if only python3 is installed

### ISSUE THREAD

**Issue by jljusten** [pazz/alot#1354]
https://github.com/pazz/alot/blob/1e346cac12fdce13a6fe1aec790ebb5ee1c5651e/tests/helper_test.py#L422

This is present in 0.8, and master.

Changing 'python' to 'python3' fixed the issue, but if python3 is now required for alot, then the referenced code block could remove the future import as well.

**Comment by lucc** [comment]
What operating system are you on? Why is there no symlink `python -> python3` on your system?

If we change it to `python3` there might be someone with a system where only `python` is installed and it will not work again.  This is a catch 22.

**Comment by lucc** [comment]
I think the only way to make it really fool proof would be to `import sys` and use `sys.executable`.

**Comment by jljusten** [comment]
@lucc: I'm on debian, and building the alot package in a minimal build environment. Now I only depend on python3, so python2 is not installed. Therefore the 'python' executable does not exist.

I think the only Linux distro that did something funny was arch-linux. They made the python executable be python3, which prompted the python project to document this.

https://www.python.org/dev/peps/pep-0394/

Based on that PEP, for python3, the python3 executable should always be available as python3.

I looked at the arch python package that installs python3. It makes both python and python3 work as python3, so I think this change should be safe for arch. See "Package Contents" under:

https://www.archlinux.org/packages/extra/x86_64/python/

> I think the only way to make it really fool proof would be to `import sys` and use `sys.executable`.

I guess that could work too. But, since alot no longer supports python2, I don't think that is strictly required.

**Comment by lucc** [comment]
I was not aware of pep 394 and am indeed using arch linux so I was under the impression that distros just choose some version to link to plain python.

In the light of pep 394 I approve of this and #1355.
