### ISSUE TITLE
~ Expansion Request/Implementation

### ISSUE THREAD

**Issue by bmccary** [pazz/alot#1361]
I would like the following `~` expansion to work:

```
$ cat .config/alot/config

[accounts]
    [[foo]]
        realname = bar
        address = bar@foo.com
        sendmail_command = msmtp --account=foo -t
        sent_box = maildir://~/.mail/sent
        draft_box = maildir://~/.mail/drafts
```

The concerned `alot` code is here https://github.com/pazz/alot/blob/6bb18fa97c78b3cb1fcb60ce5d850602b55e358f/alot/utils/configobj.py#L100-L101

It does not work because the `~` is parsed by `urlparse` into the `netloc` property of `mburl`, but it is not used by `alot`.

```python
mburl.path == '/.mail/sent'
mburl.netloc == '~'
```

As a result, `alot` generates the error

```
$ alot
[Errno 2] No such file or directory: '/.mail/sent'
```

since, of course, there is not a `.mail` directory in `/`. A possible implementation might be:

```python
    elif mburl.scheme == 'maildir':
        box = mailbox.Maildir(mburl.netloc + mburl.path)
```

This might work and also be backwards-compatible because a fully-qualified path like `'/spam/eggs/.mail/sent'` parses like:

```python
mburl.path == '/spam/eggs/.mail/sent'
mburl.netloc == ''
```

and the `mailbox` implementation in CPython already does `~` expansion https://github.com/python/cpython/blob/67ba547cf001d6b975cf6900aaf2bd5508dc6a87/Lib/mailbox.py#L38

According to [the URI RFC](https://tools.ietf.org/html/rfc3986#section-3), the element that `urlparse` is calling `netloc` is called the *authority* and it something like `example.com:1234`. I leave it to the august `alot` developers to determine whether or not `~` is an authority.

**Comment by polyzen** [comment]
This can be closed.
