### ISSUE TITLE
Warning about msg not being encrypted to all recipients should be case-insensitive

### ISSUE THREAD

**Issue by varac** [pazz/alot#1363]
Warn if mail is not encrypted to all recipients #1232 works well, except the situation where i.e. one recipient has one character in upper case, whereas the gpg has all characters in lower case.

**Software Versions**
- Python version: 3.6.7
- Alot version: master of today

**To Reproduce**
Steps to reproduce the behaviour:
1. compose a mail to `someOne@example.org`
2. encrypt it, using key from `someone@example.org`
3. try to send it
4. Alot will complain

**Error Log**

Nothing relevant in the logs:

```
DEBUG:ui:cmdline: 'send'
DEBUG:ui:envelope command string: "send"
DEBUG:__init__:mode:envelope got commandline "send"
DEBUG:__init__:ARGS: ['send']
DEBUG:__init__:cmd parms {}
```

The UI shows: `Message is not encrypted to all recipients. This means that not everyone will be able to decode and read this message. Do you want to send anyway? (y):yes (n):no`.

**Comment by varac** [comment]
@drebs ^

**Comment by lucc** [comment]
This looks like another symptom of the fact that email address local parts should only be interpreted by the receiving system (the one identified by the domain name of the email address). We had this problem before with local parts that where interpreted case insensitive by the provider but we had trouble matching them against our account addresses in alot.

**Comment by drebs** [comment]
> This looks like another symptom of the fact that email address local parts should only be interpreted by the receiving system (the one identified by the domain name of the email address). We had this problem before with local parts that where interpreted case insensitive by the provider but we had trouble matching them against our account addresses in alot.

Hi, @lucc. I don't understand if your comment is just a remark or if it leads to or suggests some way of handling the present situation.

**Comment by lucc** [comment]
My comment above was a reminder that any solution to the problem must take care to solve essentially the same problems as #1108. Only now for any potential recipient instead of the users own addresses. Essentially it boils down to the question "In which situations do we allow ourselves to deviate from the standard and dare to make assumptions about the local part of an email address?"

**Comment by pazz** [comment]
(see #1364 )

**Comment by varac** [comment]
Thx !
