### ISSUE TITLE
Confirmation option for command pipelines

### ISSUE THREAD

**Issue by MacGyverNL** [pazz/alot#1368]
I'd like to bind sequences of --all tagging operations in search buffers (so that I can easily, say, tag all e-mails from a search query as deleted, and untag the inbox and unread tags). This is currently a bit risky because even with a leader like 'g delete' I might accidentally hit that at some point.

I was thinking of the possibility of having a "confirm" command as the first command in a sequence which prompts the user similar to bug_on_exit. If answered "n", it aborts the entire sequence.

Alternatives could be to add a --confirm or --prompt option to tagging operations but then the sequence would just continue when answered "n" on the first.

I'm also considering just binding 'g delete y' to have effectively the same sequence of key presses, but that doesn't actually *prompt* me for what I'm about to do and seems to have some trouble with the timing of the third keypress.

**Comment by pazz** [comment]
Quoting Pol Van Aubel (2019-01-09 15:10:38)
> I'd like to bind sequences of --all tagging operations in search buffers (so
> that I can easily, say, tag all e-mails from a search query as deleted, and
> untag the inbox and unread tags). This is currently a bit risky because even
> with a leader like 'g delete' I might accidentally hit that at some point.
> 
> I was thinking of the possibility of having a "confirm" command as the first
> command in a sequence which prompts the user similar to bug_on_exit. If
> answered "n", it aborts the entire sequence.

I think such a command may be useful.
In fact, upon "n" such a command may raise some exception. This aborts the whole following sequence of commands.
You could define a special "abort sequence" exception and catch that specifically (somewhere in the ui.apply logic)
to avoid this exception appearing as error in the logs.
