### ISSUE TITLE
send mail with msmtp dit not work after 0.8

### ISSUE THREAD

**Issue by GuillaumeSeren** [pazz/alot#1372]
Hello thank you for alot it is the best MUA !

Before you submit a bug report, please make sure that the issue still exists on the master branch!
I can reproduce it on 0.8 and master (fff58de316f31267923cad28670ce6c033e93c83).

I use alot since a long time, and I am working to package the 0.8 for gentoo linux,
the problem is the following, when I send a mail it hang's up stay for ever on 'sending..'.

**Software Versions**
- Python version:
python3.6
- Notmuch version: [if relevant]
notmuch-0.27
- Alot version:
alot-0.8 - fff58de3

**To Reproduce**
* Compose a mail
* Send !

**Error Log**
Here the sending part of the log
```
DEBUG:ui:Got key (['y'], [121])
DEBUG:ui:cmdline: 'send'
DEBUG:ui:envelope command string: "send"
DEBUG:__init__:mode:envelope got commandline "send"
DEBUG:__init__:ARGS: ['send']
DEBUG:__init__:cmd parms {}
DEBUG:envelope:FROM: "Mr Guillaume Seren <guillaumeseren@gmail.com>"
DEBUG:envelope:ACCOUNT: "guillaumeseren@gmail.com"
(...)
DEBUG:helper:CMD = [b'msmtp', b'-t', b'--read-envelope-from']
DEBUG:ui:Got key (['q'], [113])
DEBUG:ui:cmdline: 'exit'
DEBUG:ui:envelope command string: "exit"
```
And msmtp is responding as usual
```
Feb 01 12:39:25 host=smtp.gmail.com tls=on auth=on user=guillaumeseren from=guillaumeseren@gmail.com recipients=masked@gmail.com mailsize=423 smtpstatus=250 smtpmsg='250 2.0.0 OK 1549021165 s132sm1443836wmf.28 - gsmtp' exitcode=EX_OK
```
When doing the same with the 0.7 alot get the response from msmtp, and close the small 'sending..' bar,
as alot is now python-3 there is a lot of changes but I can reproduce on master as well.

Guillaume

**Comment by GuillaumeSeren** [comment]
Hey @pazz thank you for the quick feedback.

> 1. have you tried hardcoding the full path to the msmtp binary?

No I kept the same setup / config that worked for the 0.7, will try that.

> 2. I'm not using the msmtp version from my packager either because something similar hung 

I use the msmtp without problem for a long time, so I will try the last version, but I am sure because it works fine with alot-0.7 so it would nice to see what's changed inside alot that cause the issue.
I will check last version.

:tea:

**Comment by GuillaumeSeren** [comment]
I tested upgrading msmtp to the last version 1.8.2, same issue,
works fine with 0.7 stuck on 'sending..' on master.
So I think the issue is in alot so I will dig into the changes !

**Comment by teto** [comment]
I use msmtp without problems in alot 0.8. But I use msmtp-queue instead so that may not be helpful advice.

**Comment by GuillaumeSeren** [comment]
@teto Hey thank you I will check that.

**Comment by pazz** [comment]
https://github.com/pazz/alot/pull/1306
could be related?

**Comment by GuillaumeSeren** [comment]
Hey @pazz sorry to be late,
I have tested again this morning against several versions here my feedback,
(I use MSMTP 1.6.6-r1, and this setup work fine with alot-0.7-r1, builded with python3):

- master (d0297605) → send mail with MSMTP work
- 0.8.1 (4c3fe821) → send mail with MSMTP work
- (fff58de3) → send mail with MSMTP work
- 0.8 (a5d956af) → send mail with MSMTP work

So I think this issue comes from my setup, sorry for the trouble I will prepare a new version for gentoo.

Thank you again for this great MUA :heart:

**Comment by pazz** [comment]
super, I'm glad it's fixed without my input :) cheers!
