### ISSUE TITLE
Wrong tab completion for addressbook entries with non-ascii characters.

### ISSUE THREAD

**Issue by josch** [pazz/alot#1378]
With alot 0.8 from Debian unstable I can observe the following bug:

In abook I have the address of a person called "Andreas Nüchter" stored. When I compose an email and type "Andr" when prompted for the `To:` field, then it gets completed to:

    To:=?utf-8?q?Andreas_N=C3=BCchter?= <xxx@yyy>,

This is a regression. This bug did not happen with alot 0.7.

**Comment by pazz** [comment]
Right, it looks as if this one gets encoded too early. Very strange. Thanks for reporting.

**Comment by sgelb** [comment]
The same kind of error occurs when autocompleting accounts with umlauts in their realname in `compose`. The fix is also the same, replace the remaining `email.utils.formataddr` with `formataddr` in https://github.com/pazz/alot/blob/f9689575e771aaa2e6cd4da13b71b88cf8e9e246/alot/completion.py#L251
