### ISSUE TITLE
Filtering messages in thread view

### ISSUE THREAD

**Issue by agrudzinsky** [pazz/alot#1385]
It can be difficult to navigate long threads.  I have threads with many participants, and there are many automated "out of office" replies.  I do auto-label them as "ooo" and "spam", but they still show up in thread view.  

It would be great to hit ``/`` and add some filter terms like ``not tag:ooo`` or ``tag:flagged`` or ``from:the_boss`` or ``tag:attachment`` and see only those messages in the selected thread.

Is there already a solution for this use case?

**Comment by lucc** [comment]
You can fold messages based on search terms in thread view: `fold not tag:ooo` should work.

**Comment by agrudzinsky** [comment]
Quoting Lucas Hoffmann (2019-03-09 22:59:11)
> You can fold messages based on search terms in thread `view: fold not tag:ooo
> should work.

When there are several pages of just email titles, folding
doesn't help much. For instance, my company has a department in
China. There is a thread on some topic that includes 20+ people.
The thread is already overloaded with one-liner emails like "OK",
"Thanks", and "Noted" that carry 0 information. But then you
happen to send an email at the beginning of the Chinese New Year
and you get 10 "Out of the office" autoreplies.

Unfolding emails doesn't make them visually stand out because of
the nasty Outlook habit to append the whole email thread to each
email.  And folding emails does not help to unclutter the screen
if I want to see just the 2 flagged emails in the thread out of
40.

-- 
Arkady

**Comment by pazz** [comment]
Yes, that'd be great.
The problem is that currently, the only "collection of messages" buffer alot has, is the thread view, and threads come directly from the notmuch database, i.e., cannot be filtered.
In future, It'd be great to have a buffer for individual messages and another one for general collections (which may include the current thread buffer), but as it stands there is no easy way to filter out some messages from threads I'm afraid.

**Comment by agrudzinsky** [comment]
Thanks.

I suppose, I can run `move next tag:flagged` command to find
what I want and run a script to delete junk once in a while.

-- 
Arkady
