### ISSUE TITLE
Option to show threads folded by default

### ISSUE THREAD

**Issue by Tyilo** [pazz/alot#1387]
**Is your feature request related to a problem? Please describe.**
When entering a (long) thread, the first thing I do is always to fold all the messages.

**Describe the solution you'd like**
I would like an option to always showing messages folded by default, when entering a thread.

**Describe alternatives you've considered**
Maybe this could be achived by a hook or some other setting, but I'm not really sure.

**Additional context**

**Comment by pazz** [comment]
This is very easy to do by re-binding the (search mode) enter key to "select; fold *"..
Best,
P

Quoting Asger Hautop Drewsen (2019-03-26 22:40:34)
