### ISSUE TITLE
pre_envelope_send hook failing

### ISSUE THREAD

**Issue by aalexei** [pazz/alot#1389]
Setting up a hook following the examples in the wiki:

```
def pre_envelope_send(ui, dbm, cmd):
   e = ui.current_buffer.envelope
   e.add("X-Clacks-Overhead", "GNU Terry Pratchett")
```

Gives the error: `Object NoneType can't be used in 'await' expression` on trying to send a message. Are the examples out of date? (alot version 0.8.1)

**Comment by pazz** [comment]
Yes, this contrib code is outdated; it should be 

  async def pre_envelope_send(ui, dbm, _):
    ...

Can you fix the wiki accordingly if it works for you?
Cheers,
P
    
Quoting Alexei (2019-03-30 07:30:45)

**Comment by lucc** [comment]
I fixed the remaining examples of `pre_envelope_send` in the contrib hooks page. The keyword was already present in one case.
