### ISSUE TITLE
Composing emails asynchronously

### ISSUE THREAD

**Issue by lenormf** [pazz/alot#1392]
**Is your feature request related to a problem? Please describe.**

I have `terminal_cmd` set in my configuration, and the process blocks the `alot` UI.

**Describe the solution you'd like**

Be able to navigate the mailbox in the UI while another window contains the email I'm writing.

**Comment by ninewise** [comment]
The `editor_in_thread` configuration option does not work?

**Comment by lenormf** [comment]
It does, I must have missed it when I wrote my configuration. Thanks!
