### ISSUE TITLE
travis build fails to install notmuch

### ISSUE THREAD

**Issue by pazz** [pazz/alot#1395]
The current master tests fail because the buildbot seems to have problems installing notmuch + bindings...
@lucc could you look into this? IIRC, you've written the travis config have you?
Cheers,
P

**Comment by pazz** [comment]
The problem seems to be that notmuch new requires a higher libgmime version than 2.6. I have tried updating the package name as suggested by notmuchs install script bu I think the respective package is not available on the distribution travis uses. ubuntu (?)

**Comment by pazz** [comment]
It looks like [the latest ubuntu distribution that travis supports is xenial](https://docs.travis-ci.com/user/reference/overview/#linux) but libgmime 3 is only packaged from the next higher release:
https://launchpad.net/ubuntu/+source/gmime

**Comment by pazz** [comment]
https://docs.travis-ci.com/user/reference/overview/#linux
It looks like we're out of luck.
I see two options:
1. also build libgmime manually (on travis)
2. install (an outdated) notmuch stable with lower dependencies..
I'll leave this to you @lucc because you seem to have more experience with travis.

**Comment by lucc** [comment]
I would prefer a stable notmuch from the repos but that is not possible as ubuntu provides 0.21 and we need >=0.27.  Someone (maybe dcbaker?) said that we could also make two builds one for stable notmuch and one for notmuch@master. I will think about it.

**Comment by lucc** [comment]
@dkg I found [the PPA](https://launchpad.net/~notmuch/+archive/ubuntu/notmuch) you started together with David beginning this month. Is that a good candidate for alot? currently we are running xenial on travis and build notmuch ourselves.  Or is there another PPA which provides notmuch directly?

**Comment by pazz** [comment]
I spend two hours on travis just now and cannot get it to run!
https://travis-ci.org/pazz/alot/builds
branch travistest

If someone can repair this: great! otherwise I now tend to just let it go, live without travis and CI in general. This is not what I've signed up for.

**Comment by dkg** [comment]
Sorry for the lag in response here.

@lucc yes, that is the entire point of that PPA.  I am maintaining it for notmuch upstream, which is also using travis with xenial.

I'm a little annoyed with travis for encouraging people to stick with ubuntu xenial (and a little annoyed with ubuntu for not addressing bugs in gpg in their LTS particularly well, but that's another story).  But this PPA is intended specifically to provide "harm reduction" for people building/testing notmuch in that environment.  Please feel free to use it for alot as well!

**Comment by pazz** [comment]
Thanks for this dkg!

Say do you happen to know how to get a working and up to date python3-gpg ?

I can install python3-gpg from your ppa just fine apparently, but since travis uses pip for managing the dependencies for python projects, it will try to download and install some gpgme-based package called python-gpg from pypi instead of using the locally installed version.
https://travis-ci.org/pazz/alot/jobs/537466763#L903

We had an ugly manual fix:
https://github.com/pazz/alot/blob/master/.travis.yml#L74
but this fails to compile recently because of something related to swig.

**Comment by pazz** [comment]
It seems to work now.
I have removed the manual build of gpgme and its deps and instead use `libgpgme-dev` from apt now to build `python-gpg` using pip from pypi. Let's hope this lasts for a while...

**Comment by dkg** [comment]
@pazz -- the gpgme source that ships in the PPA should itself already build both python-gpg and python3-gpg.  you shouldn't need to use pip or pypi at all:

https://launchpad.net/~notmuch/+archive/ubuntu/notmuch/+build/16737088

**Comment by pazz** [comment]
@lucc: the problem is that travis will ignore all apt-installed python packages and set up a new pip env in a virtualenv; so will download everything from scratch (pypi) anyways.
The libs still need to be present so that the pypi-sourced "gpg" package can be compiled.

**Comment by dkg** [comment]
wow, even more reasons for me to dislike travis!  thanks for the explanation, @pazz

**Comment by lucc** [comment]
If we want to use the system packages for python stuff we are restricted to only py2.7 and py3.4: https://docs.travis-ci.com/user/languages/python#travis-ci-uses-isolated-virtualenvs

**Comment by dkg** [comment]
ah, ok.  i think the one that ships in the PPA builds only for python 3.5.  i can try to make it build for 3.4 as well if that would make things easier/simpler for you.

**Comment by dkg** [comment]
hm, it seems like the ubuntu PPA build daemons ought to have built it for 3.4, actually.  i'll have to dig around a bit more.  if anyone sees the issue, i'm happy to get suggested patches for it.  It's on the ubuntu/xenial-backports branch on https://salsa.debian.org/debian/gpgme

**Comment by dkg** [comment]
[the build log](https://launchpadlibrarian.net/422353370/buildlog_ubuntu-xenial-amd64.gpgme1.0_1.13.0-1~ppa2_BUILDING.txt.gz) says:

```
checking for a Python interpreter with version >= 3.4... none
checking for a Python interpreter with version >= 3.5... python3.5
[…]
checking for a Python interpreter with version >= 3.6... none
checking for a Python interpreter with version >= 3.7... none
checking for a Python interpreter with version >= 3.8... none
checking for a Python interpreter with version >= all... none
```

and this is despite having libpython3-all-dev installed.  But [Ubuntu doesn't ship libpython3.4-dev in xenial](https://packages.ubuntu.com/search?suite=default&section=all&arch=any&keywords=libpython3.4-dev&searchon=names) (though it apparently is available in trusty).

@lucc, are you sure that the link you're referring to is up-to-date?  it looks like it is documenting trusty instead of xenial.  is alot using trusty or xenial on travis?

**Comment by lucc** [comment]
@dkg I was a bit sloppy on the summary (and when reading). The link I gave above says 
> you’ll only be able to use the default Python versions that are available in Ubuntu (e.g. for Trusty, this means 2.7.6 and 3.4.3)

What I take from this is that with the system packages we are restricted to *only* the system versions of python. For trusty these are 2.7 and 3.4. For Xenial the docs are not so clear on that matter:
https://docs.travis-ci.com/user/reference/xenial/#python-support

**Comment by dkg** [comment]
@lucc -- the system versions of python3 for xenial are pretty clearly only 2.7 and 3.5 (see for example `rmadison -u ubuntu python3.{4,5,6}`, which shows only 3.5 on xenial).

So, the python3-gpg package built in the PPA should work directly with the system python, bypassing the need for it in pip.
