### ISSUE TITLE
UTF8 recipients with a comma get split into incorrect parts when replying

### ISSUE THREAD

**Issue by mjg** [pazz/alot#1402]
**Describe the bug**
If I receive an e-mail from a sender such as `"Ö, Ä" <x@y.z>` and reply then the recipients will be a list with one recipient 'Ö' and another recipient `Ä <x@y.z>`. In other words: the UTF8-encoded comma in the name is mistaken for a header value list separator.

**Software Versions**
- Python version: python3-3.7.3-3.fc30.x86_64
- Alot version: f81fea2f (current master)

**Error Log**
I have amended `db/utils.py:decode_header()` with debug lines for the passed in header (before `re.sub`) and decoded header right before the `return`.

 When I display the message in alot, the debug reads:
```
DEBUG:utils:passedin header: |"Ö, Ä" <x@y.z>|
DEBUG:utils:unquoted header: |"Ö, Ä" <x@y.z>|
DEBUG:utils:decoded header:  |"Ö, Ä" <x@y.z>|
```
Everything fine so far.

When I reply the following relevant lines (others omitted) are shown before the editor opens:
```
DEBUG:thread:candidate addresses: [('Ö, Ä', 'x@y.z')]
DEBUG:thread:reply to: =?utf-8?q?=C3=96=2C_=C3=84?= <x@y.z>
DEBUG:utils:passedin header: |=?utf-8?q?=C3=96=2C_=C3=84?= <x@y.z>|
DEBUG:utils:unquoted header: |=?utf-8?q?=C3=96=2C_=C3=84?= <x@y.z>|
DEBUG:utils:decoded header:  |Ö, Ä <x@y.z>|
```
So, this is the step where the back and forth of encoding and decoding seems to lose the quotes around the problematic address. But I don't see which step actually introduces the quotes - they are not part of the UTF8-string.

In any case, the `', '.join()` in line 227 of `alot/commands/thread.py´ apparantly needs to be somewhat more careful about assembling that comma separated list.

**Comment by pazz** [comment]
[This](https://github.com/pazz/alot/issues/1347#issuecomment-445254273) is the same issue isn't it?

**Comment by mjg** [comment]
> [This](https://github.com/pazz/alot/issues/1347#issuecomment-445254273) is the same issue isn't it?

No, I'm not getting any UnicodeError. The message is displayed without problems. The to: header for the reply is filled in without any error messages - but it is filled in wrongly, the one realname+address is truned into a comma separated list because the `,` in the UTF8-encoded realname part is not escaped when it gets decoded.

**Comment by pazz** [comment]
OHHH!
This is a notmuch bug!
look: when you point to this message and (using pyshell) do 

```
>>> m=ui.current_buffer.get_selected_message()
>>> m.get_author()
('', 'Ö')
```
This method actually just calls `email.utils.parseaddr` on the supposed `From` header stored in the notmuch db (not the file!).

```
>>> m._from
'Ö, Ä <x@y.z>'
```

Indeed, `notmuch show` prints this (see especially the last line):

``` 
message{ id:test-alotrn-quotes@example.ac.uk depth:0 match:1 excluded:0 filename:/home/pazz/mail/alottest/new/realnames:2,S

header{
Ö, Ä <x@y.z> (2018-10-18) (inbox)
Subject: test realname quotes #1402
From: Ö, Ä <x@y.z>
```
whereas 

```
 notmuch show --format=raw id:test-alotrn-quotes@example.ac.uk 
Subject: test realname quotes #1402
Date: Thu, 18 Oct 2018 01:11:11 +0100
From: =?utf-8?q?=C3=96=2C_=C3=84?= <x@y.z>
```

This should be discussed upstream.

**Comment by pazz** [comment]
This explains your bug:
The [join you mentioned](https://github.com/pazz/alot/blob/master/alot/commands/thread.py#L227) is actually safe, because it operates on *encoded* name/address pairs:
When group-replying, the value of `to` is fine:

```
reply to: =?utf-8?q?=C3=96=2C_=C3=84?= <x@y.z>, me@example.ac.uk
```

Thr problem is that envelopes operate on unicode string values for "headers", which is why [a few lines later](https://github.com/pazz/alot/blob/master/alot/commands/thread.py#L247), we set the `To` header value for the new envelope as the decoded `to` value computed above.

This will then result in a (envelope) header value
`To: Ö, Ä <x@y.z>, me@example.ac.uk`.

Now, if you try to send this, naturally, it looks like the first character is an address part without real name part, and now [we've come full cirlce](https://github.com/pazz/alot/issues/1347#issuecomment-495946252) as for such addresses, email.util.formataddr dies non non-ascii characters.

**Comment by mjg** [comment]
Yes, this is what's happening (and which I've apparantly failed to explain). What  I don't know is when alot should operate with encoded and when with decoded values.

The problem occurs during the decoding step which fails to quote the comma - isn't this done by alot?

In my case, I didn't notice any formataddr errors, but sending failed for the wrong "address" (half of a real name).

**Comment by mjg** [comment]
As for notmuch: Displaying without quoting is fine, alot does the same, it's safe to do. That is, unless `notmuch show` output is supposed to be used verbatim as a header value.

**Comment by pazz** [comment]
you are right. Notmuch is fine.

Here is the magic: https://github.com/pazz/alot/blob/master/alot/widgets/thread.py#L288

Aparently, the value of `mail.get_all(key)` is already decoded and with quotes!

```
>>> e=m.get_email()
>>> e.get_all("From")
['"Ö, Ä" <x@y.z>']

```

**Comment by pazz** [comment]
f401701fe4bd3ce4267551eaedd443bed7c11fd6 should fix your problem.
However, before i push this, we need tests and there seem to be some related and similar problems.

1. the inline quatation string when replying to this msg is currently `Quoting Ö (timestam)` and not `Quoting "Ö, Ä"` as expected.
2. I have not checked Cc's
3. adding a quoted header 
`Cc: "Ö, Ä" <a@b.c>`
in the editor is not correctly interpreted by the envelope header.

**Comment by mjg** [comment]
> [f401701](https://github.com/pazz/alot/commit/f401701fe4bd3ce4267551eaedd443bed7c11fd6) should fix your problem.

Thanks, this fixes my case indeed.

Time permitting, I'll see if I can help with the following:

> However, before i push this, we need tests and there seem to be some related and similar problems.
> 
> 1. the inline quatation string when replying to this msg is currently `Quoting Ö (timestam)` and not `Quoting "Ö, Ä"` as expected.
> 2. I have not checked Cc's
> 3. adding a quoted header
>    `Cc: "Ö, Ä" <a@b.c>`
>    in the editor is not correctly interpreted by the envelope header.

**Comment by pazz** [comment]
3936dec6dfa650bd082edcbed51fabc8691c6e65 should fix 2;
I was wrong about point 3, it works as expected now for me (no changes).
We still need tests.

**Comment by pazz** [comment]
fixed in master
