### ISSUE TITLE
Question: notmuch v0.26 or v0.27 needed?

### ISSUE THREAD

**Issue by rasmuse** [pazz/alot#1403]
Hi all,

I hope I am opening an issue in the right way. Not sure if this is a bug report or something else.

I am trying to install alot v0.8.1 from source on Ubuntu 18.04. The installation stops because the setup.py requires `notmuch>=0.27`. However, looking at the `git blame` I am confused because the requirement for notmuch 0.27 is added in the latest commit touching `setup.py`:

https://github.com/pazz/alot/blame/0.8.1/setup.py#L48

I don't fully understand the dates listed here on GitHub, but in the list of commits for `setup.py` it says "Commits on Oct 8, 2018" ... and then "meskio committed on Nov 15, 2017", but November 2017 is even before notmuch v0.27 was released. The list of commits:

https://github.com/pazz/alot/commits/0.8.1/setup.py

The latest explicit mention of notmuch version bump I can find is to 0.26 in commit 31b61bc5868dfab22121a8f7c4a20f3b0778db10

Can I safely change to `notmuch>=0.26` in `setup.py` and expect everything to work?

Thank you for your help!

**Comment by rasmuse** [comment]
OK, sorry for being too quick to open an issue.

I have tried and it clearly needs notmuch bindings `>=0.27'. When doing a search with 0.26 bindings it crashes because `notmuch.Message.get_properties` is missing; see e.g., https://github.com/notmuch/notmuch/commit/5e05f00fe59d2f2d7dceadefaab30bcc12b0e8df

If anything needs doing it is possibly updating the docs which still point to notmuch >= 0.13:

https://alot.readthedocs.io/en/latest/installation.html

**Comment by pazz** [comment]
Thanks for bringing this to my attention. I've updated the docs to bring them in sync with `setup.py`.
