### ISSUE TITLE
documentation has broken URL to urwid Display Atributes

### ISSUE THREAD

**Issue by jonassmedegaard** [pazz/alot#1411]
Documentation section on colour attributes at https://alot.readthedocs.io/en/latest/configuration/theming.html#colour-attributes links to  urwid Attribute strings but that's a broken link.

Seems the correct URL is http://urwid.org/manual/displayattributes.html

**Comment by pazz** [comment]
thanks. Could you send a PR to correct this?

**Comment by jonassmedegaard** [comment]
Quoting Patrick Totzke (2019-06-17 21:01:26)
> thanks. Could you send a PR to correct this?

Sorry, but due to licensing concerns I won't contribute any code to 
Github, only conversational bits.

 - Jonas

-- 
 * Jonas Smedegaard - idealist & Internet-arkitekt
 * Tlf.: +45 40843136  Website: http://dr.jones.dk/

 [x] quote me freely  [ ] ask before reusing  [ ] keep private
