### ISSUE TITLE
Currently failing tests on travis and master

### ISSUE THREAD

**Issue by lucc** [pazz/alot#1414]
I just restarted the tests on travis for PR #1413 and noticed that they now fail (they were green before but for some reason github did not pick up the test completion from travis for several days).

And for me locally the test on master also fail.

@pazz, @dcbaker do they fail for you too?

**Comment by sgelb** [comment]
The gpg keys for testing in `tests/statuc/gpg-keys` are all expired. `pub.gpg` on July 11th, the others on July 12th.

**Comment by lucc** [comment]
Should we just use never expiring keys for the test suite? Is there any argument against it?
@teythoon maybe?

**Comment by pazz** [comment]
This sounds reasonable to me.
