### ISSUE TITLE
how to search email's text?

### ISSUE THREAD

**Issue by Al-Caveman** [pazz/alot#1419]
say i view an email.  how to search for some text within that email?  

i already found the email.  i just want to read faster.  so if i search for some text, i can know where to jump to read.

is this possibler?

**Comment by lucc** [comment]
This is currently not possible.  @pazz did explain it somewhere before but I don't remember where. I think the problem was that we hand the text to urwid for displaying and we (alot) do not knoww the position of parts of the text in the urwid buffer.

**Comment by lucc** [comment]
Mentioned in #830 more explanation (but only loosely related to this): #3 #639

**Comment by lucc** [comment]
Actually #830 is a duplicate of this.

**Comment by Al-Caveman** [comment]
this is horrible.  i'm leaving `alot`.  it's also funny, how can you even name it `alot` if it can't even do such a basic thing?

**Comment by lucc** [comment]
You are welcome to send a PR.
