### ISSUE TITLE
Send mail and initial_command broken with alot-0.8.1 and <twisted-18.4.0

### ISSUE THREAD

**Issue by GuillaumeSeren** [pazz/alot#1420]
Hello !

**Describe the bug**
Last week I had to change my laptop ssd and reinstall partly my system,
then I stumble upon #1372 and #1373 again, I was sure this comes from one of the dependencies not right, because I thought it was working fine on my last ssd.
I am sure the problem stopped occuring because I upgrade one of the dependencies in my userspace, I only have search which one.

There might be other problems with this issue, but I noticied those:
* The initial_command did not work (event the default one).
* The send mail was stuck on Sending, but I can see in the msmtp log that it was gone well.

**Software Versions**
- Python version: 3.6.5
- Notmuch version: 0.28.4
- Alot version: alot-0.8.1 (reproducible on master)
- msmtp 1.8.5

So I try different version of twisted and there is no more issue on the 18.4.0, so I will bump the ebuild in gentoo to this version at least, but I wanted to share the issue with you all.

And so maybe bumping the setup.py install_requires array to this version would prevent the issue for other ?

**Comment by pazz** [comment]
I guess there is no harm in bumping the dependency here.. thanks for reporting this!
