### ISSUE TITLE
*empty* screen when editor returns an error

### ISSUE THREAD

**Issue by teto** [pazz/alot#1427]
Before you submit a bug report, please make sure that the issue still exists on the master branch!

**Describe the bug**
Not really a bug but kinda weird behavior, I was trying to run `alot compose` commands when I exited neovim with `:cq` (to indicate an error).
The following alot screen kinda becomes blank. Maybe it could display some warning ("editor exited with non 0 code")

**Software Versions**
- Alot version: master

**To Reproduce**
Steps to reproduce the behaviour:
1. COmpose a mail
2.  exit the editor so that it returns a non-0 exit code

**Comment by pazz** [comment]
Confirmed.
For a bit of background: What happens here is that alot starts without any buffers and the `global` command `compose` is called. If the editor exits with return code \neq 0, this [triggers an error notification](https://github.com/pazz/alot/blob/master/alot/commands/globals.py#L307) in the alot ui, and this is it: you are left with the empty (buffer less) interface. The reason that the error notification does not show any text and is just an empty red bar is that that your editor did not write anything to `stderr`. The notification as is will just display anything your editor process prints to stderr. Perhaps we could add another line of text [here](https://github.com/pazz/alot/blob/master/alot/commands/globals.py#L307) such as "the process X has returned with error code Y: STDERR-TXT" ?

**Comment by teto** [comment]
Displaying the exit code seems useful.

NB: I am just curious about the `<15mins` label. is it equivalent to fast/easy to fix ?

**Comment by pazz** [comment]
Quoting Matthieu Coudron (2019-08-19 10:54:05)
> Displaying the exit code seems useful.
> 
> NB: I am just curious about the <15mins label. is it equivalent to fast/easy to
> fix ?

yes, that's what I meant with it. That is, assuming we'd just adjust the call to ui.notify()

**Comment by teto** [comment]
A fix was merged thanks.
