### ISSUE TITLE
\t (tab) character rendered as '?' in envelope view

### ISSUE THREAD

**Issue by pacien** [pazz/alot#1439]
**Describe the bug**
Tab characters (`\t`) are rendered as `?` in the envelope view.
This is particularly annoying when sending patches.

Identical to https://github.com/pazz/alot/issues/74 closed many years ago.
Looks like a regression.

**Software Versions**
- Python version: 3.7.4
- Notmuch version: [if relevant]
- Alot version: 0.8

**To Reproduce**
Steps to reproduce the behaviour:
1. compose a new message, and add some tab-indented code snippet in the body
2. exit the editor and return to the envelope buffer
3. notice that `\t` are replaced with `?`

**Error Log**
N.A.

**Comment by lucc** [comment]
The same happens in source view (`:togglesource`).

**Comment by pazz** [comment]
the PR is untested but I believe it should fix the issue. Please test.
