### ISSUE TITLE
segfault caused by notmuch lib?

### ISSUE THREAD

**Issue by pazz** [pazz/alot#1442]
I recently observe that alot simply dies on me, without any notice ordebug log,
when I try to archive a thread from search mode.
I suspect that there was some change in the underlying notmuch bindings as any problem within alot should have been reflected in the logs.

**Software Versions**
- Python version: Python 3.7.4+
- Notmuch version: 
```
>>> notmuch.__VERSION__
'0.28.4'
>>> notmuch.version.SOVERSION
'5'
```
- Alot version: d68617a69c9d8601b919c2db145799d1f5d7edd0

**To Reproduce**
Steps to reproduce the behaviour:
1. open search buffer
2. archive some threads (not more details available atm I'm afraid)
3. you're back at an (uncleared) terminal

**log**
```
DEBUG:ui:Got key (['a'], [97])
DEBUG:ui:cmdline: 'toggletags inbox'
DEBUG:ui:search command string: "toggletags inbox"
DEBUG:__init__:mode:search got commandline "toggletags inbox"
DEBUG:__init__:ARGS: ['toggletags', 'inbox']
DEBUG:__init__:cmd parms {'flush': 'True', 'tags': 'inbox', 'action': 'toggle'}
DEBUG:search:all? False
DEBUG:search:q: (tag:inbox AND NOT tag:killed AND NOT path:uoe/indirect/**) AND thread:000000000001a928
DEBUG:manager:write-out item: ('untag', <function Thread.remove_tags.<locals>.myafterwards at 0x7f4a06082560>, 'thread:000000000001a928', ['inbox'])
DEBUG:manager:cmd created
DEBUG:manager:got write lock
DEBUG:manager:got atomic
DEBUG:manager:ended atomic
DEBUG:manager:ended atomic
DEBUG:manager:closed db
DEBUG:manager:<function Thread.remove_tags.<locals>.myafterwards at 0x7f4a06082560>
DEBUG:manager:called callback
DEBUG:manager:flush finished
DEBUG:manager:write-out item: ('tag', <function Thread.add_tags.<locals>.myafterwards at 0x7f4a06082170>, 'thread:000000000001a928', [])
DEBUG:manager:cmd created
DEBUG:manager:got write lock
DEBUG:manager:got atomic
DEBUG:manager:ended atomic
DEBUG:manager:ended atomic
DEBUG:manager:closed db
DEBUG:manager:<function Thread.add_tags.<locals>.myafterwards at 0x7f4a06082170>
DEBUG:search:remove thread from result list: thread:000000000001a928: subject line
```

**Comment by lucc** [comment]
I am on Arch Linux with 

notmuch: 0.29.1
alot: 0.8.1-78-gd68617a6

and I noticed nothing.

**Comment by pazz** [comment]
I still get this occasionally, but less often now that I've updated notmuch+bindings from git. I will close the issue for now because I have no clue how to reproduce (or even debug) this.

**Comment by mkaito** [comment]
I've been running into this exact problem, core dump when archiving threads from search view. Did you ever find out anything else?

arch linux, notmuch 0.30, alot 0.9.1.
