### ISSUE TITLE
Expand environment variable in terminal_cmd ?

### ISSUE THREAD

**Issue by psic** [pazz/alot#1450]
**Describe the bug**
I want to use st terminal and tabbed (new tab of terminal when writing mail with nano)
my terminal_cmd look like ='st -w $XEMBED -e'
it seems that the $XEMBED variable is not replace by its value.
So alot open a new st terminal with nano, which is fine,  without expand this $XEMBED variable (see it using ps).
With this $XEMBED value, my st terminal will stick in tabbed

Thanks.

**Software Versions**
- Python version: 3
- Notmuch version: [if relevant]
- Alot version: 0.8

**Comment by pazz** [comment]
I agree that it could be useful to expand environmental variables in external commands spawned from within alot. The requested behaviour is a potential security issue of course and at the very least should be user configurable.
I suspect it will be easy to do (check out the internals of `ExternalCommand`, there should be a boolean parameter `shell` or similar when finally calling the command iirc.

**Comment by psic** [comment]
My bad, it's workiing. My $XEMBED variable is replaced by its value. It was more a tabbed or st issue, but more my fault (problem between chair and keyboard!)
