### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by zenhack** [pazz/alot#1452]
There are some bugs in 0.8.1 that are affecting me that seem to be fixed in master. I've switched over to running master for the moment, but perhaps it's time to tag a new release? The last one was in February.

**Comment by lucc** [comment]
According to [git tag-stats](https://github.com/lucc/shell/blob/master/git/git-tag-stats) we have accumulated some commits:

```
97e147cc...0.2:      885 commits,  55 files changed,  7609 insertions(+),   511 deletions(-)
    0.2...0.3:      643 commits,  86 files changed,  6983 insertions(+),  3059 deletions(-)
    0.3...0.3.1:    108 commits,  41 files changed,   948 insertions(+),   279 deletions(-)
  0.3.1...0.3.2:    164 commits,  75 files changed,  2525 insertions(+),  1313 deletions(-)
  0.3.2...0.3.3:    119 commits,  80 files changed,  3314 insertions(+),  2945 deletions(-)
  0.3.3...0.3.4:    142 commits,  37 files changed,  1223 insertions(+),   359 deletions(-)
  0.3.4...0.3.5:    221 commits,  69 files changed,  4123 insertions(+),   783 deletions(-)
  0.3.5...0.3.6:     77 commits,  32 files changed,   680 insertions(+),   263 deletions(-)
  0.3.6...0.3.7:     65 commits,  52 files changed,   523 insertions(+),  2397 deletions(-)
  0.3.7...0.4:       75 commits,  24 files changed,   397 insertions(+),   148 deletions(-)
    0.4...0.5:      228 commits,  87 files changed,  2613 insertions(+),  1419 deletions(-)
    0.5...0.5.1:     10 commits,   6 files changed,    24 insertions(+),    17 deletions(-)
  0.5.1...0.6:      231 commits,  91 files changed,  4004 insertions(+),   823 deletions(-)
    0.6...0.7:      154 commits,  62 files changed,  1966 insertions(+),   490 deletions(-)
    0.7...0.7rc1:    19 commits,   0       0      0 
 0.7rc1...0.8:      338 commits, 137 files changed,  4129 insertions(+),  3230 deletions(-)
    0.8...0.8.1:     14 commits,  34 files changed,   111 insertions(+),    32 deletions(-)
  0.8.1...v0.8:      14 commits,   0       0      0 
   v0.8...HEAD:     102 commits, 103 files changed,  1921 insertions(+),  1840 deletions(-)
```

and `git log --oneline 0.8.1..` also lists some bugfixes. I did not find any new features in there, *but I did not check thorougly!* Maybe we can make the bugfix release 0.8.2.

Site note @pazz & @dcbaker why do we have a tag `v0.8`? All other tags don't have the `v`. And we also have `0.8`.

**Comment by pazz** [comment]
@lucc: I don't remember my own rationale for the "v0.8" tag but it was something about github labels vs git tags. It should probably be renamed for consistancy.

I am open to tagging a release soon but there are a small number of feature PRs that seem ready-ish and I usually tend to wait until I have enough time during the xmas period :)
Perhaps we should get going. I'll click around and update the next milestone.

**Comment by pazz** [comment]
voila! :)
