### ISSUE TITLE
Can't attach a file if filename contains a semicolon

### ISSUE THREAD

**Issue by mmartin** [pazz/alot#1454]
**Describe the bug**
Can't add an attachment if the filename contains semicolon.

**Software Versions**
- Python version: 3.6.9
- Alot version: 0.8.1

**To Reproduce**
Steps to reproduce the behaviour:
1. compose new e-mail
2. try :attach /path/to/file;name
3. error: unknown command: name
4. try :attach '/path/to/file;name'
5. error:  No closing quotation
6. try :attach "/path/to/file;name"
7. error: No closing quotation

**Comment by pazz** [comment]
Right. That sucks. I believe that [this](https://github.com/pazz/alot/blob/master/alot/helper.py#L26) is the problem.

As a hotfix, try using wildcards: `:attach /path/to/file*name`..

**Comment by mmartin** [comment]
Yes, that was the problem. I wrote a custom parser. It's not pretty or efficient, but works good enough for me.

But I found an another problem – tab-completion does not work – `:attach '/<Tab>` returns nothing.

```python
def split_commandline(s):
    """
    splits semi-colon separated commandlines
    """
    commands = []
    buffer = ''
    state = 0 # 0 - default; 1 - escape; 2 - inside single qute; 3 - inside double quote
    prev_state = 0 # for handling escaped symbols

    for c in s:
        if state == 0:
            if c == ';':
                commands.append(buffer.strip())
                buffer = ''
                continue
            elif c == '\\':
                prev_state = state
                state = 1
            elif c == '\'':
                state = 2
            elif c == '"':
                state = 3
            buffer += c

        elif state == 1:
            state = prev_state
            buffer += c

        elif state == 2:
            if c == '\'':
                state = 0
            elif c == '\\':
                prev_state = state
                state = 1
            buffer += c

        elif state == 3:
            if c == '"':
                state = 0
            elif c == '\\':
                prev_state = state
                state = 1
            buffer += c

    if buffer:
        commands.append(buffer.strip())

    return commands
```
