### ISSUE TITLE
Some valid PGP-signed emails fail to validate: "Bad signature"

### ISSUE THREAD

**Issue by pacien** [pazz/alot#1459]
**Describe the bug**

Signed MIME emails sent by some other MUAs such as ProtonMail or K9-Mail (Android) do not validate in alot despite being valid in other MUAs like Evolution.

**Software Versions**
- Python version: 3.7
- Notmuch version: [if relevant]
- Alot version: master / f1cecca

**To Reproduce**
Steps to reproduce the behaviour:
1. import the attached .eml in the mailidr and refresh the notmuch index
2. import the corresponding public key in the gpg keyring with the right trust level
3. open the message in alot, notice that the validation fails: `PGP-Signature Invalid: ...: Bad signature for key(s)`

Example of valid .eml which fails to validate, with the public key file:
https://gist.github.com/pacien/422dd56c5c46967e642177bfbe6390af#file-1575332405-m647013610p6859q2rd52e5c50-eml

This .eml is shown as valid in Evolution.

**Error Log**
/

**Comment by ninewise** [comment]
I've seen this before, and I think it was caused by the wrapping of the content - but I haven't been able to pinpoint the issue, yet.

**Comment by pacien** [comment]
It looks like some additional blank lines are being added/removed between multipart boundaries after going through Python's MIME parsing and re-serialisation:

__Original .eml:__
```
Content-Type: multipart/mixed;boundary=---------------------a5cfd59260dd8280de7cb6716a3ae396

-----------------------a5cfd59260dd8280de7cb6716a3ae396
Content-Type: multipart/alternative;boundary=---------------------7b9e008e3e6e7b73e5019c70f73200c1

-----------------------7b9e008e3e6e7b73e5019c70f73200c1
Content-Transfer-Encoding: quoted-printable
Content-Type: text/plain;charset=utf-8

This is a test message that is signed with PGP/MIME.
-----------------------7b9e008e3e6e7b73e5019c70f73200c1
Content-Type: multipart/related;boundary=---------------------b08bd1e2a694306930e4480ddca49692

-----------------------b08bd1e2a694306930e4480ddca49692
Content-Type: text/html;charset=utf-8
Content-Transfer-Encoding: base64

PGRpdj5UaGlzIGlzIGEgdGVzdCBtZXNzYWdlIHRoYXQgaXMgc2lnbmVkIHdpdGggUEdQL01JTUUu
PC9kaXY+
-----------------------b08bd1e2a694306930e4480ddca49692--
-----------------------7b9e008e3e6e7b73e5019c70f73200c1--
-----------------------a5cfd59260dd8280de7cb6716a3ae396--
```

__Source as shown with `:togglesource`:__
```
Content-Type: multipart/mixed;boundary=---------------------a5cfd59260dd8280de7cb6716a3ae396

-----------------------a5cfd59260dd8280de7cb6716a3ae396
Content-Type: multipart/alternative;boundary=---------------------7b9e008e3e6e7b73e5019c70f73200c1

-----------------------7b9e008e3e6e7b73e5019c70f73200c1
Content-Transfer-Encoding: quoted-printable
Content-Type: text/plain;charset=utf-8

This is a test message that is signed with PGP/MIME.
-----------------------7b9e008e3e6e7b73e5019c70f73200c1
Content-Type: multipart/related;boundary=---------------------b08bd1e2a694306930e4480ddca49692

-----------------------b08bd1e2a694306930e4480ddca49692
Content-Type: text/html;charset=utf-8
Content-Transfer-Encoding: base64

PGRpdj5UaGlzIGlzIGEgdGVzdCBtZXNzYWdlIHRoYXQgaXMgc2lnbmVkIHdpdGggUEdQL01JTUUu
PC9kaXY+
-----------------------b08bd1e2a694306930e4480ddca49692--

-----------------------7b9e008e3e6e7b73e5019c70f73200c1--

-----------------------a5cfd59260dd8280de7cb6716a3ae396--

```

Notice the additional blank lines introduced between the last three ending separators.

It seems necessary to perforn the signature verification on the original .eml to avoid those alterations.
