### ISSUE TITLE
on account settings configure default bcc

### ISSUE THREAD

**Issue by genofire** [pazz/alot#1464]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when i compose a mail after choosing my sender mail x and i must always add a cc or bcc to the new mail

**Describe the solution you'd like**
a way to configure beside from settings on account also thinks like a default settings for composing:
- cc
- bcc
- subject prefix

**Comment by pazz** [comment]
I suggest you change your bindings to include the respective parameters for the `compose` command.
See https://alot.readthedocs.io/en/latest/usage/modes/global.html

You could also define a  [hook[(https://alot.readthedocs.io/en/latest/configuration/hooks.html#pre-post-command-hooks) such as `pre_edit` to alter your email template only for specific accounts. Feel free to browse, use, and extend the [user contributed hooks](https://github.com/pazz/alot/wiki/Contrib-Hooks) in our wiki.
