### ISSUE TITLE
default colors hard to read on black background

### ISSUE THREAD

**Issue by archenemies** [pazz/alot#1471]
**Describe the bug**

The default color scheme makes it impossible to read the selected message in the search buffer.

Here is a picture of what I am seeing, it is yellow-on-white:

![w1](https://user-images.githubusercontent.com/12960503/75789605-cc86a680-5d1e-11ea-98f2-055070e85055.png)

I tried copying the "16_" and "256_" lines from https://github.com/pazz/configs/ and changing "yellow" and "brown" to "black", but it didn't have any effect.

Did I recall an option to get alot to come up in black-and-white?

That's probably what I'm looking for - although it seems strange that the default color scheme would be unreadable on terminals with a black background.

**Software Versions**
- Alot version: 0.9
- Urxvt:

      rxvt-unicode (urxvt) v9.22 - released: 2016-01-23
      options: perl,xft,styles,combining,iso14755,unicode3,encodings=eu+vn+jp+jp-ext+kr+zh+zh-ext,transparent,tint,pixbuf,XIM,frills,selectionscrolling,wheel,slipwheel,cursorBlink,pointerBlank,scrollbars=plain+rxvt+NeXT+xterm

**Comment by archenemies** [comment]
I noticed this only happens when I am running alot inside a very old version of screen; otherwise the selected entry is yellow-on-gray which is a little more readable.

I would still appreciate any hints on how to change the color scheme. Thanks.

**Comment by ninewise** [comment]
You can set the theme in the config file, for instance `theme = "mutt"`. Note that this well change the entire theme, not just the colours. More information on theming can be found at https://alot.readthedocs.io/en/latest/configuration/theming.html.

**Comment by archenemies** [comment]
Thank you @ninewise, that helps.
