### ISSUE TITLE
How do you delete a message?

### ISSUE THREAD

**Issue by earksiinni** [pazz/alot#1473]
How do you delete a message? Am I missing something conceptually...? Like, am I supposed to tag messages that I want to delete with a special tag...? I don't see a command for doing this in the docs.

**Comment by earksiinni** [comment]
Aha, I did some more research and I see why `alot` doesn't support deletion out-of-the-box.

`alot` is an email client that's first and foremost an interface for `notmuch`. It appears that email systems using `notmuch` are assumed to never delete emails, or in general, the idea of deleting an email is given second thought. The `notmuch` way is to keep a permanent record of all your emails and assign them tags. So a "deleted" email might simply be an email that has had its `inbox` and `unread` tags replaced with `killed`, `deleted`, or `trash`. Therefore, `alot` doesn't have a built-in way to delete an email, but you can use `alot` to assign whatever tags you please.

That's not to say that you can't delete emails while using `alot` or `notmuch`, but it would require some sort of external process, the details of which would depend on how the rest of the email system is configured. For example, you could use `alot` to tag emails that are to be deleted with the `trash` tag, have a background task periodically delete all `trash` emails and synchronize the deletions to your remote server. Or you could write a shell script to kick off the deletion and synchronization process, then map it to a key in `alot`. The possibilities are endless!

**Comment by pazz** [comment]
Thanks for answering your own question in such detail :)

Let me att one more thing: this feature was, upon popular request, ultimately implemented in alot itself:
Check out the "remove" command in thread mode..
Cheers,
P


Quoting Ersin Akinci (2020-03-08 02:11:04)

**Comment by earksiinni** [comment]
@pazz thanks for the hint about `remove`. Is it related to `removequery`? I read the documentation for `removequery` but I didn't understand what it does because I don't know what a "named query" is.

**Comment by earksiinni** [comment]
@pazz could you also explain how `remove` is supposed to work? I just tried it and it didn't seem to do anything.

**Comment by pazz** [comment]
I just had a look into the code and it seems that 'remove' doesn't actually remove the mail file
it just deletes the entry from your notmuch index (database).
That should mean that that message will not appear in search results.

However, I don't use this feature and it may be buggy: I can imagine that "notmuch new" puts it back.. please try and report.
In any case, if you want to actually remove the file, you'd need to write a hook  for now.

"Named searches" are notmuch speak for query aliases. Notmuch stores a mapping of alias strings to full query strings in its database.
