### ISSUE TITLE
`from` header is not correctly encoded when replying

### ISSUE THREAD

**Issue by stregouet** [pazz/alot#1482]
First, thanks for prodiving such a good companion for notmuch! alot is awesome!

In thread buffer when invoking reply command, realname associated to my account is not correctly encoded in `From` header (some non ascii char are leaking in header)
It seems this is related to `determine_sender` which uses custom `format_addr` instead of `email.utils.format_addr`.

I provide a pull request to make my point clearer, feel free to discard it if it has nothing to do with this encoding issue ;)

**Comment by pazz** [comment]
Glad you like it and welcome to alot!

Unfortunately, `email.utils.format_addr` is not the solution to this problem see the 9b75fec97b4ad23178a730623ba691fbe666a747 and the related issue #1403  
It is possible that reading strings from the config has to go through an encoding filter before we use it?

**Comment by stregouet** [comment]
ok, maybe we should consider all headers as unicode (I mean as far as enveloppe class is concern) and do encoding stuff just at the  very end: in construct_mail method
This can be done by setting  policy to `email.policy.default` on `outer_msg` variable.
What do you think?

**Comment by pazz** [comment]
Quoting stregouet (2020-04-02 14:12:13)

> ok, maybe we should consider all headers as unicode (I mean as far as enveloppe
> class is concern) and do encoding stuff just at the very end: in construct_mail
> method
> This can be done by setting policy to email.policy.default on outer_msg
> variable.
> What do you think?

Yes, that was the idea behind the current implementation of alot envelopes.
If you find a violation to this ideal, a fix would be much appreciated.

**Comment by stregouet** [comment]
Yes I found violation with two kind of headers: `Subject` and `From` 

I submitted a new pull request to illustrate my point, let me know what do you think about it.

**Comment by stregouet** [comment]
closing as fixed by pull request #1485
