### ISSUE TITLE
Emails with non-ASCII subjects are bounced by SMTP server without UTF-8 support

### ISSUE THREAD

**Issue by aepsil0n** [pazz/alot#1484]
**Describe the bug**
When sending emails using alot that include non-ASCII characters to a SMTP server that does not support UTF-8 in mail headers, the email is bounced by the server.
Likely due to a bug in Python, see [issue 40157][python-issue]

**Software Versions**
- Python version: 3.6-3.8
- Alot version: 0.8-0.9

**To Reproduce**
1. Get a SMTP server, that does not support UTF-8 in headers.
2. Compose a mail with non-ASCII characters in the subject
3. Send it via that server under 1.

**Error Log**
What I get from the SMTP server:
`550 Subject contains invalid characters. (in reply to end of DATA command)`

The bounced message looks like this (somewhat redacted for privacy reasons):

```
Content-Type: text/plain; charset="utf-8"
MIME-Version: 1.0
Content-Transfer-Encoding: quoted-printable
Subject: Test üäö
From: one.of.my@mails.com
To: another.mail@of.mine
Message-ID: <redactedmessageid@somecomputer>
User-Agent: alot/0.8
Date: Thu, 02 Apr 2020 12:41:21 +0200
```

The important aspect is `Subject: Test üäö`. This has not been encoded. I have traced this down through the source code to [alot/commands/envelope.py:245](https://github.com/pazz/alot/blob/cf433946921fe7475c3457affea02fd3328faf46/alot/commands/envelope.py#L245).

It was a bit strange to see this behaviour given the existence of `email.policy.SMTPUTF8`. But apparently they both encode headers the same way. I have the impression that this is a bug in the Python standard library, so I also opened [issue 40157][python-issue] on the Python bug tracker.

As a workaround, removing the policy parameter and thereby falling back to the default compat32 policy, fixes the problem for me. Does that have any unintended side-effects?

[python-issue]: https://bugs.python.org/issue40157

**Comment by pazz** [comment]
@aepsil0n Could you check if #1485 fixes your issue?

**Comment by aepsil0n** [comment]
Thanks for the heads-up. I just checked the issue with the current master (8e96d504) and can confirm that it fixes my issue.

**Comment by pazz** [comment]
Wait: what? This supposed fix is not yet part of the master branch..

**Comment by aepsil0n** [comment]
There are two commits (5855e100 and 3ea84785) by @stregouet on master. You merged them in #1485. That is why I simply pulled in the recent master branch to check. Were you not referring to these commits?

**Comment by pazz** [comment]
sorry, you are right. These are part of the master branch already. Thanks for confirming the fix!

**Comment by aepsil0n** [comment]
No worries. Glad I could help with testing.
