### ISSUE TITLE
Help of the "unattach" command isn't clear

### ISSUE THREAD

**Issue by pacien** [pazz/alot#1489]
The help message and the documentation of the "unattach" command doesn't make it clear that it removes attachment __whose name contain the hint parameter as an infix__.

This command should perhaps accept a glob pattern with wildcards for consistency with the "attach" command.

A more natural name for this command could also be "detach". Maybe this command should be renamed or an alias be added.

**Comment by pazz** [comment]
sure, I'm fine with these changes.
