### ISSUE TITLE
`fold *` sometimes doesn’t actually fold

### ISSUE THREAD

**Issue by kirelagin** [pazz/alot#1496]
**Describe the bug**

When in thread view, running `fold *` sometimes does not fold all messages.

**Software Versions**
- Python version: 3.7.7
- Notmuch version: 0.29.3
- Alot version: 0.9, master

**To Reproduce**

1. Unpack somewhere this [maildir](https://github.com/pazz/alot/files/4502615/alotrep.tar.gz) (it contains 1 thread of 3 messages).
2. Make a new notmuch config with a path to this maildir.
3. `export NOTMUCH_CONFIG=/path/to/config && notmuch new`.
4. Only tag the middle message: `notmuch tag -inbox '*' && notmuch tag +inbox id:serokell/serokell.nix/pull/2/review/396149515@github.com`
5. Run `alot` with empty config.
6. Open thread.
7. Type `:fold *<enter>`.

Expected: all messages fold.
Actual: the second message folds, two others unfold. If you type `:fold *<enter>` again, all fold.

**Error Log**
[logfile.gz](https://github.com/pazz/alot/files/4502621/logfile.gz)

**Comment by kirelagin** [comment]
Actually, it is starting to look like the problem is not only with folding.

* If I search for `tag:inbox`, highlight the thread and run `tag important`, only the second message in the thread gets tagged.
* If I search for `*`, highlight the thread and run `tag important`, only the first and the second message get tagged.

Either something is very wrong with thread operations, or I am deeply confused.

**Comment by pazz** [comment]
@kirelagin You are not imagining things. I believe the problem is that the screen is not always re-drawn as one expects. Urwid is funny. One issue is that we don't want to do a "refresh" after each command because that would usially re-build the whole buffer and reset the focus.
Someone™ should defo look into where and when alot redraws its screen.
