### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by rien** [pazz/alot#1500]
I'm trying to update the alot package for void-linux, but the latest release has some issues (which have been patched on the master branch). I can apply the commits as patches, but may I suggest to release a new (minor) version?

**Comment by pazz** [comment]
I'm not sure if there were any new issues that justify a new release put sure,
I'll put that on my todo for the next few weeks.
There is also a backlog of new fixes and features that I'll merge soon.



Quoting Rien (2020-05-02 17:29:07)

**Comment by rien** [comment]
The fix for #1468 is not present in the latest release, which is currently preventing me to send emails without a patch.

I'll package it for void with the patch for now, so there is no hurry. Thank you for considering it!

**Comment by pazz** [comment]
https://github.com/pazz/alot/releases/tag/0.9.1

**Comment by rien** [comment]
I asked for a bugfix release, but got new features, thanks!
