### ISSUE TITLE
error popup upon erroneous abook command

### ISSUE THREAD

**Issue by pazz** [pazz/alot#153]

**Comment by lucc** [comment]
I get a nice notification if the command can not be found. What is the error you see?

**Comment by pazz** [comment]
I believe this was about a command that can be found but doesn't produce the expected output but fails and prints to stder. I'll try to reproduce this, hang on.

**Comment by pazz** [comment]
OK, I tried with /bin/false (gives a nice error notification, and with a command that prints to stderr (simply doesnt match my regexp so does nothing). All as expected, so I'll close this issue as non-reproducible.
