### ISSUE TITLE
Emails from alot 0.8.1 seem to not encode non-ascii subject

### ISSUE THREAD

**Issue by ivyl** [pazz/alot#1532]
**Describe the bug**
I am not an alot user, this is something that I have noticed as a person in charge of freedesktop.org's patchwork.

We have a few users that are using alot for mails. There are some emails from the CI system that use UTF-8 characters in the subject.

Whenever alot users are replying to those emails the header doesn't get properly encoded/escaped before being piped into "sendemail". 

My guess is that the header gets used as-is without being escaped with what's described in RFC2047. I am not sure whether the 8bit-unkown is caused by alot directly or by MTA or MDA trying to interpret and correctly encode raw UTF8 it has received.

Patchwork issue: https://gitlab.freedesktop.org/patchwork-fdo/patchwork-fdo/-/issues/43

Our workaround: https://gitlab.freedesktop.org/patchwork-fdo/patchwork-fdo/-/commit/a7046dcae33204ff0024155c23e713c29b3080a2

**Software Versions**
- Alot version: 0.8.1 (the only version I have seen in the logs)

**To Reproduce**
Steps to reproduce the behaviour:
1. reply to an email with UTF-8 in the subject

**Comment by pazz** [comment]
Thanks for reporting this.

Just FYI, alot is relying on pythons email library for the creation of RFC conformant emails.
I have the feeling that [your particular issue may have been fixed recently](https://github.com/pazz/alot/issues/1484).
Could you try and get some of your users to upgrade and see if that fixes the issue? Or simply look for version 0.9 or higher in your logs..

**Comment by ivyl** [comment]
Hey pazz,

I was kind of expecting that it steams from Python's standard library. I had similar experience recently with [another issue](https://github.com/python/cpython/commit/c1f1ddf30a595c2bfa3c06e54fb03fa212cd28b5).

Patchwork only logs the MUA when parsing exception occurs, but I guess with some creative searches done through the general archive I may be able to confirm that newer versions of alot are handling things correctly.

I'll ask the users to update, but they are die hard users of Debian stable, so this may take a while :-)

**Comment by pazz** [comment]
OK then, I'll close the issue for now. Feel free to reopen if you have confirmed cases with later versions.
Cheers,
P
