### ISSUE TITLE
Github Sponsor for alot?

### ISSUE THREAD

**Issue by hgvhgv** [pazz/alot#1545]
**Is your feature request related to a problem? Please describe.**
The problem is that I want to support and contribute to alot but I don't code beyond tinkering with my own shell scripts and altering more complicated scripts written by others.

**Describe the solution you'd like**
Have alot join the Github sponsorship program, which allows backers to support specific github projects (https://docs.github.com/en/free-pro-team@latest/github/supporting-the-open-source-community-with-github-sponsors/about-github-sponsors). There are no fees and the only criterion for joining is to be in an eligible region. How you distribute income would be up to the maintainers. Neovim uses it (https://github.com/sponsors/neovim)

**Describe alternatives you've considered**
Patreon seems like overkill and they charge fees. You could also just put a paypal tip me link somewhere on the Github / RTFD page.

**Additional context**
Alot is my main email client. Along with neovim, pandoc, and some other basic shell tools (e.g., fzf), alot is the cli program I use the most. I pay fastmail for my email hosting, and alot is nearly as crucial to my workflow as fastmail. I don't expect bug fixes or feature requests or anything, just a way to support something I use regularly. At my current income level (grad student) I could imagine paying somewhere between 1 and 3 dollars a month (fastmail is $5 per month). I know it doesn't seem like much, but that's where I am at this point. Maybe it's not worth it? I guess ideally the support would keep at least @pazz in coffee or beer.

I'm curious to hear what others think.

**Comment by pazz** [comment]
Hey!

Honestly, I'm flattered that you'd consider this but I'm similarly doubtful:

Even if there is some money flowing in, it is not going to motivate me personally to spend more time on this project, as I have a full-on real job that's lots of fun.
I would just feel bad for neglecting alot, and I don't like to give people the false impression that paying money for this will in any way guarantee continued development.
Also, I'd feel obliged to redistribute "income" among the many real contributors, and that's just another job.

However, if a few more people believe it's a good idea to just buy me a beer, no strings attached, then I could set something up (suggestions welcome) and you can go ahead and do that.
I'd also be happy to share a list of personal paypal-y type links of the most prolific contributors in the FAQ.

Cheers!
P

**Comment by hgvhgv** [comment]
I definitely don't want to cause undue stress or bad feelings! And it's a good point that creating the sense that development might continue beyond the current setup is probably not good (though I'm impressed you are going on a decade soon enough?).

Fwiw, I do think the Github sponsorship setup allows you to just set who gets what percentage based on different types of contributions (commits, code review, etc.). But you are definitely right that it's probably not as simple as it seems from the outside and would take at least some work on your part.

I think your suggestion to list paypals in the FAQ is good. Then it's more of a one-off contribution/thanks/fee than anything that could create longer-term consequences/stress/expectations.

I'll let you decide if you want to keep this up any longer to get more, but it's fine to close by me---seems solved!
