### ISSUE TITLE
notmuch-addrlookup

### ISSUE THREAD

**Issue by atrent** [pazz/alot#1551]
This "issue" is just my way of dropping a couple of lines to support 'notmuch-addrlookup' (much faster than 'notmuch address' when just searching for email addresses).
I'm referring to page https://alot.readthedocs.io/en/latest/configuration/contacts_completion.html

Use:

```
		  command = 'notmuch-addrlookup '
		  regexp = '(?P<name>.*).*<(?P<email>.+)>'
```

in the '[[[abook]]]' section of '[[youraccount]]'

**Comment by pazz** [comment]
nice. Can you just send a PR do add this to the docs? Cheers

**Comment by lucc** [comment]
Or you can add it to the wiki. I just started a page for this :)
https://github.com/pazz/alot/wiki/Address-Book-Examples

**Comment by lucc** [comment]
But we could also collect a table of programs and regexes that are known to work in the official docs!

**Comment by atrent** [comment]
I'm not very familiar to the github web interface but I think I've created the PR, feel free to edit it of course.
Otherwise I can fill the wiki page @lucc mentioned.
Let me know.

**Comment by pazz** [comment]
Thanks. I think we can include this as is.
I would not mind moving all regexps for those tools from the sphinx docs into the wiki but for now, for consistency's sake we should treat them all the same..

**Comment by lucc** [comment]
I did not remember the long list in the docs and only now saw the comment there asking for more. I think the best would be to keep that in the docs.  If it gets to much we can turn it into a table.
