### ISSUE TITLE
pipeto using many messages at once

### ISSUE THREAD

**Issue by atrent** [pazz/alot#1555]
I have tried to pipe many messages (i.e., an entire thread) at once into a "viewer" using the following binding:
```
			'ctrl D' = pipeto --background --all --format=decoded ~/bin/stdinGeany.sh
```
(where stdinGeany.sh is a script that opens the piped content in geany editor)
But alot pipes only the "current" message into the pipe.
I'm in thread mode.

What am I doing wrong?
Thank you

**Comment by pazz** [comment]
This looks like a bug.

**Comment by atrent** [comment]
while 'print --all --add_tags' works as expected, it generates one single stream

**Comment by atrent** [comment]
SOLVED, it was my fault, I'm closing this "bug", the real problem was caused by my config, I did:

```
	'ctrl r' = pipeto --background ~/bin/stdinGeany.sh
	'ctrl R' = pipeto --background --all ~/bin/stdinGeany.sh

	'ctrl d' = pipeto --background --format=decoded ~/bin/stdinGeany.sh
	'ctrl D' = pipeto --background --all --format=decoded ~/bin/stdinGeany.sh
```
Believing in differentiation between lowercase and uppercase, but that's not the case, maybe you should warn in the doc.
Thank you

**Comment by pazz** [comment]
Oh right: for upper case you'd need "shift d" or similar I believe..


Quoting atrent (2020-11-17 07:23:15)

**Comment by atrent** [comment]
1) 'shift d' does not work, as a workaround I chose a different key

2) '--background' dose not work, the UI is blocked

**Comment by pazz** [comment]
Quoting atrent (2020-11-17 11:26:57)

>  1. 'shift d' does not work, as a workaround I chose a different key


sorry, you are right: urwid distinguishes D from d:
http://urwid.org/manual/userinput.html#keyboard-input


>  2. '--background' dose not work, the UI is blocked

so this is a bug in alot then?

**Comment by atrent** [comment]
> 2. '--background' does not work, the UI is blocked
> so this is a bug in alot then?

if you can reproduce it, yes

**Comment by atrent** [comment]
> 1. 'ctrl shift d' does not work, as a workaround I chose a different key
> sorry, you are right: urwid distinguishes D from d: http://urwid.org/manual/userinput.html#keyboard-input

I'll try 'shift ctrl d' instead of 'ctrl shift d', thank you
