### ISSUE TITLE
Open URLs in message (with solution)

### ISSUE THREAD

**Issue by atrent** [pazz/alot#1556]
I need a simple mechanism to open (a choice of) URLs in a message, this is my script:

```
#!/bin/bash

# TODO launch default browser? (e.g. i3-sensible-browser)

estrattore(){
	grep -o 'http[s]*://.*' |while
	 read url
	do
	 echo -n "$url | off "
	done
}


if
 ! pidof chromium
then
 dialog --infobox "ATTENZIONE: no chromium open! (this script becomes blocking for alot)" 0 0
fi

URLS=$(estrattore)
#echo $URLS

if
 ! test -z "$URLS"
then
	scelta=$(mktemp)
	dialog --checklist URLs 0 0 0 $URLS 2> $scelta
	#cat $scelta

	for url in $(cat $scelta)
	do
		chromium $url 2>/dev/null &
	done

	rm $scelta
fi

```

It uses dialog to let me tick a selection of the URLs found in msg, then it opens chromium (or whatever you want) on the selection, I have hooked it to a key:

```
	[[thread]]
			'u' = pipeto --format=decoded ~/bin/openUrls.sh

```

**Comment by pazz** [comment]
There are several tools for this sort of thing, which eat text on stdin and provide a curses ui for selecting contained URLs. Try urlscan:

u = pipeto 'urlscan -c 2> /dev/null'


I'm also using a custom hook to open the contained html directly i na browser:

https://github.com/pazz/alot/wiki/Contrib-Hooks#open-html-emails-in-external-browser

HTH,
P


Quoting atrent (2020-11-30 10:05:58)

**Comment by atrent** [comment]
Perfect! I simply missed it ;)
Trash this thread then, sorry

**Comment by pazz** [comment]
Just FTR, I use the same custom hook also in envelope mode when I sent html mails (using pandoc)..


Quoting atrent (2020-11-30 10:42:47)
