### ISSUE TITLE
Edit mail in a different terminal tabs than the main alot windows

### ISSUE THREAD

**Issue by psic** [pazz/alot#1560]
**Describe the bug**
I don't know if it is really a bug, a misconfiguration by myself or ... a feature request.
I'd like to write my email (create or respond) in a different (new one for each mail) terminal tab than the main tab of alot. It's pretty easy to setup for opening or creating a mail in a new tab with  the header, and edit the mail with vim or nano. I try with tmux, screen , kitty and other terminal. Each time,  whatever the terminal I used, when I close the editor (and the mail is really in the temp file) and normally come back to main windows, the previously edited mail is empty/not showed.

Subsidiary question, is there any way to ask for configuration tips ? any mailing list ? reddit sub or else ?

**Software Versions**
- Python version:3.6.9
- Alot version: 0.9.1

**Comment by lucc** [comment]
Can you post your config (especially `terminal_cmd`, `editor_in_thread`, `editor_spawn`, `editor_cmd`/`$EDITOR`) so that we can better understand your question.

I would assume that you need to set `terminal_cmd` to something like `myTerminal --open-new-tab --forground --execute`. The foreground part is important. If the terminal command that alot executes returns right after it was executed and the terminal window/tab runs in a background process then alot thinks you are done editing already (but you did not even start yet).

Did you have success with new terminal windows (instead of tabs)? In this case you might be able to see the main alot terminal and your editor terminal side by side and spot some hints on what is going on in which order.

**Comment by lucc** [comment]
There is the `#alot` IRC channel on freenode.net, I do not know of any other forums or mailing lists.

**Comment by psic** [comment]
Your assumption is right, but I was aware about the `foreground` part.
`editor_in_thread` and `editor_spawn` are always set to True.
`editor_in_thread=True`
`editor_spawn=True`
`editor_cmd="nano -Y alot -m +4"`
To start nano with an alot custom style, with the cursor on the fourth line, just under the header.
`terminal_cmd="screen -S alot -X screen " ` for screen using st as terminal
`terminal_cmd="kitty @ launch --type=tab"` for the kitty terminal
`terminal_cmd="tmux new-window "` for tmux using st as terminal
No problem to work with terminal in new window.

**Comment by lucc** [comment]
I tested your `terminal_cmd` (the tmux and kitty version)  and both return immediately (after <1sec). (NB: the shell command that starts the new tab/window returns but the tab/window lives on; but alot only knows about the shell command that started the tab/window) That means alot sees the command as finished and then reads back the tmp file.

You need to find a version of your commands that only return when the tab/window they opened is closed (or wrap them in some shell script to do that manually).

**Comment by psic** [comment]
Thanks for the test. How do you test it ? How do you know the shell command returns immediatly. I've never noticed this behaviour.

**Comment by lucc** [comment]
I open a kitty or tmux and then type the respective command.  You will be put in the new tab/window but if you navigate back you can see that the shell command you executed did already finish and you have a command prompt in your original window. You can even execute more commands there with the new tab still alive. If you close the new tab (exit) you will see no indication of this in the original tab.

You can also try to execute `time tmux new-window sleep 10` in tmux  or `time kitty @ launch --type=tab sleep 10`.  Your new tab will be open for 10 seconds but `time` will report that the command to open the tab returned after <1sec.

**Comment by lucc** [comment]
You might have to write some small wrapper shell script like this: https://stackoverflow.com/questions/60365501/run-command-in-new-background-tmux-window-and-wait-for-process-to-finish

**Comment by psic** [comment]
Thnaks `alot` !
I understand something today. Sorry to open an issue for that.
