### ISSUE TITLE
Cannot quit when opening in read-only mode

### ISSUE THREAD

**Issue by aplund** [pazz/alot#1563]
I've run alot using this command:

`alot -r -l /tmp/alot.log`

and then tried to quit.  The result in the log is:

>ERROR:ui:Traceback (most recent call last):
>  File "/usr/lib/python3.9/site-packages/alot/ui.py", line 723, in apply_command
>    cmd.apply(self)
>  File "/usr/lib/python3.9/site-packages/alot/commands/globals.py", line 611, in apply
>    ui.dbman.flush()
>  File "/usr/lib/python3.9/site-packages/alot/db/manager.py", line 62, in flush
>    raise DatabaseROError()
>alot.db.errors.DatabaseROError`

Furthermore the interface does not quit and you are stuck unless you send a SIGINT.

**Software Versions**
- Python version: 3.9.1
- Notmuch version: 0.31
- Alot version: git commit 486df70d

**Comment by pazz** [comment]
Thanks for reporting. I can confirm this bug.

**Comment by DSpammy** [comment]
This bug still exists in version 0.10. :-(
