### ISSUE TITLE
Errors after upgrade => 0.9.1

### ISSUE THREAD

**Issue by robert-winkler** [pazz/alot#1570]
Hi, for using bleeding edge alot, I purged the Ubuntu 20.04 version and installed from git; v. 0.9.1
Errors from `alot -d debug -l alot.log`:
~~~
INFO:utils:Unknown values were found in `/home/rob/.config/alot/config`. Please check for typos if a specified setting does not seem to work:
search
ERROR:manager:unable to load hooks file:/home/rob/.config/alot/hooks.py  
~~~
This is correct: file `hooks.py` is not existing. How can I create it?

I open a HTML file and get an error:
~~~
DEBUG:utils:command: w3m -dump -o document_charset=UTF-8 '/tmp/i038sx_6.html'
DEBUG:utils:parms: ('text/html=', 'charset=UTF-8')
DEBUG:helper:Calling ['w3m', '-dump', '-o', 'document_charset=UTF-8', '/tmp/i038sx_6.html']
DEBUG:thread:setting focus to ('8rMrxkJMS-idJTDRpuGsvg@ismtpd0196p1mdw1.sendgrid.net', (0,)) 
ERROR:ui:Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/alot-0.9.1-py3.8.egg/alot/ui.py", line 723, in apply_command
    cmd.apply(self)
  File "/usr/local/lib/python3.8/dist-packages/alot-0.9.1-py3.8.egg/alot/commands/search.py", line 43, in apply
    tb.unfold_matching(query)
  File "/usr/local/lib/python3.8/dist-packages/alot-0.9.1-py3.8.egg/alot/buffers/thread.py", line 344, in unfold_matching
    self.set_focus(first)
  File "/usr/local/lib/python3.8/dist-packages/alot-0.9.1-py3.8.egg/alot/buffers/thread.py", line 183, in set_focus
    self.body.set_focus(pos, valign='top')
TypeError: set_focus() got an unexpected keyword argument 'valign'
~~~
The later is a bit annoying, because in HTML emails I get a read error message (TypeError: set_focus() got an unexpected keyword argument 'valign').

**Comment by pazz** [comment]
Quoting Robert Winkler (2021-04-14 22:17:43)

> Hi, for using bleeding edge alot, I purged the Ubuntu 20.04 version and
> installed from git; v. 0.9.1
> Errors from alot -d debug -l alot.log:
> 
> INFO:utils:Unknown values were found in `/home/rob/.config/alot/config`. Please check for typos if a specified setting does not seem to work:
> search
> ERROR:manager:unable to load hooks file:/home/rob/.config/alot/hooks.py
> 
> This is correct: file hooks.py is not existing. How can I create it?

Just add an empty python file under that name. This error should not be critical.


> I open a HTML file and get an error:
> 
> DEBUG:utils:command: w3m -dump -o document_charset=UTF-8 '/tmp/i038sx_6.html'
> DEBUG:utils:parms: ('text/html=', 'charset=UTF-8')
> DEBUG:helper:Calling ['w3m', '-dump', '-o', 'document_charset=UTF-8', '/tmp/i038sx_6.html']
> DEBUG:thread:setting focus to ***@***.***', (0,))
> ERROR:ui:Traceback (most recent call last):
>   File "/usr/local/lib/python3.8/dist-packages/alot-0.9.1-py3.8.egg/alot/ui.py", line 723, in apply_command
>     cmd.apply(self)
>   File "/usr/local/lib/python3.8/dist-packages/alot-0.9.1-py3.8.egg/alot/commands/search.py", line 43, in apply
>     tb.unfold_matching(query)
>   File "/usr/local/lib/python3.8/dist-packages/alot-0.9.1-py3.8.egg/alot/buffers/thread.py", line 344, in unfold_matching
>     self.set_focus(first)
>   File "/usr/local/lib/python3.8/dist-packages/alot-0.9.1-py3.8.egg/alot/buffers/thread.py", line 183, in set_focus
>     self.body.set_focus(pos, valign='top')
> TypeError: set_focus() got an unexpected keyword argument 'valign'
> 
> The later is a bit annoying, because in HTML emails I get a read error message
> (TypeError: set_focus() got an unexpected keyword argument 'valign').

Huh. I remember that there was some "recent" change in the urwidtrees package.
Perhaps I forgot to make a release there and increment the dependencies in alot?
Please check that you are running at least version 1.0.3 of urwidtrees..

**Comment by robert-winkler** [comment]
I run into another dependency problem: notmuch2>=0.3; I had to manually download and compile notmuch2 and install the python binding.
Sorry, I had to stop there, since I don't dare to mess up my system too much with different versions of python modules. 
Fortunately, 0.9.0 has all the function I need (after adding some hooks) for dealing with my 49,954 emails ;-).
