### ISSUE TITLE
How to open link under cursor?

### ISSUE THREAD

**Issue by robert-winkler** [pazz/alot#1575]
Hi, sometimes I get text mails (good) with HTML links (bad).
Is there a hook or function for opening, for example, a link under the cursor?
Currently, I copy such links from alot to the browser, using the mouse...
There must be a better way!
Best regards,
Robert

**Comment by lucc** [comment]
Some terminals allow you to klick on links (I am using termite, maybe gnome or kde terminal can do it too). Otherwise you could pipe the mail to a program like [urlscan](https://github.com/firecat53/urlscan): `:pipeto urlscan`.

**Comment by robert-winkler** [comment]
Awesome!!! ``urlscan`` is exactly what I needed! 
Thanks a lot again.
