### ISSUE TITLE
`No matching distribution found for notmuch2>=0.30`

### ISSUE THREAD

**Issue by chenrui333** [pazz/alot#1594]
👋  I have run into some build issue of installing alot from tarball file. Let me know if I need to provide more details.

**Describe the bug**
Could not run `pip install https://github.com/pazz/alot/archive/0.10.tar.gz`

**Software Versions**
- Python version: `Python 3.9.9`
- Notmuch version: [if relevant] `notmuch 0.34.2`
- Alot version: 0.10

**To Reproduce**
pip install the release tarball file

**Error Log**
```
$ pip install https://github.com/pazz/alot/archive/0.10.tar.gz
Collecting https://github.com/pazz/alot/archive/0.10.tar.gz
  Downloading https://github.com/pazz/alot/archive/0.10.tar.gz
     / 228 kB 868 kB/s
  Preparing metadata (setup.py) ... done
ERROR: Could not find a version that satisfies the requirement notmuch2>=0.30 (from alot) (from versions: 0.1, 0.30rc2)
ERROR: No matching distribution found for notmuch2>=0.30
```

**Comment by pazz** [comment]
The issue is that notmuch2 does not have a package on pip at all I think, at least not officially and supported by the notmuch team. For this project I do not maintain the pip package myself and recommend you install notmuch (and the python3 bindings from source before you install alot.
Hope you'll get it working and welcome to alot :)

**Comment by lucc** [comment]
I have just created a nix flake for the development version of alot. @chenrui333 if you use [nix](https://nixos.org) you can try it. @pazz maybe we can use that flake to help users that have trouble compiling/packaging alot+notmuch.

https://github.com/lucc/alot-flake

**Comment by pazz** [comment]
If you think it'd help please add to the documentation and send a PR?
P


Quoting Lucas Hoffmann (2022-01-04 23:37:33)
