### ISSUE TITLE
Contact completion with khard

### ISSUE THREAD

**Issue by robert-winkler** [pazz/alot#1596]
Hi, I recently switched my contact management from abook to **khard**. 
# Advantages
- Synchronizing local contacts with my Nextcloud vCard DB is possible.  <https://vdirsyncer.pimutils.org/en/latest/tutorials/>
- Contacts locally and remotely stored (redundancy/backup).
- Same address book on all computers.
- Editing of vCard contacts with kaddressbook (<https://apps.kde.org/kaddressbook/>).
# Migration of abook contacts
- export abook DB to vCard file (.vcf) <https://pypi.org/project/abook/>
- import to NextCloud contacts. 
# Autocompletion in alot
Entry in the `.config/alot/config` (for each account):
~~~
[[account]] 
        ...
        [[[abook]]]
               type = shellcommand
               command = khard email --remove-first-line --parsable
               regexp = '^(?P<email>[^@]+@[^\t]+)\t+(?P<name>[^\t]+)'
~~~
Seems to work nicely :-))

**Comment by lucc** [comment]
Is there an issue? Otherwise you can post your notes/guide in the wiki in [Address Book Examples](https://github.com/pazz/alot/wiki/Address-Book-Examples).

**Comment by robert-winkler** [comment]
Quoting Lucas Hoffmann (2022-02-03 01: 40:37)
Date: Thu, 03 Feb 2022 08:33:50 -0600
Message-ID: ***@***.***>
User-Agent: alot/0.9.1
X-Provags-ID: V03:K1:xNKvkUGakoxrcrJXQ5D16Xg0L6HtP3YXdK2Rp2snxebRdrdwBMJ
 5FjivtwQjXAd+2MTc2VwYnYA0BBjxjSoMhDApd4aIpDHhYMNRsUsg13HFI8cdHh7yygmev9
 z0/8bvv02nsI5aVA+fb7mNT4dFDgWShW0e9PRD7MPzymVPcOvj/VqcWn+rWuHslFu1AooG4
 v41MqImyaNZLt1KeDLsEw==
X-Spam-Flag: NO
X-UI-Out-Filterresults: notjunk:1;V03:K0:ghgKoZ6FVtY=:RU9Q0YApxlS2f9iDtKE4Jr
 1iYdx61M9oaL8a1wfK1M1aLXFr5nq+6BCM8IofSro+r4oR8krNTHHdB6o9stO8W948Lt0Sili
 WbPsL/6HHvHlqOzc5rFA5kly8UYn4xhdZOWTYxd70P8AZDQ/uVkrbepy/eHcODu9nwJvw257I
 R8NOAV1HtJ4EuvqPoHQT6NYS35LeCm6ju3tBnrF2GJ58m9HBMm4PeJXDdrNiyj9Xvh58irwFQ
 4N9o//LJo1nHVimNXBSupA8l46FrOY1N7QkLrx9Lq/qhcKX4OJ9TaT1MnoC/k3ptfsXrZ04ZO
 DhjoHFD74ttC+UVDv4eri9+HhygV20nVeUGYnWDq5G8rtDjtsTA22ZdVT8SKy0xdeYqYR56ac
 FhJvclUEY5/DsVcpjYutmkeCJvk9fOIwtFFzMUx2oywf4Bme+rbVGBMCTAqWilwNB/mtWTACA
 kfFWaCXEaj4pay3EEbDDtvPnRGJUI7uAH08VxfLK2bQI85N8fC0a

> Is there an issue? Otherwise you can post your notes/guide in the wiki in
> Address Book Examples.
>=20
> =E2=80=94
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android.
> You are receiving this because you authored the thread.*Message ID: <pazz=
/alot/
> ***@***.***>
>=20

You are right, this not an issue (well, I solved it while writing the
issue =F0=9F=98=89). OK, I'll post it to the Wiki.
