### ISSUE TITLE
would it be ok to convert installer to poetry ?

### ISSUE THREAD

**Issue by teto** [pazz/alot#1620]
**Is your feature request related to a problem? Please describe.**
The  'setup.py' approach is hardly automatable, which is why the python ecosystem currently discourage it https://peps.python.org/pep-0518/ . The pyproject.toml can be parsed by 3rd-party tools while addressing shortcomings of setup.py (can create a sandbox a la pipenv).
There is a lot on the subject, one random link https://venthur.de/2022-12-18-python-packaging.html

**Describe the solution you'd like**
I've had good experience with poetry in the past so I think it would be a good candidate to generate a pyproject.toml

**Describe alternatives you've considered**
do nothing

**Additional context**
I work with the package manager nix on the project, it's already doable but having a declarative setup of the project could help when adding dependencies and all. It would allow to automate the nix packaging via poetry2nix.

PS: I am willing to do the work if I get approval

**Comment by pazz** [comment]
Yes, absolutely, go ahead.
I would be happy to include the config file in the main repo if that's helpful.
thanks!

Quoting Matthieu Coudron (2023-05-19 10:27:47)

**Comment by teto** [comment]
submitted at https://github.com/pazz/alot/pull/1621

**Comment by teto** [comment]
merged and we also have a nix flake now so closing
