### ISSUE TITLE
0.11.tar.gz is much different than the v0.11 tag

### ISSUE THREAD

**Issue by jljusten** [pazz/alot#1681]
**Describe the bug**
I work on the debian alot packaging. I use git primarily for the packaging, but debian's tools also compare the tree with the release tarball. It looks like 0.11.tar.gz is significantly different than the v0.11 tag in git.

Debian's tools allow for ignoring some files when doing this diff, but that's more intended for files that aren't used by the software normally. For example, files only needed for CI, which could be stripped in the release tarball.

Here is a subset of the diff between the trees. The full diff file has 581 lines. `alot-0.11.orig` in this diff is the tarball, and `alot-0.11` is the v0.11 tag:

```diff
--- alot-0.11.orig/alot/__init__.py
+++ alot-0.11/alot/__init__.py
@@ -9,4 +9,9 @@ except PackageNotFoundError:
 
 
 __productname__ = 'alot'
+# -__copyright__ = "Copyright (C) 2012-21 Patrick Totzke"
+# __author__ = "Patrick Totzke"
+# __author_email__ = "patricktotzke@gmail.com"
 __description__ = "Terminal MUA using notmuch mail"
+# __url__ = "https://github.com/pazz/alot"
+# __license__ = "Licensed under the GNU GPL v3+."
--- alot-0.11.orig/alot/__main__.py
+++ alot-0.11/alot/__main__.py
@@ -1,4 +1,4 @@
-# Copyright (C) Patrick Totzke <patricktotzke@gmail.com>
+# Copyright (C) 2011-2012  Patrick Totzke <patricktotzke@gmail.com>
 # This file is released under the GNU GPL, version 3 or a later revision.
 # For further details see the COPYING file
 import argparse
```

**To Reproduce**

1. Extract 0.11.tar.gz
2. Checkout v0.11 in the git tree
3. Use a diff tool to compare the trees.

**Comment by pazz** [comment]
Oppsie.. this is on me, sorry for that.
Only after tagging `0.11` I realised that the new dynamic versioning feature we use requires a `v0.11` to interpret it as non-dev version, so I tagged again and must have missed a cleanup commit.
In any case, it appears that the two are functionally the same ane only differ in commented out packaging info (which is now only declared once at the appropriate place). If possible, just pick the "cleaner" version and package that.
Thanks for the heads-up though!
