### ISSUE TITLE
[rfe][search view] the displayed numbers of mails in a thread don't align upon differing arity 

### ISSUE THREAD

**Issue by 0x64746b** [pazz/alot#24]
this makes the start of the tags wiggle (and drives me further from my ultimate goal of having everything locked away in columns _evil laugh_ ;)) seriously though, I think having a column like look here should improve readability; and aligning num_mails should be possible without wasting too much screen space.

**Comment by pazz** [comment]
Tuesday 25/08/2011? I'm status you've missed that by a few years now :-)
So since obviously this hasn't been missed I'm closing this issue as wontfix.
cheers
