### ISSUE TITLE
Navigate to url in an email

### ISSUE THREAD

**Issue by ghost** [pazz/alot#316]
Many emails contain some hyperlinks which are supposed to be clickable in gui mail clients.
I think it would be useful to implement a similar function in alot.

I can offer two possible ways:
1. Like in vimperator, uzbl and other keyboard-driven browsers: pressing a key (e.g. <F>) triggers enumerating of all the links currently visible in the viewport and showing these numbers near the link. Typing this number should lead to opening the url in a browser
2. This solution also covers #315. Thread view should have a horizontal cursor (highlighted terminal line) movable with "j" and "k" keys. Pressing e.g. "Enter" should open url under the cursor in a browser.
This option also lets introduce vim-like scrollings like 'zt', 'zz', 'zb' etc naturally.

The second way looks more convenient for me, although the first one may be faster and treats situation (rare enough in emails imho) where there is more than one url in a line.

**Comment by varac** [comment]
I'm using [termite](https://github.com/thestinger/termite) as terminal, which in general has good URL handling. It works with single-line URLs but it breaks on multi-line URLs in alot (multi-line URLs in the terminal are not a problem).

I tried `pipeto urlview` as suggested above, which also works for single-line URLs but not for multi-line ones. @goneri Did you get `urlview` working with multi-line URLs ?

**Comment by varac** [comment]
Nice, `pipeto urlscan 2> /dev/null` works for me!

**Comment by pazz** [comment]
I'll close this for now: the proposed vertical focusing is a totally different breast from URLs in mails. Also, because alot relies on external tools to render HTML mails and most terminals nicely deal with url strings, I'd rather keep this functionality out.
