### ISSUE TITLE
Saved searches/folder list with count

### ISSUE THREAD

**Issue by quite** [pazz/alot#331]
Saved searches, like a folder list that Emacs-notmuch has.
Has it been discussed? How could it work, as a buffer?

I would like the ability to have such a list, and one which
also displays the number of messages/threads for each
entry. For emulating folders with unread indicators...

**Comment by TomasTomecek** [comment]
@pazz can I file a PR? Is it possible that you'll merge it at some point?

**Comment by pazz** [comment]
sure thing! send a pull request. Before you do its hard for me to comment on the details of your implementation anyway. It is of course likely that your first PR does not get pushed directly,
but this shouldn't discourage you from submitting it!
Just remember to send one PR per feature (you implement both a saved-search list and a folders-tree as new buffers?) and split your contribution into manageable chunks.

**Comment by ibotty** [comment]
Just FYI: Notmuch 0.23 added "Support for named queries". So "saved searches" are in notmuch proper.

**Comment by pazz** [comment]
Is that documented somewhere?
thx,
p

Quoting Tobias Florek (2016-11-18 20:10:00)

**Comment by ibotty** [comment]
Yes. It's documented in notmuch-search-terms(7) and notmuch-config(1).

**Comment by pazz** [comment]
great! it seems to work for me:

1. check that `notmuch config get built_with.field_processor` returns `true`
2. `notmuch config set query.test "from:santa"
3. `notmuch search query:test`

search queries also work within alot as it's done in the lib \o/
Now it is a matter of adjusting alot's query string completer and perhaps build some small buffer to list saved searches.

**Comment by TomasTomecek** [comment]
I just tested what @pazz wrote and it works just fine for me (Fedora rawhide). I also agree that having a dedicated buffer with list of queries would be awesome! Unfortunately I won't have time to implement anything like that in near future.

**Comment by lucc** [comment]
On what system are you or how did you build xapian/notmuch with the field processor enabled? I think it is a compile time option of xapian but have trouble finding the right switch for it.

**Comment by TomasTomecek** [comment]
As I said, Fedora rawhide. This is [the build](https://koji.fedoraproject.org/koji/buildinfo?buildID=828767) and here is the [build log](https://kojipkgs.fedoraproject.org//packages/xapian-core/1.4.1/1.fc26/data/logs/x86_64/build.log). I haven't built it myself.

**Comment by lucc** [comment]
(I can confirm that the query:foo stuff now also works on Arch Linux (they are now shipping notmuch with the field processor enabled)).

So what exactly is missing from this issue/feature request? Is it only the ability to display mails from a certain file system folder (directory)? If so, are you aware of the `path:foo_bar` and `folder:foo_bar` syntax for notmuch queries? [Check it out in the docs](https://notmuchmail.org/manpages/notmuch-search-terms-7/).

**Comment by pazz** [comment]
I think we can close this issue in favor of more specific feature requests.
The one missing feature that would make sense to me (but is certainly not a priority)
would be some sort of Bufferlist/Taglist buffer to display saved searches linewise and open new searches on "select".

**Comment by lucc** [comment]
Done:  #1011

**Comment by pazz** [comment]
thanks lucc!
