### ISSUE TITLE
confirm send w/o attachment

### ISSUE THREAD

**Issue by pazz** [pazz/alot#395]
if keyword "attach" matches the body text.
this should be configurable.

the best solution that comes to mind is to put this into `envelope.SendCommand` and use `ui.choice` like
`globals.ExitCommand` does.

**Comment by josch** [comment]
The code you suggest doesn't work anymore:

```
ERROR:ui:Traceback (most recent call last):
  File "/usr/share/alot/alot/ui.py", line 272, in apply_commandline
    await apply_this_command(c)
  File "/usr/share/alot/alot/ui.py", line 713, in apply_command
    await cmd.prehook(ui=self, dbm=self.dbman, cmd=cmd)
  File "/home/josch/.config/alot/hooks.py", line 17, in pre_envelope_send
    if re.match('.*[Aa]ttach', e.body, re.DOTALL) and\
AttributeError: 'Envelope' object has no attribute 'body'
```

**Comment by pazz** [comment]
yes, I think it's called body_plaintext and body_html now...


Quoting josch (2020-02-14 09:05:28)

**Comment by josch** [comment]
Yes, `body_txt` and `body_html`. I assume one now has to check *both* parts for this kind of hook or is there a more convenient way?

**Comment by pazz** [comment]
Unless you are using the new txt2html feature, the html body should be None anyway. If you do, then it'd be a html-ized version of the plaintext. I'd just check the plaintext.


Quoting josch (2020-02-14 09:43:25)
