### ISSUE TITLE
fullwidth unicode characters distort bindings help

### ISSUE THREAD

**Issue by teythoon** [pazz/alot#570]
I've got a fullwidth unicode character mapping for a tag (the smiley) and it distorts the help screen. Not sure who's to blame here. For the record, alot is running in a gnome-terminal.

![visual_glitch](https://f.cloud.github.com/assets/469398/190991/d6de51ce-7f21-11e2-8c01-fed2327b5309.png)

**Comment by dcbaker** [comment]
I'm closing this. Gnome terminal and odd-width unicode characters don't seem to work ever.
