### ISSUE TITLE
crypto: add "encrypt_by_default" option

### ISSUE THREAD

**Issue by pazz** [pazz/alot#655]
there is a `sign_by_default` account option, but strangely, we are still missing a similar one to turn on encryption of outgoing mails per default.
I see four possibilities:

1. no encryption per default
2. encrypt if recipients pubkey is in my local keyring only
3. get the key locally or try to obtain a matching key from keyservers; complain on failures
4. like the previous case, but ignore errors and fall back to no encryption.

This is only about the initial value of an envelopes "encrypt" flag
when opening new envelopes. One should still be able to manually change it (as possible already).

I think the default behaviour should be option 3 for accounts which have some
private key assigned, and 1 otherwise.

**Comment by meskio** [comment]
I agree about (2), not just for the privacy issues. If alot retrieves keys from keyservers will need to take care of deciding which key should trust, and this is tricky to do it right. Should you do TOFU? Do you trust a key that was uploaded 5 years ago and never updated again (maybe the user generated just to try and never used gpg again)? ...

I don't think alot should become a complicated keymanager.

**Comment by freuk** [comment]
(2) +1 ! This is a much needed feature. :)

**Comment by pazz** [comment]
option 2 is implemented in #774 (and included in v 3.4.7)
