### ISSUE TITLE
Support groups in contacts completion

### ISSUE THREAD

**Issue by wor** [pazz/alot#658]
For example contacts completion shell command can return multiple names and addresses which mach certain group or alias. abook regexp value seems to expect that just one name and address is returned.

Example with goobook, when group named "Work" exists:

```
   $ goobook query Work
   firstname lastname <address>, firstname0 lastname0 <address0>      Work (group)
```

**Comment by dpaetzel** [comment]
This thread is three years old, but for people having the same question:  You could simply write a wrapper script that transforms such group results (e.g. from `goobook query` as mentioned above) into a single pair of a name that contains all name/email pairs but the last email address and the last email address.

The above example would therefore transform to the name being `firstname lastname <address>, firstname0 lastname0` while the address were `address0`.

See my try on it (working for me): https://github.com/dpaetzel/utility/blob/master/goobook-wrapper .

**Comment by lucc** [comment]
Another solution could be to use a hook to detect some special recipient and replace it by the group members:
```py
aliases = {
    'foo': ['foo1@example.com', 'foo2@exmple.com'],
    'bar': ['bar1@example.com', 'bar2@example.com']
}
def post_buffer_open(ui, dbman, buf):
    if buf.modename = 'envelope':
        # TODO modify buf.envelope['To'] and replace 'foo' or 'bar' with the list of addresses ...
        # Same for Cc and Bcc
        pass
```

**Comment by dcbaker** [comment]
I'm going to close this, because I think the answer is that this isn't something that alot needs to solve and ship, but a hook or external tool problem

**Comment by atrent** [comment]
> i'm not entirely sure what the intended behaviour here should be..
> do you just want to tab through all contacts in the result set in that case or do you want to have an alias that
> stands for a long string containing multiple contacts?

I may have solved the "problem" (i.e. having the ability to send mail to a group alias).
I've tried with an external script (hooked to [[[abook]]] shellcommand, source at the end of this comment) to generate lines such as:
```
groupname1: email1,email5,email7
groupname2: email2,email4,email11
...
```
and parse them with a regexp (in alot config) such as:
```
regexp = '(?P<name>.*).*:(?P<email>.+)'
```
the (name,email) pairs are extracted correctly (when auto-completing), then alot creates a To: line this way:
```
groupname1 <email1,email5,email7>
```
This is not entirely correct (in terms of To: standard) but it works.

### The hooked script

```
#!/bin/bash
notmuch-addrlookup $* | tr -s ' '|sed 's/ *</: /g' |tr -d '>'
grep -i "$*" .mailaliases
```

It can also be called by CLI passing any number of parameters, it returns matching lines, in .mailaliases I keep my groups in the form "<name>:<email>", such as:
```
name: email1, email2, email3, ...
groupname1: email1,email5,email7
groupname2: email2,email4,email11
...
```
If you call mailaddress.sh (the name of this script on my system) using:
```
mailaddress.sh groupname1
```
you get the corresponding lines extracted from notmuch-addrlookup AND the same extraction from .mailaliases, in a consistent and regexp-able form.





P.S. (in my PR about the "notmuch-addrlookup" hook I forgot an "r" in the header, I wrote "notmuch-addlookup")

**Comment by atrent** [comment]
then I discovered that msmtp supports aliases (see the 'aliases' directive in the .msmtprc), BUT the actual email is sent out with an implicit To: such as: "To: mailalias <>" without all the addresses

**Comment by pazz** [comment]
> groupname1 <email1,email5,email7>
>
> This is not entirely correct (in terms of To: standard) but it works.

I'm surprised that this "works". This does not look RFC conform (which means very little in the real world unfortunately).



> then I discovered that msmtp supports aliases (see the 'aliases' directive in
> the .msmtprc), BUT the actual email is sent out with an implicit To: such as:
> "To: mailalias <>" without all the addresses

Awesome! Thanks for making me aware!
P

**Comment by atrent** [comment]
> groupname1 <email1,email5,email7> This is not entirely correct (in terms of To: standard) but it works.
> I'm surprised that this "works". This does not look RFC conform (which means very little in the real world unfortunately).

I'm suprised too!
