### ISSUE TITLE
crypto: encrypt email by default if is a reply to an encrypted email

### ISSUE THREAD

**Issue by meskio** [pazz/alot#661]
I think that if the email I'm replying to was encrypted alot should encrypt the reply by default. Too often I send by mistake the body of an encrypted emails as plain text when I reply to them.

Other clients like mutt or thunderbird-enigmail do that.

**Comment by lamarpavel** [comment]
According to #774 this has been implemented and merged into master, I think this issue could be closed.

**Comment by pazz** [comment]
thanks for pointing this out!
