### ISSUE TITLE
Mouse event support via urwid

### ISSUE THREAD

**Issue by sjackso** [pazz/alot#664]
Urwid can deliver mouse and scroll wheel events.  It would be neat if alot could accept these.

@pazz, would you be open a pull request for such a feature?

**Comment by dcbaker** [comment]
@pazz. Do you want to leave this open or close it with #952 merged?

**Comment by pazz** [comment]
Let's close it, I'm quite happy with the current patch and
it clearly hasn't been a pressing issue in the past years :)

#close
