### ISSUE TITLE
Viewing threads does not mark them as read.

### ISSUE THREAD

**Issue by jasonmhite** [pazz/alot#672]
I'm having a bit of trouble with the `auto_move_unread` option not working. First, my setup...

Arch Linux, with the git versions of both Notmuch and Alot. I have two accounts that I'm using with OfflineIMAP (though of course Notmuch indexes them together) and both accounts configured to send with MSMTP.

My understanding is that `auto_move_unread` should remove the `unread` flag when I touch the message in thread view, but it does not seem to be doing so. Under no circumstances does it do so (either with multiple replies in a thread or on just a single message) and I've also tried explicitly setting `auto_move_unread=True` in the config. 

I am not sure if it is related, but I did some poking around with PDB. I stuck `pdb.set_trace()`'s in the `hooks.py` file so I could try and get a feel for what's going on. It seems that some of the buffer-related hooks aren't triggering, e.g. `pre_buffer_close` and `post_buffer_close`. I haven't gotten to dive into the Alot source much, but my guess is that the `auto_move_unread` feature is implemented using the same mechanism as the buffer hooks and that it isn't triggering properly.

Thanks.

**Comment by teto** [comment]
oh gosh that's counterintuitive. So you have to move to the body and refresh the index. Is it possible to automatically refresh the index upon a thread marked as read via auto_move_unread? I think that would make sense as a default
