### ISSUE TITLE
searches match excluded tags

### ISSUE THREAD

**Issue by krobelus** [pazz/alot#707]
In my .notmuch-config I have these two lines
[search]
exclude_tags=deleted;spam;

I tagged some messages as "deleted", but a generic search (*) still shows those messages. They do not show when using the emacs frontend or `notmuch search \*`

**Comment by bremner** [comment]
I commented on the pull request, but I don't know who gets those comments. There is no need to hand craft a query to emulate the excluded tag functionality, it's available in the library and the python bindings.
