### ISSUE TITLE
maximum recursion depth exceeded

### ISSUE THREAD

**Issue by mturquette** [pazz/alot#711]
I get the following error several times a day while browsing through long emails containing Linux kernel patches on the linux-kernel mailing list:

```
... [line below is repeated many times] ...
  File "/home/mturquette/.local/lib/python2.7/site-packages/alot/foreign/urwidtrees/tree.py", line 65, in _last_in_direction
    next_pos = direction(starting_pos)
  File "/home/mturquette/.local/lib/python2.7/site-packages/alot/foreign/urwidtrees/tree.py", line 244, in next_sibling_position
    return self._confirm_pos(pos[:-1] + (pos[-1] + 1,))
  File "/home/mturquette/.local/lib/python2.7/site-packages/alot/foreign/urwidtrees/tree.py", line 216, in _confirm_pos
    if self._get_node(self._treelist, pos) is not None:
  File "/home/mturquette/.local/lib/python2.7/site-packages/alot/foreign/urwidtrees/tree.py", line 208, in _get_node
    subtree = self._get_substructure(treelist, pos)
RuntimeError: maximum recursion depth exceeded
```

I cannot recall ever getting this error in any type of "normal" correspondence and my guess is that is has to do with the length of the message body, which can often exceed 2000 lines of text if it is a large patch/diff.

I typically page down or half page down when reading mail. Not sure if that has anything to do with it.

**Comment by cryptocrack** [comment]
I just stumbled upon this annoying bug. The fix seems to be pretty simple: Use an iterative version of _last_in_direction(). Hope that doesn't cause any unexpected side effects. I attached a patch, please let me know if you prefer a pull request.

```
From: Lukas Fleischer <info@cryptocrack.de>
Date: Sun, 1 Feb 2015 22:30:32 +0100
Subject: [PATCH] tree.py: Use a loop in _last_in_direction()

Convert the recursion in _last_in_direction() into a loop to avoid too
many nested functions calls.

Fixes issue #711.
---
 alot/foreign/urwidtrees/tree.py | 14 +++++++-------
 1 file changed, 7 insertions(+), 7 deletions(-)

diff --git a/alot/foreign/urwidtrees/tree.py b/alot/foreign/urwidtrees/tree.py
index 0058c17..6fa64f2 100644
--- a/alot/foreign/urwidtrees/tree.py
+++ b/alot/foreign/urwidtrees/tree.py
@@ -56,17 +56,17 @@ class Tree(object):
 
     def _last_in_direction(self, starting_pos, direction):
         """
-        recursively move in the tree in given direction
-        and return the last position.
+        move in the tree in given direction and return the last position.
 
         :param starting_pos: position to start at
         :param direction: callable that transforms a position into a position.
         """
-        next_pos = direction(starting_pos)
-        if next_pos is None:
-            return starting_pos
-        else:
-            return self._last_in_direction(next_pos, direction)
+        cur_pos = None
+        next_pos = starting_pos
+        while next_pos is not None:
+            cur_pos = next_pos
+            next_pos = direction(cur_pos)
+        return cur_pos
 
     def depth(self, pos):
         """determine depth of node at pos"""
-- 
2.2.2
```

**Comment by pazz** [comment]
do you have a (publicly available) testcase? maybe as mailbox/maildir to reproduce this?

@cryptocrack thanks for the patch. could you send me a pullrequest for this [here](https://github.com/pazz/urwidtrees)? I'd be very happy to push this once someone can confirm it works. I'm not particularly proud of the urwidtrees logic.

**Comment by cryptocrack** [comment]
Done. I guess you can simply import any thread with a lot of replies (several hundred should work). Unfortunately, I do not have the time to prepare such a test case now, though. FWIW, I tested this on a couple of threads that triggered the bug and it works fine now. I have been using the patched version for almost a week now without noticing any glitches.

**Comment by pazz** [comment]
great! no problem about the test case. I pushed your pr to urwidtrees.master
and also to alot's testing branch for now.
(my plan is to properly separate those two projects in the next alot release)
@mturquette : can you report back if this fixes the issue for you?
Thanks!

**Comment by mturquette** [comment]
@pazz I'm traveling right now but I'll test it when I get home next week.

**Comment by mturquette** [comment]
This fixes the issue for me, so far as I can see. I tried on some failing threads and they no longer fail. I'll create a new issue if I get the same error in the future. Thanks!

**Comment by lfos** [comment]
I guess this can be closed now?

**Comment by pazz** [comment]
yes, thanks

**Comment by mturquette** [comment]
Using the fix I still occasionally get the error. I can't say if the hit
rate is lower than it used to be or not.

**Comment by pazz** [comment]
@mturquette feel free to re-open the issue when you have some reproducible example
