### ISSUE TITLE
Select all mails from a search

### ISSUE THREAD

**Issue by teto** [pazz/alot#726]
Hi,

I've done a search to select all mails sent by cron and I want to mark all of them as killed, preferrably in a vim way (like "ggdG" or "Shift+V dd"). Is it already possible (could not find it via the help) ? otherwise what course of action would you advise me ?

**Comment by varac** [comment]
This works for simple operations like adding only one tag. What I'd like to have is to select all mails in a buffer/search, and use a pre-defined key binding that would apply all configurations assigned to it like it would do on a single mail/thread.
