### ISSUE TITLE
use human readable names when opening attachments

### ISSUE THREAD

**Issue by cinghiopinghio** [pazz/alot#736]
Hi @pazz,

Great job.
While using it i found that when opening attached file, they open with random names from `/tmp` folder.
If I want to save it to disk I won't have suggestions on the original file name. 
It would be nice to open the attachment saving it to some temporary folder (for example `/tmp/alot-XXXXX`) with the original filename. Something as the following:

```diff
diff --git a/alot/commands/thread.py b/alot/commands/thread.py
index ca73c75..92e3b6b 100644
--- a/alot/commands/thread.py
+++ b/alot/commands/thread.py
@@ -887,12 +887,12 @@ class OpenAttachmentCommand(Command):
             # in case the mailcap defined command contains no '%s',
             # we pipe the files content to the handling command via stdin
             if '%s' in handler_raw_commandstring:
-                nametemplate = entry.get('nametemplate', '%s')
-                prefix, suffix = parse_mailcap_nametemplate(nametemplate)
-                tmpfile = tempfile.NamedTemporaryFile(delete=False,
-                                                      prefix=prefix,
-                                                      suffix=suffix)
 
+                filename = self.attachment.get_filename()
+                # this prevents filename to be splitted in commandlist
+                filename = filename.replace(' ','_')
+                tmpdir = tempfile.mkdtemp(prefix='alot-')
+                tmpfile = open(tmpdir+'/'+filename,'w')
                 tempfile_name = tmpfile.name
                 self.attachment.write(tmpfile)
                 tmpfile.close()
```

This btw left a bunch of empty `/tmp/alot-XXXX` folders around (I can live with it, but probably is not desirable). The solution would be to make such temporary folder when alot starts and taking care to remove it when exiting.

What do you think?

**Comment by cinghiopinghio** [comment]
I'm back to this issue after quite some time.
I'm insisting on this because:

* a nice readable name help me remember what I'm doing (for example while reviewing many files attached to a single email
* the extension helps tools like `xdg-open` in the case of strange files like `docx`

I've written a initial working solution (it's in `human-readable-filenames` branch in my fork).
Its a bit crude.

Here what it does: it take `prefix` and `suffix` from the mailcap (as before) and `head` and `ext` from the filename and return `prefix+head` and either `suffix` or `ext` as respectively prefix and suffix to `NamedTemporaryFile`.

what should I do? should I make a pull request from my branch?
what's your thoughts?

I still prefer to make a new temporary folder an put there a [sanitized] file without those weird looking random strings.

**Comment by lamarpavel** [comment]
How about making the choice a user setting? That way I could set it to randomized names if I'm security conscious while you can set it to clear names for convenience.

Alternatively, only use clear names for mails/attachments that weren't encrypted.

In any case the file (and folder) should be written with permission `rwx------` if it's in `/tmp`.

**Comment by pazz** [comment]
i like your patch and am not totally opposed to temporary directories as long as they get automatically removed at some point. I'm not sure i understand your second point about the extension helping xdg-open but sure... feel free to send a PR (that applies to the master branch).
You might want to make the filename sanitization optional or configurable.
One way to do this is to add a hook - a user definable function that translates strings.
This function can default to the identity, i.e. do nothing.

**Comment by cinghiopinghio** [comment]
Sorry for the long silence...

Finally I added a hook that ask for two strings: `prefix` and `suffix` to pass to `tempfile.NamedTemporaryFile`.

If you like it as is, I'll try to edit also the docs to reflect this change (I'll have to figure out how to edit them BTW).

**Comment by pazz** [comment]
sorry where can i see this? Did you send a separate PR that I don't see atm?

**Comment by cinghiopinghio** [comment]
I've sent a PR #811 to `master`. Hope I've done right.

This is the least intrusive and more conservative way... I guess
