### ISSUE TITLE
automatically sign reply to signed emails

### ISSUE THREAD

**Issue by josch** [pazz/alot#741]
Hi,

I don't have a patch yet so I'll fille this to not loose track of the issue.

When replying to an email that was signed, then I usually want to sign my reply as well. To not forget to sign my reply, it would be great if it was configurable that replies to signed emails would be signed as well.

**Comment by lucc** [comment]
@josh Is this covered by the `sign_by_default` option (which currently supports `True` and `False`) or do you want to propose another option/value?

**Comment by josch** [comment]
I personally use the `sign_by_default` option, so for my own use case there is no bug anymore.
