### ISSUE TITLE
automatically encrypt replies to encrypted emails

### ISSUE THREAD

**Issue by tgirod** [pazz/alot#743]
In the same spirit as #741, I think it is nice to automatically encrypt replies to encrypted mails.

**Comment by freuk** [comment]
Indeed! I looked into writing a hook for this, but I'm not familiar enough with the source to do that without a free day before me.
That would be a very nice feature..

**Comment by meskio** [comment]
I did open an issue some years ago about that #661, and even sent a pull-req #675. Sadly I didn't have time to fix my patch to get it commited. I was hoping to get back and try to fix my pull-req.

**Comment by lamarpavel** [comment]
It looks like this can be closed since #774 has been merged into master.

**Comment by pazz** [comment]
cheers
