### ISSUE TITLE
Support 'next message or thread' command in thread buffers

### ISSUE THREAD

**Issue by elehack** [pazz/alot#748]
I'm coming from Mutt, and finding myself missing a number of pieces of my workflow. In general, alot seems to be working pretty well, but there are some impedances.

One is the ability to quickly read mail by going to the next (unread?) message after reading a message. I've looked at the alot code, though, and unfortunately it seems that this feature does not fit very well with the design of alot's buffers.

So I would propose the following as a potential design, based on my short foray into the code to see how this feature might be implementable:

- A thread buffer knows the search results it came from (pointer to buffer + position, or list of thread IDs + position).
- A thread buffer can go to the next thread in the search from which it was created. The resulting thread buffer is created just as if the user had gone back to the search results, gone down a thread, and opened it.
- Alternative way of conceiving of it: the thread buffer knows its creating search buffer, and if that buffer is still open, the thread can ask it to open the next message. Should probably be done by thread ID rather than position, in case the search has been refreshed, but in such a way that marking a message as read doesn't keep it from having a 'next message' capability when it was opened from an 'unread' search. This shouldn't be a problem since search buffers don't auto-refresh based on thread buffer tag changes, but needs to be considered.

**Comment by elehack** [comment]
Somehow I missed that bindings can be sequence of commands. That would let me have a 'jump to next thread' as a separate key.

Ultimately, I'd like to have a key that goes to the next message in the thread, if there is such a message, and on the last message goes to the next thread. Possibly only navigating messages that match the starting query (or open messages, for simplicity). But that seems to be a relatively invasive change.

**Comment by pazz** [comment]
i hear you. But you could script all that in python, writing a hook that does this and then bind it to a key via `call hookname`..
