### ISSUE TITLE
Display common tags in thread

### ISSUE THREAD

**Issue by elehack** [pazz/alot#750]
Right now, the thread view only displays 'unique' tags on messages (tags that are not applied to all messages in the thread).

I would like to be able to see, somewhere, the tags that apply to the thread. Perhaps a substitutable element in the thread statusbar?

**Comment by pazz** [comment]
see https://github.com/pazz/alot/issues/735
I think this is even pushed to testing already if im not mistaken..

**Comment by elehack** [comment]
Thanks. A quick search of the `testing` sources (`ag intersection_tags`) doesn't reveal it.

**Comment by pazz** [comment]
It's true. This should be documented better!
