### ISSUE TITLE
alot ignores 256 colourmode setting

### ISSUE THREAD

**Issue by Cutuchiqueno** [pazz/alot#751]
I can not get 256 colors to work with alot.
```
Theme file mutt failed validation:
key "focus" in section "search, threadline" failed validation: foreground/background (u'black'/u'#00d') require more colors than have been specified (16)
```

```
$ tput colors
256
```

```
$ echo $TERM
rxvt-unicode-256color
```

in alot config
`colourmode = 256`

also tried
`$ alot -C 256`

my shell is the zshell, but happens also with bash

I use the curren git master brunch version.

any ideas?

**Comment by pazz** [comment]
It could be an urwid problem. How do you know it doesn't work?
Have you tried the (urwid) colour_picker.py in alot/extra/ ?

I'm using rxvt-unicode-256color myself and it works as expected for me. Are you
behind a screen or so?

**Comment by Cutuchiqueno** [comment]
thx, for responding so quickly.

yes, the colour_picker provided by urwid/alot shows all the 256 colors. Thus, I think the terminal environment is set up correctly. It's just that alot thinks I set up 16 colors (looking at the error message at the top of my last post. Don't beconfused by the name of the theme file mutt, it's not the default one, I changed it heavily)

I don't use tmux or screen.

**Comment by Cutuchiqueno** [comment]
ok, shame on me. This one was really my fault. I misinterpreted the way different colors are set for 2,88,256 color depths.

**Comment by Cybolic** [comment]
I'm dealing with the same issue - what was your solution @Cutuchiqueno ?
