### ISSUE TITLE
How to get current thread/message from a hook?

### ISSUE THREAD

**Issue by cro** [pazz/alot#759]
I'm investigating different ways that labels can be round-tripped from Gmail through offlineimap into notmuch, manipulated in alot, and synced via offlineimap back to Gmail.  The first attempt involves writing a post-retag hook, but I'm not sure how to get the current message or thread that is being operated on via the hook.  Can someone enlighten me?  

(sorry for posting this in an issue. Is there an active mailing list?)

**Comment by pazz** [comment]
hey cro,

there are some example hooks in the github wiki:
https://github.com/pazz/alot/wiki/Contrib-Hooks

Basically, your hook gets a `alot.ui.UI` object as parameter. So you get the current `Buffer`
as `ui.current_buffer`.
If that is a Threadbuffer, you can get the selected message using
```
ui.current_buffer.get_selected_message()
```
and from search buffers you get the highlighted thread as using `get_selected_thread()`.
I hope this helps. If you find a nice way to synchronize gmail tags with notmuch this way
please document it. I gave up on that :)

**Comment by cro** [comment]
Thanks Patrick. That is helpful!

> I hope this helps. If you find a nice way to synchronize gmail tags with
> notmuch this way
> please document it. I gave up on that :)
>
 I've been through this with Sup, and gave up there. I was excited to find
alot, I much prefer Python.

>

-- 
--cro
