### ISSUE TITLE
nottoomuch-addresses.sh conflicts with testing 2c29bf7ea9f968874c4bb54b31a7c7b95a4fd0a0

### ISSUE THREAD

**Issue by bjoernb** [pazz/alot#764]
When calling nottoomuch-addresses.sh in alot it crashes.

From ~/.config/alot/config:

	[[[abook]]]
	type = shellcommand
	command = nottoomuch-addresses.sh
	regexp = \"(?P<name>.+)\"\s*<(?P<email>.*.+?@.+?)>

Here is the traceback:

	Traceback (most recent call last):
	  File "/home/bb/.local/bin/alot", line 9, in <module>
	    load_entry_point('alot==0.3.6-', 'console_scripts', 'alot')()
	  File "/home/bb/.local/stow/alot/lib/python2.7/site-packages/alot-0.3.6_-py2.7.egg/alot/init.py", line 186, in main
	    UI(dbman, cmdstring)
	  File "/home/bb/.local/stow/alot/lib/python2.7/site-packages/alot-0.3.6_-py2.7.egg/alot/ui.py", line 87, in __init__
	    self.mainloop.run()
	  File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 274, in run
	    self.screen.run_wrapper(self._run)
	  File "/usr/lib/python2.7/dist-packages/urwid/raw_display.py", line 268, in run_wrapper
	    return fn()
	  File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 339, in _run
	    self.event_loop.run()
	  File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 1183, in wrapper
	    rval = f(*args,**kargs)
	  File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 390, in _update
	    self.process_input(keys)
	  File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 490, in process_input
	    k = self._topmost_widget.keypress(self.screen_size, k)
	  File "/usr/lib/python2.7/dist-packages/urwid/container.py", line 588, in keypress
	    *self.calculate_padding_filler(size, True)), key)
	  File "/usr/lib/python2.7/dist-packages/urwid/container.py", line 2265, in keypress
	    key = w.keypress((mc,) + size[1:], key)
	  File "/home/bb/.local/stow/alot/lib/python2.7/site-packages/alot-0.3.6_-py2.7.egg/alot/widgets/globals.py", line 141, in keypress
	    self.edit_pos)
	  File "/home/bb/.local/stow/alot/lib/python2.7/site-packages/alot-0.3.6_-py2.7.egg/alot/completion.py", line 111, in complete
	    for c, p in self._completer.complete(mypart, mypos):
	  File "/home/bb/.local/stow/alot/lib/python2.7/site-packages/alot-0.3.6_-py2.7.egg/alot/completion.py", line 219, in complete
	    res = res + abook.lookup(prefix)
	  File "/home/bb/.local/stow/alot/lib/python2.7/site-packages/alot-0.3.6_-py2.7.egg/alot/addressbook/external.py", line 44, in lookup
	    return self._call_and_parse(self.commandline + " " + prefix)
	  File "/home/bb/.local/stow/alot/lib/python2.7/site-packages/alot-0.3.6_-py2.7.egg/alot/addressbook/external.py", line 63, in _call_and_parse
	    m = re.match(self.regex, l, self.reflags)
	  File "/usr/lib/python2.7/re.py", line 141, in match
	    return _compile(pattern, flags).match(string)
	  File "/usr/lib/python2.7/re.py", line 233, in _compile
	    bypass_cache = flags & DEBUG
	TypeError: unsupported operand type(s) for &: 'NoneType' and 'int'

Here is the debug output:

	DEBUG:manager:unable to load hooks file:/home/bb/.config/alot/hooks.py
	DEBUG:manager:/home/bb/.config/alot/themes
	DEBUG:manager:abook defined: {u'type': u'shellcommand', u'command': u'nottoomuch-addresses.sh', u'regexp': u'\\"(?P<name>.+)\\"\\s*<(?P<email>.*.+?@.+?)>', 'ignorecase': True, 'abook_contacts_file': '~/.abook/addressbook', 'shellcommand_external_lookups': True}
	DEBUG:manager:abook defined: {u'type': u'shellcommand', u'command': u'nottoomuch-addresses.sh', u'regexp': u'\\"(?P<name>.+)\\"\\s*<(?P<email>.*.+?@.+?)>', 'ignorecase': True, 'abook_contacts_file': '~/.abook/addressbook', 'shellcommand_external_lookups': True}
	DEBUG:manager:abook defined: {u'type': u'shellcommand', u'command': u'nottoomuch-addresses.sh', u'regexp': u'\\"(?P<name>.+)\\"\\s*<(?P<email>.*.+?@.+?)>', 'ignorecase': True, 'abook_contacts_file': '~/.abook/addressbook', 'shellcommand_external_lookups': True}
	DEBUG:manager:abook defined: {u'type': u'shellcommand', u'command': u'nottoomuch-addresses.sh', u'regexp': u'\\"(?P<name>.+)\\"\\s*<(?P<email>.*.+?@.+?)>', 'ignorecase': True, 'abook_contacts_file': '~/.abook/addressbook', 'shellcommand_external_lookups': True}
	DEBUG:manager:abook defined: {u'type': u'shellcommand', u'command': u'nottoomuch-addresses.sh', u'regexp': u'\\"(?P<name>.+)\\"\\s*<(?P<email>.*.+?@.+?)>', 'ignorecase': True, 'abook_contacts_file': '~/.abook/addressbook', 'shellcommand_external_lookups': True}
	DEBUG:manager:abook defined: {u'type': u'shellcommand', u'command': u'nottoomuch-addresses.sh', u'regexp': u'\\"(?P<name>.+)\\"\\s*<(?P<email>.*.+?@.+?)>', 'ignorecase': True, 'abook_contacts_file': '~/.abook/addressbook', 'shellcommand_external_lookups': True}
	INFO:ui:setup gui in 256 colours
	DEBUG:ui:fire first command
	DEBUG:ui:global command string: "search tag:inbox AND NOT tag:killed AND NOT tag:draft AND NOT tag:work AND NOT tag:something"
	DEBUG:__init__:mode:global got commandline "search tag:inbox AND NOT tag:killed AND NOT tag:draft AND NOT tag:work AND NOT tag:something"
	DEBUG:__init__:ARGS: [u'search', u'tag:inbox', u'AND', u'NOT', u'tag:killed', u'AND', u'NOT', u'tag:draft', u'AND', u'NOT', u'tag:work', u'AND', u'NOT', u'tag:something']
	DEBUG:__init__:cmd parms {'sort': None, 'query': [u'tag:inbox', u'AND', u'NOT', u'tag:killed', u'AND', u'NOT', u'tag:draft', u'AND', u'NOT', u'tag:work', u'AND', u'NOT', u'tag:something']}
	DEBUG:manager:Worker process 26668 spawned
	DEBUG:walker:EMPTY PIPE
	DEBUG:manager:Worker process 26668 exited successfully
	DEBUG:ui:Got key (['m'], [109])
	DEBUG:ui:cmdline: 'compose'
	DEBUG:ui:search command string: "compose"
	DEBUG:__init__:mode:search got commandline "compose"
	DEBUG:__init__:ARGS: [u'compose']
	DEBUG:__init__:cmd parms {'spawn': None, 'sender': None, 'attach': None, 'cc': None, 'omit_signature': False, 'rest': [], 'bcc': None, 'to': None, 'template': None, 'subject': None}
	DEBUG:envelope:TEMPLATE: None
	DEBUG:ui:Got key (['tab'], [9])
	DEBUG:ui:Got key (['tab'], [9])
	DEBUG:ui:Got key (['tab'], [9])
	DEBUG:ui:Got key (['tab'], [9])
	DEBUG:ui:Got key (['enter'], [10])
	DEBUG:globals:True
	DEBUG:globals:[<alot.addressbook.external.ExternalAddressbook object at 0x7f1b99e90e10>, <alot.addressbook.external.ExternalAddressbook object at 0x7f1b99ef8410>, <alot.addressbook.external.ExternalAddressbook object at 0x7f1b99ef8a50>, <alot.addressbook.external.ExternalAddressbook object at 0x7f1b99e90d10>, <alot.addressbook.external.ExternalAddressbook object at 0x7f1b99e90d90>, <alot.addressbook.external.ExternalAddressbook object at 0x7f1b99e90e90>]
	DEBUG:ui:Got key (['p'], [112])
	DEBUG:ui:Got key (['a'], [97])
	DEBUG:ui:Got key (['z'], [122])
	DEBUG:ui:Got key (['z'], [122])
	DEBUG:ui:Got key (['tab'], [9])

**Comment by pazz** [comment]
thanks. actually, i cannot reproduce this: could you try setting the `reflags=None`
in `alot/addressbook/external` line 14 to `reflags=0` and see if it helps?

**Comment by bjoernb** [comment]
Hi Pazz,

Quoting Patrick Totzke (2015-04-15 12:13:39)
> in alot/addressbook/external line 14 to reflags=0 and see if it helps?

this is a patch that works.

Greetings,
bjoernb.

**Comment by pazz** [comment]
i could reproduce it after all: in the testing branch, but not the feature branch. Strange, but hey :)
Check out the new testing branch and note also that i renamed the new config option
to `shellcommand_external_filtering` (needs to be `False` if you use `notmuch address`)
