### ISSUE TITLE
Ability to use GPG-agent through forwarded Unix Domain Socket

### ISSUE THREAD

**Issue by MacGyverNL** [pazz/alot#768]
I use alot on a remote host (because of Windows and the headaches of syncing a tag database etc), but I'd like to be able to not throw my GPG key on there. Now I know there are solutions like using subkeys, but they seem sub-optimal in as much as you can still take them over and use them until I've revoked them.

What I'd like to be able to do is use SSH Unix Domain Socket forwarding to use the agent on my local machine, rather than on the remote host (SSH has native support for this since 6.7, try e.g. ssh -R/home/remoteuser/.gnupg/S.gpg-agent:/home/localuser/.gnupg/S.gpg-agent). However, alot doesn't seem to pick up on this and just trows "(7, 54, u'Unusable secret key')" at me.

Note that I'm running gpg-agent 2.1.4, so the whole GPG_AGENT_INFO env variable is no longer relevant, the socket must live at /home/user/.gnupg/S.gpg-agent.

Also, maybe this happens because it's only since gnupg 2.1 that all secret key operations can happen in the agent and alot doesn't use those mechanisms (yet)?

**Comment by pazz** [comment]
Hi! interesting use case :)

alot itself does all the gnupg related stuff through gpgme's python bindings.
I suspect this is an issue with gpgme and you'll find some support
on their mailinglist/bugtracker/irc chan:
https://www.gnupg.org/documentation/mailing-lists.html

**Comment by MacGyverNL** [comment]
Turns out it was my setup of gpg-agent-forwarding that wasn't working yet; for this setup you still need a full copy of the keyring + trustdb without your secret keys. This does exactly what I want now, there doesn't seem to be any issue with alot. Apologies for the confusion.
