### ISSUE TITLE
Prefer matching "To:", "CC:", "From:" over "Delivered-To:" when selecting sender address.

### ISSUE THREAD

**Issue by MacGyverNL** [pazz/alot#771]
I have one mailbox where a number of different addresses are delivered. Some of these addresses I use to send mail with, and they are listed as accounts in the config. However, in the end, all mail carries a Delivered-To header for the "main" account, which is listed at the top of the config file. Because it seems to pick the top account, many replies I start formatting start out with the "wrong" sender address. Changing the order of the accounts in the config file, moving this account entirely to the bottom, seems to fix the problem. But I consider some headers more valuable than others in determining where a reply should come from, so it might be worth considering changing this behaviour.

**Comment by pazz** [comment]
Hi!
I'm not sure what exactly you're proposing here, but go ahead and send a
pull request (doesn't have to be perfect the first time) to get the discussion
going..

**Comment by josch** [comment]
I'm in the exact same situation as @MacGyverNL and was about to file a bug for this but was extremely pleased to not only already find a bug about this issue but also a patch which is even merged already! Thanks alot (pun intended) @pazz and @MacGyverNL !!

**Comment by josch** [comment]
Note for my future self: applying the commit 34537d8323767281c0e9a5537de9faa12fc4be0e from @MacGyverNL's fork requires application of commit b70d1e1790a163aa92f6259a586ff61baf879458 from the same fork first.

**Comment by MacGyverNL** [comment]
Note that I recently rebased that on top of testing so I could start running on the testing-branch. I spoke with @pazz on IRC and he prefers pull requests based on master, so in the near future I'll rebase it on master again and provide a merge-commit with testing instead, so that you shouldn't have to apply b70d1e1 if you're running master.

**Comment by lucc** [comment]
I assume this is done, please reopen if not.
