### ISSUE TITLE
Comparing alot vs other Notmuch-based MUAs, including mutt-kz

### ISSUE THREAD

**Issue by johnnyutahh** [pazz/alot#776]
Can the alot community comment on my [initial comparisons with other Notmuch-based MUAs, namely mutt-kz](https://github.com/johnnyutahh/search-based-email#MUA_choice)?

https://github.com/johnnyutahh/search-based-email#MUA_choice

I haven't revisited the alot resources (github, software, etc) since April/May 2015 timeframe, so if there's been significant changes since, I've not seem them.

Feedback on the rest of my questions in the above document are welcome.

**Comment by pazz** [comment]
Hi and welcome to alot!
I think you're right that an example config could help newcommers.
I am a little surprized to hear about alot's "sparse" documentation compared to muttrc.
Does muttrc have more than a RADME? Are you aware of alot.rtfd.org?
You might find [the config section](http://alot.readthedocs.org/en/latest/configuration/index.html) useful.. Have fun,
/p

**Comment by johnnyutahh** [comment]
Hi Patrick,

Thanks for the welcome. mutt and mutt-kz have several rich, diverse, and 
example-config references. Here's some of the better ones I've found 
thus far:

https://github.com/johnnyutahh/search-based-email#mutt-kz-applicable-configuration

And yes, I am (and was) familiar with alot.rtfd.org, including the 
config section. However, the easiest uptake for a user like me is to 
provide examples, workflows, user scenarios, etc--things like above--and 
_then_ read the "reference manual" like alot.rtfd.org (currently) to 
figure out any details I couldn't figure out from the examples, 
workflow, scenario docs.

Here's an analogy: it's hard to build a house with just carpentry tools 
like a hammer and saw (unless I've previously built the same or similar 
house). It's much easier if I can see a blueprint, design, and/or 
example of another house. My experience (which frankly might be just 
wrong--I'm still learning and investigating) is that alot.rtfd.org 
provides the carpentry tools, but I have no other examples, or designs, 
or recommendations like I'd get from a blueprint or an example house. I 
have to figure out all the latter by myself. And that's much harder. And 
currently an impediment for me trying to master alot.

Is this possibly an unfair analogy? Sure. But for better or worse, it's 
my current experience. I'd be very happy to discover stuff I've not yet 
seen, and/or get a better understanding of alot.rtfd.com or other, 
existing docs.

Amplifying the above problem is that, while I do have programming and 
cmdline-usage, and "text-y" skills and experience, I haven't employed 
these kinds of programming/cmdline/text-y approaches (at least, not 
recently) to MUAs/email usage. So I might be learning much more than 
just 'alot'.  And because of all this, alot feels like too daunting a 
learning curve. My current plan is to start trying/using mutt-kz, and 
then maybe try alot later. Do you have any alternative suggestions?

More on my usage background, requirements, and cmdline-based-email 
learning challenges here:
https://github.com/johnnyutahh/search-based-email

Does this all make sense?

**Comment by pazz** [comment]
Hi again,
I did not use mutt for too long until I wrote alot, so I cannot really compare them in terms of user friendliness. At the time, muttkz was not available and when I tried it, I had a hard time getting into it.
Anyhow, good luck with muttkz. If you do try alot later, I welcome you to write about the exact
problems you run into etc. It's always good to improve upon the docs :)

**Comment by geier** [comment]
@johnnyutahh I believe alot is not that hard to get into. If you don't know the commands yet press `?` for a scrollable list of commands (while in alot). Until I found someone's alot config a messed up when trying to write my own config, especially with the bindings. If you need a simpler example, you might want to have a look [at mine](https://github.com/geier/dotfiles/blob/master/.config/alot/config) and e.g. [offlineimaprc](https://github.com/geier/dotfiles/blob/master/.offlineimaprc) for the post sync workflow.

But looking through pazz config I realise I'm currently missing out on some nice automation possibilities.

**Comment by pazz** [comment]
Quoting Christian Geier (2015-07-15 20:38:38)
>    But looking through pazz config I realise I'm currently missing out on
>    some nice automation possibilities.

FTR: my config on github was way outdated. I pushed my current config if you
want to have a peek. It is full of commented out stuff that was introduced
to test features i'm not using myself :)

**Comment by geier** [comment]
@pazz thank you! especially for hooks.github()

**Comment by johnnyutahh** [comment]
@geier @pazz -- all helpful feedback, thank you.

@pazz: is this the config mentioned above?
https://github.com/pazz/configs/blob/master/.config/alot/config

**Comment by lucc** [comment]
I will close this. If there are more specific ideas how to improve the docs you can open a new PR.
