### ISSUE TITLE
Encrypting results in Error on sending (GnuPG 2.1)

### ISSUE THREAD

**Issue by mdik** [pazz/alot#783]
Hi,

Debian unstable comes with gnupg 2.1 now and sending emails results in "(0, 1, u'General error')". Just Signing still works, though.

With logging enabled in "debug" detail, everything seems to work up until (including) signing the message and then it just ends.

```
DEBUG:ui:Got key (['y'], [121])
DEBUG:ui:cmdline: 'send'
DEBUG:ui:envelope command string: "send"
DEBUG:__init__:mode:envelope got commandline "send"
DEBUG:__init__:ARGS: [u'send']
DEBUG:__init__:cmd parms {}
DEBUG:envelope:signing plaintext: Content-Type: text/plain; charset="utf-8"

[ the signed message itself ]
```

Any ideas on how to debug further?

**Comment by lucc** [comment]
Sorry for the late answer. I can sign and send emails just fine with recent alot master and gpg 2.1.22. I am on Arch Linux though.

Is bug still happening on your end?

**Comment by dcbaker** [comment]
I can't replicate this on master and the bug is quite old, feel free to re-open if you can still reproduce the bug.

**Comment by mdik** [comment]
I switched to mutt a while ago, sorry. But thank you for the follow-up!
