### ISSUE TITLE
SIGUSR1 for refresh

### ISSUE THREAD

**Issue by jreinert** [pazz/alot#786]
this is a feature request:

trigger a refresh of alot with SIGUSR1. so after a sync one could trigger it and automatically refresh alot

**Comment by TomasTomecek** [comment]
+1

**Comment by i7c** [comment]
+1

**Comment by mpnordland** [comment]
I have this working on my end, I'll send a pull request once I've made sure the formatting is correct.

**Comment by mpnordland** [comment]
fixed in pull request #833 . The pull request was merged and so this should be in the next release.

**Comment by pazz** [comment]
ah yes, I'll close this issue then. thanks
