### ISSUE TITLE
GPG tab completion delays the prompt.

### ISSUE THREAD

**Issue by Stebalien** [pazz/alot#790]
Most of the UI is pretty snappy but displaying a prompt (':') and any commands that use prompts prompt, retagprompt, etc...) are really slow (~1.5s). Interestingly, prompting for the to/from addresses when sending an email is really fast.

**Comment by pazz** [comment]
I cannot reproduce this and would need more info here

**Comment by Stebalien** [comment]
It appears to be my mail. Running notmuch as a new user doesn't reproduce the bug unless I import my mail. Is alot performing a really expensive query when opening the prompt box? I'm guessing this has something to do with tab completion. Is there any way to turn this off?

BTW, I have 24,000 emails.

**Comment by Stebalien** [comment]
I spoke too soon. Importing my mail doesn't cause the issue. I'm trying to check my config now (it may be a disk read issue because I'm testing from tmpfs (but my real mail is on my ssd) but it shouldn't be).

**Comment by Stebalien** [comment]
Found it! It's my gnupg public keyring (16MB). It shouldn't be iterating through every single key up front.

**Comment by pazz** [comment]
OK, so maybe there should be an option to disable or at least postpone
the creation of a `CryptoKeyCompleter` until it is actually used (when selecting a recipients key).

**Comment by Stebalien** [comment]
You can also cache the list or provide a hint to `ctx.keylist`

**Comment by lucc** [comment]
Is this fixed by #1066?

**Comment by dcbaker** [comment]
I think this is @lucc. I'm going to close it, but feel free to reopen if it's not.
