### ISSUE TITLE
custom mailcap path

### ISSUE THREAD

**Issue by boyska** [pazz/alot#791]
Having a custom mailcap is useful for me, so that I can keep (multiple) mail configurations separated.
It is therefore important for https://github.com/boyska/mailbundle
In mutt this is easy (`set mailcap_path`) but I cannot find a way to do this in alot

**Comment by pazz** [comment]
Actually, I think this is a really marginal use case. I'm not aware of
any software that has a switch to pass on a custom mailcap path.
However, since alot uses some lib to get mailcap info, you might be lucky
and that lib interprets, like mutt, the MAILCAP environment variable.

**Comment by boyska** [comment]
Reading the code, I discovered that the `mailcap` python module understands `MAILCAPS` environment variable, which is good news!
