### ISSUE TITLE
Keep the line selected on refresh (search mode)

### ISSUE THREAD

**Issue by GuillaumeSeren** [pazz/alot#792]
Hi there,
I used alot to read my mails and I find it awesome !

But when I refresh a buffer with '@' I would like the selection to stay the same, can you think it can be done ?

Thank's,
Guillaume.

**Comment by pazz** [comment]
IIRC, this was difficult since the refresh command completely rebuilds the widget tree.
On could remember the index (some reference object in the tree) that is focussed; rebuild and hope that the new tree has an equally named reference point. But It might not, for instance if a mail was removed and notmuch new was called..

**Comment by GuillaumeSeren** [comment]
@pazz 
Yes I think we can save the message id from the notmuch database, then if it is still in the result of the actual query select it.

I will check that, thank you for feedback.

**Comment by pazz** [comment]
I think you want to use the get/set_focus methods of the TreeBox
https://github.com/pazz/alot/blob/master/alot/buffers.py#L373
see also http://urwidtrees.readthedocs.org/en/latest/containers.html for the docs.
Maybe it is actually overkill to replace the TreeBox and the ThreadTree here.
How about adding a refresh() method in the ThreadTree ? I'm just not so sure
if changing these trees will actually trigger urwid to redraw the display

**Comment by kirelagin** [comment]
Upvoting this. My use-case is that I have a command running in the background that sync mail every now and then, and when it’s done it sends SIGUSR1 to all `alot` processes so that they pick up the changes.

**Comment by GuillaumeSeren** [comment]
Hey @kirelagin 
actually I use this hook function who does the job https://github.com/pazz/alot/wiki/Contrib-Hooks#save-marked-position-in-search-buffer

Maybe we can close this issue, as it is well covered in the wiki https://github.com/pazz/alot/wiki
