### ISSUE TITLE
Proposal: Catch all hooks

### ISSUE THREAD

**Issue by lucc** [pazz/alot#797]
I try to update a awesome mail notification widget when I exit alot.

My first idea was to use some exit hook, but there is only a hook for the exit command and that is not triggered when I use the config option `quit_on_last_bclose`.

At the moment I have a working solution that installs a bclose hook for every mode:
```python
import subprocess

def pre_search_bclose(ui, **kwargs): bclose_wrapper(ui)
def pre_thread_bclose(ui, **kwargs): bclose_wrapper(ui)
def pre_global_bclose(ui, **kwargs): bclose_wrapper(ui)
def pre_envelope_bclose(ui, **kwargs): bclose_wrapper(ui)
def pre_taglist_bclose(ui, **kwargs): bclose_wrapper(ui)
def pre_bufferlist_bclose(ui, **kwargs): bclose_wrapper(ui)

def bclose_wrapper(ui):
    if len(ui.buffers) == 1:
        update_awesome_mail_widget()

def update_awesome_mail_widget():
    p = subprocess.Popen(['awesome-client'], stdin=subprocess.PIPE)
    p.communicate(
        'require("vicious").force({require("widgets/notmuch").widget})')
```
In my opinion this is a unnecessary complication. So the question and proposal is this:

1. Introduce some general exit hook that is agnostic of the reason of the exit. Maybe `pre_teardown`, `post_teardown`, `exit_cleanup`, `exit` or something similar. (I was expecting some hook like this to already exist because of the presence of the `quit_on_last_bclose` option.)
2. Introduce mode agnostic hooks that are run for a special command, whichever mode it was fired from. They could be called `pre_any_COMMAND` and `post_any_COMMAND` or `pre_COMMAND` and `post_COMMAND`.

**Comment by pazz** [comment]
yes, i agree with both suggestions. These kind of hooks would be welcome.

**Comment by lucc** [comment]
In the mean time I found that `pre_global_bclose` can be used to simplify my example:
```python
import subprocess

def pre_global_bclose(ui, **kwargs):
    if len(ui.buffers) == 1:
        update_awesome_mail_widget()

def update_awesome_mail_widget():
    p = subprocess.Popen(['awesome-client'], stdin=subprocess.PIPE)
    p.communicate(
        'require("vicious").force({require("widgets/notmuch").widget})')
```
But the `*_global_*` hooks are not well explained in the [hooks documentation](http://alot.readthedocs.org/en/latest/configuration/hooks.html). What is the exact meaning and do global hooks exist for all commands or only the commands listed in [global commands](http://alot.readthedocs.org/en/latest/usage/modes/global.html)?

**Comment by pazz** [comment]
You are right: I forgot about these "pre_global_*" hooks.
The relevant line is this:
  https://github.com/pazz/alot/blob/master/alot/commands/__init__.py#L205

So these global hooks can be defined for all commands,
and will be used as fallback if the more specific `pre/post_mode_command` is
undefined.
I hope this helps. Feel free to improve the docs and send a PR. Thanks.

**Comment by lucc** [comment]
I tried to implement a new exit hook like this:
```diff
diff --git a/alot/ui.py b/alot/ui.py
index e9624e5..4c7c800 100644
--- a/alot/ui.py
+++ b/alot/ui.py
@@ -318,6 +318,9 @@ class UI(object):
         except Exception as e:
             exit_msg = 'Could not stop reactor: {}.'.format(e)
             logging.error(exit_msg + '\nShutting down anyway..')
+        exit_hook = settings.get_hook('exit_cleanup_test')
+        if exit_hook is not None:
+            exit_hook()
 
     def buffer_open(self, buf):
         """register and focus new :class:`~alot.buffers.Buffer`."""
```
with this in `hooks.py`:
```python
def exit_cleanup_test():
    logging.debug('hans')
```
But I was not successful. What would be the right place and way to implement that?

**Comment by pazz** [comment]
it looks correct at first sight. Maybe `reactor.stop` calls `sys.exit` or something and then the remaining lines are ignored. Have you tried adding the hook call before the try?

**Comment by lucc** [comment]
I tried it but no change. I can call my hook manually with `:call hooks.exit_cleanup_test()`. I also tried to put some `logging.debug()` call before every `sys.exit()` call in the alot source. No result. It seems like the exit call is not made my alot directly but by some foreign module.

**Comment by lucc** [comment]
I found a place for the hook that works:
```diff
diff --git a/alot/init.py b/alot/init.py
index 4392809..0528d84 100755
--- a/alot/init.py
+++ b/alot/init.py
@@ -184,6 +184,9 @@ def main():
 
     # set up and start interface
     UI(dbman, cmdstring)
+    exit_hook = settings.get_hook('exit_cleanup_test')
+    if exit_hook is not None:
+        exit_hook()
 
 if __name__ == '__main__':
-    main()
\ No newline at end of file
+    main()
```
If we decide on a name, I can send a PR.

**Comment by lucc** [comment]
I have some ideas for the name of the new hook:
* `exit` (my favorite)
* `exit_cleanup`
* `final_cleanup`
* `cleanup`
* `final`
* `post_teardown`
What do you think?

**Comment by pazz** [comment]
I'm fine with `exit`. Thanks!
