### ISSUE TITLE
It's probably time to put out a release.

### ISSUE THREAD

**Issue by zenhack** [pazz/alot#810]
It's been well over a year since 0.3.6 came out. I'm running the release, and just tripped over #711, which was fixed in February. Probably about time to make a new release.

**Comment by pazz** [comment]
Quoting Ian Denhardt (2015-12-16 10:56:25)
>    It's been well over a year since 0.3.6 came out. I'm running the release,
>    and just tripped over [1]#711, which was fixed in February. Probably about
>    time to make a new release.

I agree.

**Comment by np** [comment]
Can this be closed now?

**Comment by pazz** [comment]
yes; thanks.
