### ISSUE TITLE
Make addresses in To header unique when group replying

### ISSUE THREAD

**Issue by josch** [pazz/alot#818]
Hi,

imagine an email with headers like this:

```
From: foo@bar.com
To: blub@bla.com, plim@blub.com
Reply-To: foo@bar.com, blub@bla.com
```

If I'd now hit reply-all for such an email, I'd get a message with the following To header:

```
foo@bar.com, blub@bla.com, plim@blub.com, foo@bar.com, blub@bla.com
```

As you can see, foo@bar.com and blub@bla.com are repeated. This is because there is no attempt at sending the list of addresses through a `sorted(set())` call but even with making such call, the addresses would not be unique-y-fied because they get pushed into the resulting list as groups of addresses and not as individual addresses.

The following patch sketches a possible solution:

``` patch
--- alot/commands/thread.py 2014-08-02 18:26:46.000000000 +0200
+++ alot/commands/thread.py.bak 2015-12-28 03:46:23.144234416 +0100
@@ -181,7 +184,7 @@
                 % recipients
             logging.debug(emsg)
         else:
-            recipients = [sender]
+            recipients = self.clear_my_address([], [sender])

         if self.groupreply:
             # make sure that our own address is not included
@@ -189,8 +192,8 @@
             MFT = mail.get_all('Mail-Followup-To', [])
             followupto = self.clear_my_address(my_addresses, MFT)
             if followupto and settings.get('honor_followup_to'):
-                logging.debug('honor followup to: %s', followupto)
-                recipients = [followupto]
+                logging.debug('honor followup to: %s', ', '.join(followupto))
+                recipients = followupto
                 # since Mail-Followup-To was set, ignore the Cc header
             else:
                 if sender != mail['From']:
@@ -200,15 +203,27 @@
                 if sender_address not in my_addresses:
                     cleared = self.clear_my_address(
                         my_addresses, mail.get_all('To', []))
-                    recipients.append(cleared)
+                    recipients.extend(cleared)

                 # copy cc for group-replies
                 if 'Cc' in mail:
                     cc = self.clear_my_address(
                         my_addresses, mail.get_all('Cc', []))
-                    envelope.add('Cc', decode_header(cc))
+                    envelope.add('Cc', decode_header(', '.join(cc)))

-        to = ', '.join(recipients)
+        def make_unique(value):
+            res = dict()
+            for name, address in getaddresses(value):
+                res[address] = name
+            new_value = []
+            for address, name in res.items():
+                if name != '':
+                    new_value.append('"%s" <%s>' % (name, address))
+                else:
+                    new_value.append(address)
+            return sorted(new_value)
+
+        to = ', '.join(make_unique(recipients))
         logging.debug('reply to: %s' % to)
         envelope.add('To', decode_header(to))

@@ -252,7 +267,7 @@
                     new_value.append('"%s" <%s>' % (name, address))
                 else:
                     new_value.append(address)
-        return ', '.join(new_value)
+        return new_value


 @registerCommand(MODE, 'forward', arguments=[
```

Firstly, the function `clear_my_address` now returns a list of addresses instead of already concatenating the addresses into a single string. Secondly, as I knew no better function, I used `clear_my_address` also to parse the value of `sender` in the beginning so that it would be a list of individual adresses instead of a list with only a single concatenated string of addresses. Thirdly I added a function which makes a list of addresses unique and sorts them. That it is done like that instead of the much simpler `sorted(set())` is partly due to that it might happen that different headers have addresses with the same email address but different names (which should be treated as the same address with an arbitrary real name) and partly because the quoting alot is doing which already messes this up by itself.

What do you think?

**Comment by pazz** [comment]
I like it. could you send a PR?
what's with the `append -> extend`/ is this py2 vs py3?
this `make_unique` is local? you could consider adding it to `alot.utils` or similar..

**Comment by josch** [comment]
Yes, I can make this a pull request.

    Python 2.7.10 (default, Sep 13 2015, 20:30:50) 
    [GCC 5.2.1 20150911] on linux2
    Type "help", "copyright", "credits" or "license" for more information.
    >>> l = [1,2,3]
    >>> l.append([4,5])
    >>> l
    [1, 2, 3, [4, 5]]
    >>> l.extend([4,5])
    >>> l
    [1, 2, 3, [4, 5], 4, 5]
    >>> 

Okay, I can add `make_unique` to `alot.utils`.

Since you didn't comment on it I guess that there doesn't yet exist a better way than using `clear_my_address` to parse a address string into a list?

**Comment by pazz** [comment]
Quoting josch (2016-01-04 07:51:36)
>    Yes, I can make this a pull request.
> 
>  Python 2.7.10 (default, Sep 13 2015, 20:30:50)
>  [GCC 5.2.1 20150911] on linux2
>  Type "help", "copyright", "credits" or "license" for more information.
>  >>> l = [1,2,3]
>  >>> l.append([4,5])
>  >>> l
>  [1, 2, 3, [4, 5]]
>  >>> l.extend([4,5])
>  >>> l
>  [1, 2, 3, [4, 5], 4, 5]
>  >>>

thanks! I used `+` here mostly
> 
>    Okay, I can add make_unique to alot.utils.

How about some `set()` based version?
> 
>    Since you didn't comment on it I guess that there doesn't yet exist a
>    better way than using clear_my_address to parse a address string into a
>    list?

I'm not completely sure. Have a look at `email.Utils.getaddresses` and `parseaddr`..

**Comment by josch** [comment]
Quoting Patrick Totzke (2016-01-05 08:55:20)
> Quoting josch (2016-01-04 07:51:36)
> >    Okay, I can add make_unique to alot.utils.
> 
> How about some `set()` based version?

I explained why this doesn't work in my initial report. Imagine you have the
following list of addresses:

    [ "foo <blub@bla.com>", "bar <blub@bla.com>" ]

Then you don't want blub@bla.com in the list twice, right? Instead either of
those two should be picked arbitrarily. Picking one arbitrarily should be fine
because I don't see a good way to decide for one and both must be correct or
they wouldn't be listed like that.

> >    Since you didn't comment on it I guess that there doesn't yet exist a
> >    better way than using clear_my_address to parse a address string into a
> >    list?
> 
> I'm not completely sure. Have a look at `email.Utils.getaddresses` and
> `parseaddr`..

Right, I guess it might even be better to store the address lists as a list of
`(realname, address)` tuples as returned by `parseaddr` instead of repeatedly
parsing and encoding the address strings.

Though before I can further work on this I need a solution for #823 which
currently makes me unable to try out my changes in git.

Thanks!

cheers, josch

**Comment by pazz** [comment]
>    > How about some `set()` based version?
> 
>    I explained why this doesn't work in my initial report. Imagine you have
>    the
>    following list of addresses:
> 
>    [ "foo <blub@bla.com>", "bar <blub@bla.com>" ]
> 
>    Then you don't want blub@bla.com in the list twice, right? Instead either
>    of
>    those two should be picked arbitrarily. Picking one arbitrarily should be
>    fine
>    because I don't see a good way to decide for one and both must be correct
>    or
>    they wouldn't be listed like that.

agreed, thanks.

**Comment by pazz** [comment]
this is pushed now.
