### ISSUE TITLE
editnew bug

### ISSUE THREAD

**Issue by pazz** [pazz/alot#819]
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 588, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/home/pazz/.local/lib/python2.7/site-packages/alot-0.3.8.dev0-py2.7.egg/alot/ui.py", line 633, in call_apply
    return defer.maybeDeferred(cmd.apply, self)ts
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1274, in unwindGenerator
    return _inlineCallbacks(None, gen, Deferred())
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1128, in _inlineCallbacks
    result = g.send(result) is already due since 23 Dec 2015.
  File "/home/pazz/.local/lib/python2.7/site-packages/alot-0.3.8.dev0-py2.7.egg/alot/commands/globals.py", line 846, in apply
    if self.encrypt or account.encrypt_by_default:
exceptions.AttributeError: 'NoneType' object has no attribute 'encrypt_by_default'

```

**Comment by pazz** [comment]
the above error occurs when I use the `editnew` command (in alot v0.3.7) in a thread buffer.
This seems related to #774

**Comment by meskio** [comment]
I confirm I can reproduce it. I'm looking into it. Sorry for the delay.

**Comment by lakinwecker** [comment]
I am attempting to setup alot for the first time, and I am running into this issue trying to compose any message. Is this something that will be merged or released soon? Or should I look for a workaround?

**Comment by meskio** [comment]
@lakinwecker my experience with alot is that things get merged at some point, but some times it takes time.

@pazz can we do something to help you on the reviews?

**Comment by lakinwecker** [comment]
@meskio: good point. :)  I'd be happy to help get this merged as well

**Comment by meskio** [comment]
@lakinwecker you could test it to see if it works for you. I just rebased it on top of master.

**Comment by lakinwecker** [comment]
@meskio pazz:master exhibits the same issue (I was previously using the version from Arch AUR). meskio:819_editnew_bug fixes it for me. I am able to compose messages.

**Comment by pazz** [comment]
thanks for this. I am lacking behind PR's for alot as i don't spend too much time on it any more. I will keep this one in my inbox. *promise*

**Comment by jasom** [comment]
Is there a workaround for this?  A bug that prevents sending any new messages is pretty severe in an e-mail client.

**Comment by pazz** [comment]
Quoting Jason Miller (2016-11-29 17:01:33)
>    Is there a workaround for this? A bug that prevents sending any new
>    messages is pretty severe in an e-mail client.

It does nothing of the sort: this is a bug in the operation that
creates a new mail out of an existing one..

**Comment by lakinwecker** [comment]
I was running into it using the `:compose` command, so for me it stopped me from composing any new mail

**Comment by jasom** [comment]
@lakinwecker and I get the exact same symptom with `:compose` and @lakinwecker reports that @meskio's patch branch fixes the problem (I'm trying that currently).

**Comment by pazz** [comment]
That would be a new bug. Can you provide some more info on how to
reproduce it? thx,
p

Quoting lakinwecker (2016-11-29 17:56:37)

**Comment by jasom** [comment]
> That would be a new bug. Can you provide some more info on how to reproduce it? thx, p
This does it for me:

1. `virtualenv venv/alot`
2. . venv/alot/bin/activate
3. `pip install https://github.com/pazz/alot/archive/master.zip`
4. `mv ~/.config/alot ~/.config/alot~`
5. `alot`
5. `:compose <RET> <RET> <RET>

**Comment by pazz** [comment]
As mentioned earlier, this patch has not made it to the master branch,
just the testing branch!
Try https://github.com/pazz/alot/archive/testing.zip

Quoting Jason Miller (2016-11-29 18:20:15)
