### ISSUE TITLE
Add more flexibility for timestamp formats

### ISSUE THREAD

**Issue by BlacklightShining** [pazz/alot#821]
I like the human-readable timestamps that you get in search view (`just now`, `${x}min ago`, `08:12am`, and the like). Some of the details bother me, like the _yesterday_ timestamps being in twelve-hour time and the _last year_ timestamps not including the day, but specifying `timestamp_format` makes _all_ the timestamps use that one format, which is worse. Can we get some way of customizing the various different kinds of timestamp?

**Comment by pazz** [comment]
I'm not sure what kind of customization you have in mind, but feel free to hack around and send a pullrequest if you have more concrete suggestions

**Comment by haasn** [comment]
What I would like to bring up is that this logic does not make much sense to me:

```
    ampm = d.strftime('%P')
    if len(ampm):
        hourfmt = '%I' + ampm
        hourminfmt = '%I:%M' + ampm
    else:
        hourfmt = '%Hh'
        hourminfmt = '%H:%M'
```

In my locale I certainly have a very reasonable setting in place for %P, but I would still prefer to use 24-hour notation over a 12-hour notation.

I can work around this limitation by invoking alot as `LC_TIME=de_DE.UTF-8 alot` (or some other time locale that doesn't have %P defined), though, so it's not a huge issue.

**Comment by haasn** [comment]
I found a cleaner work-around: I can copy/paste the pretty_datetime function, remove that logic, and use it as my own datetime hook.

**Comment by stupidus89** [comment]
How do you use the pretty_datetime function as your own hook? I copied the function from `helper.py` into `~/.config/alot/hooks.py` and modified it, but alot is still using the function from the helper.py file. How can I tell alot to use the function from the hooks file?

**Comment by pazz** [comment]
@stupidus89 you are rererring to the [timestamt_format](http://alot.readthedocs.io/en/latest/configuration/hooks.html#) hook? Notice that it is not called `pretty_datetime`..

**Comment by stupidus89** [comment]
Thanks. I renamed the function and now it is working.
