### ISSUE TITLE
running alot from git

### ISSUE THREAD

**Issue by josch** [pazz/alot#823]
I tried running alot from git like this:

    PYTHONPATH=. python alot/__main__.py

I'm probably doing this wrong and I'd appreciate a pointer on how to properly run alot straight from git without installing it first. The error message I get is:

    Could not read /home/josch/.abook/addressbook

This file exists and after investigating `alot/settings/utils.py` it rather seems that instead of `/home/josch/.abook/addressbook` not being readable it might be the spec file that is not readable because alot tries to pass the following file to `ConfigObj`:

    /home/josch/git/alot/alot/addressbook/defaults/abook_contacts.spec

Where it actually should use:

    /home/josch/git/alot/alot/defaults/abook_contacts.spec

Now this might very well be a problem because I try running alot from git but:

 1. it should be possible to execute alot straight from git
 1. if the spec is really the problem then the error message is wrong and should be fixed instead (maybe just be a test if the spec file exists and is readable)

**Comment by TomasTomecek** [comment]
```
$ PYTHONPATH=$PWD python -m alot
```

**Comment by josch** [comment]
Thanks @TomasTomecek - that still leaves me with the abook problem though.

**Comment by pazz** [comment]
we need more infor on the addressbook path issue here. What makes you think `alot/settings/utils.py`
has anything to do with this? I also cannot reproduce this issue on my end

**Comment by josch** [comment]
`alot/settings/utils.py` is the one where I get the following error from:

    Could not read /home/josch/.abook/addressbook

though that file does exist. Instead it seems that I get an `IOError` because `abook_contacts.spec` cannot be read. I suggest the following patch:

```diff
--- a/alot/settings/utils.py
+++ b/alot/settings/utils.py
@@ -27,7 +27,7 @@ def read_config(configpath=None, specpath=None, checks={}):
     except ConfigObjError as e:
         raise ConfigError(e)
     except IOError:
-        raise ConfigError('Could not read %s' % configpath)
+        raise ConfigError('Could not read %s or %s' % (configpath, specpath))
     except UnboundLocalError:
         # this works around a bug in configobj
         msg = '%s is malformed. Check for sections without parents..'
```

Here more info: so it tries to read `alot/addressbook/defaults/abook_contacts.spec` which doesn't exist and where instead it should read `alot/defaults/abook_contacts.spec`. This path in turn seems to be created because `os.path.dirname(__file__)` is concatenated with `defaults` and then with `abook_contacts.spec` in `alot/addressbook/abook.py`. But `os.path.dirname(__file__)` evaluates to `alot/addressbook`. The actual path we want is just `alot` so that concatenating it with `defaults` and then `abook_contacts.spec` will create the right path: `alot/defaults/abook_contacts.spec`. The following patch fixes problem this for me:

```diff
--- a/alot/addressbook/abook.py
+++ b/alot/addressbook/abook.py
@@ -15,7 +15,7 @@ class AbookAddressBook(AddressBook):
         :type path: str
         """
         AddressBook.__init__(self, **kwargs)
-        DEFAULTSPATH = os.path.join(os.path.dirname(__file__), 'defaults')
+        DEFAULTSPATH = os.path.join(os.path.dirname(__file__), '..', 'defaults')
         self._spec = os.path.join(DEFAULTSPATH, 'abook_contacts.spec')
         path = os.path.expanduser(path)
         self._config = read_config(path, self._spec)
```

though there is probably a more elegant solution.

The problem was probably created in commit 2f064af4 where the code was residing in `alot/addressbooks.py` and thus it calling `os.path.dirname(__file__)` resulted in the path we wanted: `alot`. Moving the code a directory deeper to `alot/addressbook/abook.py` changed the output of `os.path.dirname(__file__)` to `alot/addressbook` which in turn created the behaviour I initially described.

I hope this made sense now :)

Thanks!

**Comment by pazz** [comment]
thanks for this. You are absolutely right, I forgot to update this relative path when I refactored this code.
Can you send a PR for these two patches?

**Comment by pwnage101** [comment]
This can be closed.  I created an addressbook file using

`abook --add-email <path/to/maildir/message`

then I edited my `~/.config/alot/config` to contain the following section:

```
[[[abook]]]
    type = abook
```

then I cloned alot from github (747b894bbe2156bae2c1f128ec0b4344d7c28378) and ran:

`PYTHONPATH=$PWD python -m alot`

no backtrace, alot runs successfully.

**Comment by pazz** [comment]
thanks for the update
