### ISSUE TITLE
Cannot see some message bodies

### ISSUE THREAD

**Issue by datakurre** [pazz/alot#829]
I'm new to alot. Any tips, why I don't see bodies for some messages with alot (only headers are shown), even I can see the bodies with ``notmuch show``?

I'm not sure if this is true for all "broken" messages, but at least some of them are multipart messages (with text/plain shown by notmuch).

**Comment by datakurre** [comment]
@garbas Have you seen this?

**Comment by pazz** [comment]
dup of #622; please read the [FAQ](http://alot.readthedocs.org/en/latest/faq.html) (point 5)

**Comment by garbas** [comment]
@datakurre aha now i know why i keep w3m installed around :)

i guess we need to improve nix expression for alot and w3m with ${w3m}/bin/w3m.

**Comment by datakurre** [comment]
@pazz Thanks.
