### ISSUE TITLE
Add an option to support format=flowed when composing and reading

### ISSUE THREAD

**Issue by BlacklightShining** [pazz/alot#837]
This would be really nice to have—plain-text messages without flowing [can look terrible on screens of different sizes](https://mathiasbynens.be/_img/gmail-plain-text/result-in-ios-mail.png).

If the editor is `vim`, the option should probably also set `formatoptions+=w`.

**Comment by pazz** [comment]
I don't understand this feature request

**Comment by BlacklightShining** [comment]
`format=flowed` is described in [RFC 3676](https://tools.ietf.org/html/rfc3676). The gist is that it adds a parameter to the `text/plain` MIME type called `format`, which can be set either to `fixed` (the default) or to `flowed`. `format=fixed` doesn't change anything; `format=flowed` causes readers to ignore any linebreaks with preceding space (`\x20`) characters, in favor of breaking lines naturally (i.e. when they become too long to fit).

**Comment by fnurl** [comment]
@BlacklightShining I made a hook and some necessary changes to the alot code that does this. See https://gist.github.com/fnurl/bc5b48e14cd3da11173aa63992936cea

**Comment by dcbaker** [comment]
If we add this option it needs to be disableable, this will break working with patches on a mailinglist in a way that will enfuriate everyone involved. Honestly I think the hook might be a better way to handle this. We could definately add it to the wiki

**Comment by fnurl** [comment]
@dcbaker it is a hook, the changes only enable the hook to work by enabling the `pre_envelope_edit()` hook. At the moment, that hook never runs because hooks are only attached from command line entered commands.

**Comment by dcbaker** [comment]
@fnurl: I recognize that, I think your hook solution is better than adding this to alot core, since I do not want this feature (and would be flamed for using it) since the majority of work I do with email is reviewing patches on mailing lists, and for that people expect text email with an 80 character per line limit; and I know that other people using alot/notmuch have the same use case.

**Comment by pazz** [comment]
@fnurl: if you make the suggested changes in #967 I'd be happy to push this.
In that case, it'd be great if you'd document the hook you mention in the [wiki](https://github.com/pazz/alot/wiki/Contrib-Hooks); thx

**Comment by fnurl** [comment]
@dcbaker thanks for the comments on #967 

@pazz I'll add the hook to the wiki too!

**Comment by BlacklightShining** [comment]
@dcbaker All _options_ can be disabled. Otherwise, they wouldn't be **options.** NB: I never suggested anything that would change the default behavior or otherwise break backwards compatibility. You and everyone else who didn't opt into the feature as originally suggested (i.e. _**change an option**_) wouldn't get it.

**Comment by BlacklightShining** [comment]
Anyway, I think implementing #897 is all-around better—it would let you choose between `format=fixed` (the default) and `format=flowed` for individual messages, rather than having to change an option|muck about with hooks and then restart `alot` each time.

**Comment by pazz** [comment]
I think we agree that setting/amending the content-type header via hooks is prefereable to hardcoding this.
As the bug with hooks not being triggered is merged #967 I will close this issue here. Perhaps we should link @fnurl s hook to the wiki for others to find. #897 is an alltogether different beast, and I think it is a good idea.

**Comment by pazz** [comment]
By the way: re f:f i found this to be helpful https://joeclark.org/ffaq.html
