### ISSUE TITLE
Optionally use something besides the local hostname in message IDs

### ISSUE THREAD

**Issue by BlacklightShining** [pazz/alot#838]
Possibly the mail provider's domain, or the whole `From` address with a dot instead of the at sign (hey, DNS does it!)

**Comment by pazz** [comment]
Quoting Blacklight Shining (2016-02-03 15:53:11)
>    Possibly the mail provider's domain, or the whole From address with a dot
>    instead of the at sign (hey, DNS does it!)


This is not done by alot but by the email module (see line 263 of db/envelope.py).
So unless you find out and propose to use some parameters to this function
call, there is not much we can do here.

**Comment by BlacklightShining** [comment]
Yeah, looks like `make_msgid()` always uses the current time and hostname. You could always do it yourself, with `uuid.uuid4()` and the mail provider's domain (it looks like Apple's mail client does that).

**Comment by pazz** [comment]
Quoting Blacklight Shining (2016-02-04 00:58:25)
>    Yeah, looks like make_msgid() always uses the current time and hostname.
>    You could always do it yourself, with uuid.uuid4() and the mail provider's
>    domain (it looks like Apple's mail client does that).

If you really want this feature, I suggest you add a hook that creates the
MessageID (and defaults to the current behaviour if that hook is nonexistent)..

**Comment by t-8ch** [comment]
In an earlier version of alot I used this hook, which may still work.

```py
def pre_envelope_send(ui, dbm):
    ui.current_buffer.envelope.add(
        'Message-ID', '<%s@t-8ch.de>'.format(uuid.uuid4().hexdigest()))
```

**Comment by dcbaker** [comment]
Since this seems resolved via hook, I'm going to close this.
