### ISSUE TITLE
16 color terminal mode has some odd colors

### ISSUE THREAD

**Issue by Profpatsch** [pazz/alot#840]
I’m using a solarized terminal color scheme, and this is how alot looks like by default:

![screenshot](https://cloud.githubusercontent.com/assets/3153638/12918801/48fdbf8e-cf41-11e5-9ea8-a500e458e6d8.png)

* left is the output of [this color table script](https://raw.githubusercontent.com/alghanmi/terminal_color_test/master/colortable16.sh)
* top right is 16 colors
* bottom right is 256 colors

The blue background looks correct, but the grey one doesn’t even appear in my colorscheme (and the contrast in both cases is awkward at best).

**Comment by pazz** [comment]
have you tried https://github.com/pazz/alot/blob/master/extra/colour_picker.py ?
It could be that this colour is some shading of gray and your colour script might just not display those.
in any case, have a look at the solazized themes for alot itself (I'm using those as well)

**Comment by Profpatsch** [comment]
That script indeed displays some additional colors:

![screenshot](https://cloud.githubusercontent.com/assets/3153638/12935078/8d5792f2-cf93-11e5-88b7-f86bfe60629c.png)

In this case: Isn’t yellow on light gray bad idea in any case?

**Comment by pazz** [comment]
Quoting Profpatsch (2016-02-10 00:14:50)
>    That script indeed displays some additional colors:
> 
>    [1]screenshot
> 
>    In this case: Isn’t yellow on light gray bad idea in any case?

You are welcome to improve the default theme. It looks all a bit different in my
terminal anyway as I solarized my ~/.Xresources

**Comment by Profpatsch** [comment]
Can you post a reference image of your colors?
I directly configured solarized in my terminal emulator ([lilyterm](https://github.com/Tetralet/LilyTerm)), and the only thing that’s different is the background color (#1D1C1A (grey) instead of #002b36 (dark greenish-blue))

**Comment by pazz** [comment]
Quoting Profpatsch (2016-02-10 10:42:14)
>    Can you post a reference image of your colors?
>    I directly configured solarized in my terminal emulator ([1]lilyterm), and
>    the only thing that’s different is the background color (#1D1C1A (grey)
>    instead of #002b36 (dark greenish-blue))


here are some (old) screenshots i made with the same config:
https://github.com/pazz/alot/tree/master/extra/themes/screenshots

I'm using urxvt.

**Comment by Profpatsch** [comment]
How does your selection look? Mine’s like this:

![screenshot](https://cloud.githubusercontent.com/assets/3153638/12945462/c4b31cc6-cfed-11e5-9a88-5b3603be5f75.png)

**Comment by pazz** [comment]
the default theme has dark gray over light gray for me in my terminal config.
But as I said: I am using solarized terminal colours *and* the solarized alot theme
