### ISSUE TITLE
pass arguments to refine prompt

### ISSUE THREAD

**Issue by teto** [pazz/alot#845]
Hi,

I would like to toggle some flag in my current search, for instance to list only the unread messages within the current search (via a bindings). I tried to bind `R = refineprompt 'tag:unread' ` but refine prompt does not accept any argument. 
Ideally I would like to achieve some kind of "R = toggletag_incurrent_search <tag>"

**Comment by pazz** [comment]
These things can be done easily by defining a custom hook and then bind some key
to `call yourhookname`.
In the hook code, you can extract / change the current buffers' query string and
call refresh(), for instance.

#close

Quoting Matthieu Coudron (2016-02-24 11:47:58)

**Comment by teto** [comment]
Thansk I managed to get something working.
Nb: it would be nice to say in log which file was used for hooks (does not appear when hooks are successfully loaded).

**Comment by pazz** [comment]
Quoting Matthieu Coudron (2016-02-25 00:03:47)
>    Thansk I managed to get something working.
>    Nb: it would be nice to say in log which file was used for hooks (does not
>    appear when hooks are successfully loaded).

Yea, why not. Care to submit this patch?
The thing is that there is no ambiguity here, as alot will only try to
read hooks from ~/.config/alot/hooks.py ..

**Comment by teto** [comment]
According to doc, you can set the "hooksfile" option. http://alot.readthedocs.org/en/latest/configuration/config_options.html . 
I will submit a patch.

When trying to toggle the "unread" tag in the buffer.querystring, I have to handle several cases (here is some pseudocode, my actual cod e being on another computer): 
```
for pattern in ['tag:unread AND', 'AND tag:unread', 'tag:unread']:
    if pattern in querystrying:
        found_match= True
        querystring.replace(pattern, '') # remove the tag from query string

if not found match:
    querystring += " AND tag:unread"
```
Is there some kind of wrapper to build the notmuch request ?
sthg like a NotmuchRequest with add_tag/remove_tag/toggle_tag
