### ISSUE TITLE
Search for several tags

### ISSUE THREAD

**Issue by teto** [pazz/alot#846]
I would like to be able to search several tags without typing them every time.
Right now I can do this via creating bindings which is ok as long as you don't have too many tags.
I had the following ideas (providing there is no other alternative I don't know of):
- prepend entries with several tags (loaded from a file) to taglist
- be able to mark tags in taglist and generate a search from marked tags
- add autocompletion to search:tag ?

I might implement some of these ideas if they make sense to you.

**Comment by pazz** [comment]
Quoting Matthieu Coudron (2016-02-24 11:54:31)
>    I would like to be able to search several tags without typing them every
>    time.
>    Right now I can do this via creating bindings which is ok as long as you
>    don't have too many tags.
>    I had the following ideas (providing there is no other alternative I don't
>    know of):
> 
>      * prepend entries with several tags (loaded from a file) to taglist

I don't understand this.

>      * be able to mark tags in taglist and generate a search from marked tags

complicated..

>      * add autocompletion to search:tag ?

There already is tab completion for query strings like that:
in the search prompt, type `tag:` and maybe some prefix, and hit tab. voila!

**Comment by teto** [comment]
> There already is tab completion for query strings like that:
Indeed
> * be able to mark tags in taglist and generate a search from marked tags
Thought so but wouldn't marking several entries be also necessary in search mode ? to retag a bunch of entries for example
>I don't understand this.
My bad. in taglist you have:
```
unread
killed
family 
friends
```
It could load a file or run a hook to add custom entries:
```
unread
killed
family 
friends
# added manually
unread AND killed   
family AND friends
```

**Comment by pazz** [comment]
Aha! I think what you want is something like the "saved searches" feature in the
emacs UI. Alot doesn't yet have that. But you'll find some discussion in the
issues about that.

Quoting Matthieu Coudron (2016-02-25 00:16:21)

**Comment by teto** [comment]
If there are already issues about it th'as fine for me thanks. I will use custom mappings for now.
