### ISSUE TITLE
Ask the user before quitting

### ISSUE THREAD

**Issue by GuillaumeSeren** [pazz/alot#851]
Hey,
I just notice that, if I start to compose add recipient, then senders, then I changed my mind so I C-c to close that call, alot just quit (witch is not what i wanted). 
Maybe C-c in alot is not a good practice, and I know that <escape> works better, 
but I feel it could be great to have a confirmation to quitting, what do you think ?

**Comment by pazz** [comment]
There is of course the "bug_on_exit" config flag, but that will only
trigger if you use the normal "exit" command (or close the last buffer).
I thing recently, someone added signal handling to `alot.ui.UI`,
so that `SIGUSR1` is intercepted and triggers a refresh.
It should be easy to add some code that intercepts `SIGKILL` and triggers `exit`
(which would then, if bug_on_exit=true, behave as you want).
Go for it! :)

Quoting Guillaume Seren (2016-03-08 10:52:28)

**Comment by GuillaumeSeren** [comment]
@pazz:
Yes I can see that, I will try some test but maybe we can add that as a global behaviour,
so if you set it in you config you can prevent to quit alot by mistake.

**Comment by GuillaumeSeren** [comment]
Oh nevermind, I did not test bug_on_exit flag it works on *normal* exit,
in mutt C-c trigger exit, and ask for quitting, and 'q' quit directly so I think,
we could 'force' bug_on_exit even if it is not set for that case.
It was some time I didn't read the source of alot so I am searching a bit to find a place for my hook.

**Comment by GuillaumeSeren** [comment]
Ok I played a bit more with the source and added my case in the handle_signal() function,
it catch the signal and I can ask the use to confirm same way that bug_on_exit do.

Do you think we need something more ?

**Comment by pazz** [comment]
I'd rather this signal triggers an exit command, because that would make sure
that all queued up changes to the index have been flushed before alot shuts
down.


Quoting Guillaume Seren (2016-03-09 22:40:13)

**Comment by GuillaumeSeren** [comment]
@pazz :
I agree this way you can setup the bug_on_exit flag and get the expected behaviour,
in the other side (without the flag) it will quit in a cleaner fashion.
I am cleaning my patch, then I'll send it to you.

**Comment by GuillaumeSeren** [comment]
Ok I prepared a PR here #852
