### ISSUE TITLE
make sure the write-queue is flushes when exiting 

### ISSUE THREAD

**Issue by pazz** [pazz/alot#853]
see discussion in #851 #852

**Comment by GuillaumeSeren** [comment]
I could work on that too, but I am not sure to well understand the process,
can you explain a bit more how it can append ?

**Comment by pazz** [comment]
I think we just want to use `commands.globals.FlushCommand` here:

1. Build (find) a function that actually shuts down the UI
2. Create a FlushCommand(callback=MYSHUTDOWNFUNCTION)
3. pass it to UI.apply_command(..)

that would try (and re-try) to flush the db, and only when it was successful
it calls the callback, that shuts down the ui.




Quoting Guillaume Seren (2016-03-10 13:58:20)

**Comment by pazz** [comment]
done (https://github.com/pazz/alot/commit/621c2288e1c2f4c04ccd7888801031f15165b8f8)
