### ISSUE TITLE
Reply --all keep all cc

### ISSUE THREAD

**Issue by GuillaumeSeren** [pazz/alot#855]
Hey,
I need to send mail with a lot of cc these day, for my job,
and I would like to keep all cc, when I 'reply --all'.

Maybe I miss one option, or maybe we need to upgrade the reply command code,
to keep all headers, are you agree ?

**Comment by pazz** [comment]
that's the expected behavour, yes. It's not working?

**Comment by GuillaumeSeren** [comment]
@pazz 
Yes it is not keeping the cc'ed in the reply so I think it is broken somehow ?

It is working on your side ?

**Comment by pazz** [comment]
Quoting Guillaume Seren (2016-03-13 21:05:02)
>    [1]@pazz
>    Yes it is not keeping the cc'ed in the reply so I think it is broken
>    somehow ?
> 
>    It is working on your side ?

Yes. I just tried it again and it does copy all Cc-values over for me

**Comment by GuillaumeSeren** [comment]
Damn it didn't work on my build I will investigate this week !

**Comment by GuillaumeSeren** [comment]
Quick reply,
I think it work, but as the cc didn't appear in my editor (vim),
I thought they wasn't here, but they are added after.

So my question became, don't we want to display them in the editor ?

It could be usefull, to see them.

**Comment by LinuCC** [comment]
No problem here with 0.3.7.
`reply --all` leads me directly into (neo)vim with the Cc correctly set.
Try a different editor or remove all plugins from vim, since some could introduce unwanted behaviour (wrapping of long CCs).

**Comment by GuillaumeSeren** [comment]
@LinuCC Maybe i am not precise enought,
I can confirm that the Cc are being kept when I come back from vim / neovim,
*but* they aren't show in the editor so I think it could be a good idea to display it.

**Comment by pazz** [comment]
@GuillaumeSeren did you set Cc etc in `edit_headers_whitelist` ?

**Comment by GuillaumeSeren** [comment]
@pazz 
I wasn't sure wich option, but after checking no I'd set:
```
edit_headers_whitelist = Attach,From,To,Subject
```
I added the Cc and Bcc to the list and my issue seem's to be fixed.

Thank you for feedback @pazz @LinuCC
