### ISSUE TITLE
exception when replying to my own emails with only bcc

### ISSUE THREAD

**Issue by josch** [pazz/alot#859]
Hi,

when I hit the reply button on emails written to myself but with all recipients in Bcc I get the following in my log:

```
ERROR:ui:Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 306, in addCallback
    callbackKeywords=kw)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 295, in addCallbacks
    self._runCallbacks()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/usr/share/alot/alot/ui.py", line 638, in call_apply
    return defer.maybeDeferred(cmd.apply, self)
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 139, in maybeDeferred
    result = f(*args, **kw)
  File "/usr/share/alot/alot/commands/thread.py", line 211, in apply
    to = ', '.join(recipients)
exceptions.TypeError: sequence item 0: expected string, NoneType found
```

What I expected to happen was a new email with the right `Reply-To` headers and the right subject and an empty `To` header.

**Comment by josch** [comment]
It seems a fix would be to change the last line in thread.py:

```
        # check if reply is to self sent message
        if sender_address in my_addresses:
            recipients = [mail['To']]
```

into:

```
            recipients = [mail.get('To', '')]
```

**Comment by pazz** [comment]
dup of #784?

**Comment by josch** [comment]
I don't think so. I can reply to other emails of mine just fine.

**Comment by pazz** [comment]
But the traces look very similar don't they?

**Comment by josch** [comment]
Indeed, but the other bugreport also doesn't say whether the reporter tried to reply to a bcc-only self-sent email. You should ask that :)

**Comment by pazz** [comment]
Sure, I'm just trying to see if it's actually one construction site rather than
one :)

Does your patch fix the issue for you?

**Comment by josch** [comment]
Yes, my patch fixes this issue :)

**Comment by pazz** [comment]
OK great. Care to send a PR for this?
Thanks!

**Comment by josch** [comment]
Sorry, too little time for that. Just use it. I don't care about attribution. Thanks!

**Comment by pazz** [comment]
you patch might result in an empty string introducing two consecutive commas.. which is not a malformed header value but still not so nice.
Does https://github.com/pazz/alot/commit/98f1ba44cab6a8fdf0a50c45e795792f2d775a61
work for you as well?

**Comment by josch** [comment]
yup, 98f1ba4 fixes this issue, thanks!
