### ISSUE TITLE
Allow to pass files to the compose command as attachments

### ISSUE THREAD

**Issue by Cutuchiqueno** [pazz/alot#861]
I very often run into the situation that I want to send someone some files from within a folder I am currently working in and would like to start `alot compose file1 file2 …` so that the files automatically become attachments of the newly created email so that I do not need to look for them again from within alot.

Such a feature would simplify my life *alot* ;-)

**Comment by pazz** [comment]
alot compose --attach *jpg

works for me. See `alot compose --help` for more info..

**Comment by Cutuchiqueno** [comment]
Ok, I feel stupid. I have not considered that each subcommand has its own --help flag.
Thanks a lot.
