### ISSUE TITLE
Feature: Add a tree view for the mime parts of a message

### ISSUE THREAD

**Issue by lucc** [pazz/alot#862]
This is a feature request (or discussion) for a new alternative way to display a message in thread buffers. It could be accessible with a new command for thread buffers `togglemimetree` which should be used similar to `togglesource` or `toggleheaders`.

If activated the mime tree of the message should be displayed below the currently displayed header lines (so this command should work independently of `toggleheaders`). Each line should correspond to one mime part and the lines should be indented like the messages in thread view to indicate the tree structure. 

Some commands are of interest when viewing the mime tree:
- something like `select` to display a rendered version of the current mime part (either inside the tree or in a new buffer)
- something like `select` currently works on attachments to open mime parts with external tools
- something like `pipeto` to pipe only this mime part to an external shell command
- something like `save` to save only this mime part to a file
- others?

This feature is inspired by the [view-attachments](http://www.mutt.org/doc/manual/#attach-menu) of mutt. In mutt it looks like this: 
![view-attachments](https://cloud.githubusercontent.com/assets/1104419/14314942/b9e4df08-fbfa-11e5-9549-4136777728c0.png)

**Comment by meskio** [comment]
I belive this issue has being solved by #1480. Isn't it? Or is there still some parts still missing?
