### ISSUE TITLE
Feature: Adding tags before sending.

### ISSUE THREAD

**Issue by lucc** [pazz/alot#870]
I was unable to find this feature so I propose it here. (Maybe I missed something?)

When I compose a mail I would like to add tags to it before sending it. Technically speaking the tags would only be applied after the message was send and a copy was saved to disk and registered with notmuch. But I would like to specify such tags in the envelope buffer before sending the mail. Otherwise I have to search for it after it was send and apply the tags. This (the search step) feels cumbersome to me.

**Comment by pazz** [comment]
yes, I agree that this could be a nice feature.
We could replicate the tag commands from thread/search buffers also in envelope buffers,
keep the info in the envelope and tag command in the `afterwards` callback of
`envelope.SendCommand` (https://github.com/pazz/alot/blob/master/alot/commands/envelope.py#L254) .

**Comment by lucc** [comment]
Cool, the constructor of `alot.db.envelope.Envelope` already has a `tags` argument. It is stored in the envelope and later (in the `afterwards` callback you mentioned) these tags are already applied to the message!

I just don't see any place where they are set in the constructor. But the new `:tag` command in an envelope buffer could store the tags there. 

What should the command interface look like? I think if I add a `:tag` command there should be a `:untag` at least. Maybe also a `:retag`?

**Comment by lucc** [comment]
@pazz if we have a tag command in search buffers, in thread buffers and also in evelope buffers it might make sense to abstract some small base class out of these. Yes? Where should it do?

**Comment by pazz** [comment]
nice idea. I'd simply introduce a new TagCommand for envelope buffers
and copy & paste the decorators. IMO the actual command code is
different enough from what we do in other buffers so I'm not sure
what is there to gain from making an abstraction in commands/globals
or so..

Quoting Lucas Hoffmann (2017-07-04 06:03:15)

**Comment by lucc** [comment]
I started implementing it (and it seems to be rather easy). But there is already some documentation for all four commands in `docs/source/usage/modes/envelope.rst` . What is the deal with that? I can not find any corresponding code or functionallity in `master`.

**Comment by pazz** [comment]
Quoting Lucas Hoffmann (2017-07-05 09:05:33)
> I started implementing it (and it seems to be rather easy). But there is
> already some documentation for all four commands in docs/source/usage/modes/
> envelope.rst . What is the deal with that? I can not find any corresponding
> code or functionallity in master.

I dint see it:
https://github.com/pazz/alot/blob/master/docs/source/usage/modes/envelope.rst

remember that this stuff is auto-generated at make-time from the decorators in alot/commands/*py

**Comment by lucc** [comment]
yes I did remember that shortly after I wrote the above. You probably did not see my edit via mail.

The PR is ready by the way.

**Comment by pazz** [comment]
Quoting Lucas Hoffmann (2017-07-06 00:43:49)
> yes I did remember that shortly after I wrote the above. You probably did not
> see my edit via mail.

yep, I should check the github website every once i na while :)
 
> The PR is ready by the way.

great! I'll have a look as soon as I can.
cheers
