### ISSUE TITLE
SIGUSR1 should only refresh search views?

### ISSUE THREAD

**Issue by jimcheetham** [pazz/alot#871]
My MDA (actually, notmuch new's post-new hook) is using SIGUSR1 to tell alot that new messages are available; when sitting at the search list this works well.

However, when reading a thread the external interrupt refreshes the buffer, meaning that I lose my cursor position and return to the top. It makes sense to refresh the thread _if_ there is a change in the thread (i.e. the new message that arrived was in this thread; although many other MUAs don't bother with a live refresh of a thread view at all)

Is there some solution like the post_buffer_focus hook mentioned in #828 ?

**Comment by pazz** [comment]
I can't think of any smart solution to your problem atm, sorry.
Note to self: `alot.ui.UI.handle_signal` can use some love.
signal-handling code could actually be done by user hooks..
