### ISSUE TITLE
Unfavourable standard: Close without sending [y]

### ISSUE THREAD

**Issue by f-thiele** [pazz/alot#875]
When in envelop mode e.g. composing a message and then closing the buffer using `bclose` the question asked is `close without sending? [y]:yes (n):no`.

However the standard keyboard shortcut for sending a message is `y`as well, leading to an unfavourable constellation: It is easy to mistakenly send a message using this combination. E.g. by pressing `n y` inadvertently.

I noticed that pressing enter works as well, which does not send e-mails so for now I am using this as a safe-guard.

**Comment by pazz** [comment]
I forgot to close this here.
