### ISSUE TITLE
Signatures not respecting gpg_key configuration

### ISSUE THREAD

**Issue by fowlslegs** [pazz/alot#876]
I have set the `gpg_key:` to my short key ID, 68A6AA0A, for both my accounts since starting to use alot. However, I just received an email telling me a message I had sent had been signed with a different key (I cannot verify this because I did not realize alot does not have encrypt-to-self setup by default and I'll need to work that out in my gpg.conf, but that's a separate issue--anyway, I trust he's correct). To test, I just sent myself an unencrypted, but signed message and it worked correctly (at least according to alot it was valid--I tried to just copy the content between the first two "boundaries" in the raw message and verify that it against the signature below, but gpg was telling me the signature was invalid, but at least from the correct key--maybe I'm just making a mistake here having not worked with multipart/signed content before).

Anyway, while trying to debug this I did also notice this as a strange behavior:

``` py
>>> plaintext = "hail seitan"
>>> detach_sig = alot.crypto.detached_signature_for(plaintext, alot.crypto.get_key("68A6AA0A"))[1]
>>> plaintext = "hail seitan"
>>> signature = alot.crypto.detached_signature_for(plaintext, alot.crypto.get_key("68A6AA0A"))[1]
>>> alot.crypto.verify_detached(plaintext, signature)
[<gpgme.Signature object at 0x7f8b8cb0a138>]
>>> plaintext = "jajaja"
>>> alot.crypto.verify_detached(plaintext, signature)
[<gpgme.Signature object at 0x7f8b8cb0a190>]
```

Shouldn't it be raising a `GPGProblem` in the second verify example?

**Comment by pazz** [comment]
Quoting Noah Vesely (2016-07-03 00:25:26)
>    I have set the gpg_key: to my short key ID, 68A6AA0A, for both my accounts
>    since starting to use alot. However, I just received an email telling me a
>    message I had sent had been signed with a different key (I cannot verify
>    this because I did not realize alot does not have encrypt-to-self setup by
>    default and I'll need to work that out in my gpg.conf, but that's a
>    separate issue--anyway, I trust he's correct). To test, I just sent myself

yes, this should be documented, or at least a gpg setup howto should be
linked in alot's docs. please don't hesitate to send a PR if you know
how.


>    an unencrypted, but signed message and it worked correctly (at least
>    according to alot it was valid--I tried to just copy the content between
>    the first two "boundaries" in the raw message and verify that it against
>    the signature below, but gpg was telling me the signature was invalid, but
>    at least from the correct key--maybe I'm just making a mistake here having
>    not worked with multipart/signed content before).

PGPMIME is tricky and the sig is not just over the "body" text part but
over the whole message.


>    Anyway, while trying to debug this I did also notice this as a strange
>    behavior:
> 
>  >>> plaintext = "hail seitan"
>  >>> detach_sig = alot.crypto.detached_signature_for(plaintext, alot.crypto.get_key("68A6AA0A"))[1]
>  >>> plaintext = "hail seitan"
>  >>> signature = alot.crypto.detached_signature_for(plaintext, alot.crypto.get_key("68A6AA0A"))[1]
>  >>> alot.crypto.verify_detached(plaintext, signature)
>  [<gpgme.Signature object at 0x7f8b8cb0a138>]
>  >>> plaintext = "jajaja"
>  >>> alot.crypto.verify_detached(plaintext, signature)
>  [<gpgme.Signature object at 0x7f8b8cb0a190>]
> 
>    Shouldn't it be raising a GPGProblem in the second verify example?


I belive the pydocs for this function are misleading. Checking the code
it seems that "if it fails" means that some internal gnupg error
occurrs, not that the signature mismatches the plaintext.

If that happens, the function successfully returns some
gnupg object, from which one can determine (via the gnupg api) if the 
signature is invalid or valid. It's a hack, I agree.

**Comment by dcbaker** [comment]
I believe this is fixed in master now (there's been a bunch of gpg work recently), if not please re-open.
