### ISSUE TITLE
Attachments with utf8 filenames

### ISSUE THREAD

**Issue by josch** [pazz/alot#879]
Hi,

I recently tried to attach a file with an umlaut in the file name to an email. Turns out that neither me (using notmuch) nor the receiving end (using thunderbird) saw the attachment of the email. Here is the email that alot constructed:

```
Content-Type: multipart/mixed; boundary="===============8526373729717649192=="
MIME-Version: 1.0
To: josch@mister-muffin.de
Message-ID: <146788320497.11198.5117159613429899772@localhost>
From: Johannes Schauer <josch@mister-muffin.de>
User-Agent: alot/0.3.6
Subject: test
Date: Thu, 07 Jul 2016 11:20:04 +0200

--===============8526373729717649192==
Content-Type: text/plain; charset="utf-8"
MIME-Version: 1.0
Content-Transfer-Encoding: quoted-printable

blub

--===============8526373729717649192==
Content-Type: text/plain; charset="utf-8"
MIME-Version: 1.0
Content-Transfer-Encoding: quoted-printable
Content-Disposition: =?utf-8?q?attachment=3B_filename=3D=22umlaut=5Ftest=5F?=
 =?utf-8?b?w6QudHh0Ig==?=

blubber

--===============8526373729717649192==--
```

I suspect that something is wrong with the `Content-Disposition` header?

**Comment by pazz** [comment]
it looks OK to me, but I believe there should not be a newline

**Comment by josch** [comment]
Agreed. I don't think anybody expects the `Content-Disposition` header to be multiline.

**Comment by dcbaker** [comment]
I thought this was a different issue. I can attach unicode file name files as long as I don't try to encrypt them. Please re-open if this bug is still relevant.
