### ISSUE TITLE
notmuch-tag-like tagging of emails (smart retag)

### ISSUE THREAD

**Issue by xiroV** [pazz/alot#890]
Hi!

I don't know if this is already possible somehow, but otherwise I would really like it as an additional feature.
When you tag email in alot, you have the options to `:tag`, `:retag` and `:untag` emails.
However, to be honest, I really enjoy the way `notmuch tag` works, where you can do both `tag` and `untag` in the same command, e.g. `notmuch tag +junk -inbox` (adding tag `junk` and removing tag `inbox`)

Is there anything I've missed which already makes this possible? And if not: Would this be a nice feature to have?

I haven't studied the code of alot, but if others think that this would be handy, I wouldn't mind trying to implement it.

This could either be implemented as:
- a switch-like setting in the config like "notmuch_like_tagging = true", overwriting the default `tag` command, or
- a new command, like `:smart_tag`, alongside the current commands

Where I'm guessing the last one would be the best.

Looking forward to hear your thoughts, and please tell me if this already exists.

Best.
Brian

**Comment by pazz** [comment]
Hi Brian, welcome to alot.
You can already achieve this, although not in the same syntax
by simply chaining two commands:

  tag foo,bar; untag baz

HTH, & best wishes,
P

Quoting Brian Alberg (2016-08-20 23:17:05)

**Comment by teto** [comment]
This can be closed I think ?
