### ISSUE TITLE
\t gets replaced by spaces when sending

### ISSUE THREAD

**Issue by xunam** [pazz/alot#892]
Hi,

Yesterday I noticed that any occurrence of backslash-t in a composed mail, although displayed correctly in envelope mode, gets replaced by 4 spaces when sending. Both the copy of the message that is stored in the local maildir and the message that is sent have spaces, so the substitution does happen inside alot. I tried composing a message with all backslash-letter combinations and \t is the only one that gets this special treatment.

The problem occurs with an up to date version extracted from git master (commit 747b894).

**Comment by pazz** [comment]
I believe this is a feature: the docs just before the offending line
https://github.com/pazz/alot/blob/master/alot/db/envelope.py#L174
mentions some RFC and i think it was related to creating correct MIME-trees (well formated emails)
for use with PGPMIME encrypting/signing

**Comment by xunam** [comment]
I do believe it is a bug.

I just skimmed the RFC and there does not seem to be any mention of a special treatment for tabs nor the particular sequence backslash-t. The RFC is just about putting the contents of messages in MIME canonical form before signing. Besides, replacing backslash-t by four spaces (or even by an actual tab) is surely not a canonicalisation procedure since it changes the contents of the text. Even replacing tabs by sequences of four spaces (i.e. what would be achieved with `'\t'` instead of `'\\t'`on that line of code) would change the text contents in a non-canonical way.

Besides, when I type `\t` in the body of an email when composing, I do want to send `\t`, whatever the machinery used for building MIME messages behind the scenes...

**Comment by pazz** [comment]
Oh you really want "    " in your text? sorry, I misunderstood.
And yes, I am happy to push a patch that changes the behaviour such that
the canonization only happens when building a signed message.

**Comment by xunam** [comment]
No, I do not want spaces in my text where I type `\t`, I want a backslash followed by a lowercase t.

I believe that pushing a patch such that backslash-t gets replaced by four spaces only in the case of signed messages is not a reasonable option since it does not fix the bug: one should not change the text that is provided by the user, whether it is signed or not. Issues of canonicalization and content encoding are orthogonal to this. Maybe some content encoding format chokes on the backslash-t sequence for some weird reason, but then this bit of text should be properly quoted according to the specification of the encoding. In any case, the actual content (the one that is typed in and displayed) must not be modified.

**Comment by pazz** [comment]
Understood and agreed :)
making this search&replace command conditional on the mail begin
singed/encrypted should be no big issue. Care to send a PR?

**Comment by xunam** [comment]
Well, the pull request #901 is the only sensible thing I can come up with, but it only consists in removing the spurious substitution (unconditionally).
