### ISSUE TITLE
Unexpected behaviour flushing changes

### ISSUE THREAD

**Issue by workboot** [pazz/alot#895]
Hi all,

I am trying to make use of the alot objects for some maintenance scripts. When executing the following example:
```python
#!/bin/python2
from alot.db.manager import DBManager
from alot.settings  import settings
from os.path import expanduser

"""
settings object required (deliberately?) by
	flush function from DBManager:
		sync = settings.get_notmuch_setting('maildir', 'synchronize_flags')
	where settings is not configured inside DBManager
"""
settings.read_notmuch_config(expanduser("~")+"/.notmuch-config")
indexpath = settings.get_notmuch_setting('database', 'path')
man   = DBManager(path=indexpath,ro=False)


query = "tag:notify" #use tag that exists already
man.untag(query,"notify") #untag messages

# gather information before flushing
count_before = man.count_messages(query)
queue_before = len(man.writequeue)

DBManager.flush(man) #flush changes

# gather information after flushing
queue_after = len(man.writequeue)
count_after = man.count_messages(query)

# output
out_count_msg   = ("Number of messages\n\n"
                   "  Before: {:}\n"
                   "  After:  {:}")
out_count_queue = ("Writequeue items\n\n"
                   "  Before: {:}\n"
                   "  After:  {:}")

print(out_count_msg.format(count_before,count_after))
print("\n------\n")
print(out_count_queue.format(queue_before,queue_after))
```

The output is:

```bash
Number of messages

  Before: 132
  After:  132
------

Writequeue items

  Before: 1
  After:  0
```

I conclude that a writequeue is getting created and as well flushed, no exceptions are thrown. However as seen in the output, no changes are applied to the database. For me this is an unexpected behaviour in comparison to the [documentation](http://alot.readthedocs.io/en/latest/api/database.html). Comments are very welcome!

**Comment by workboot** [comment]
I finally found the culprit: the `untag` method of `DBManager` takes a **list of tags** which is nicely mentioned in the [documentation](https://alot.readthedocs.io/en/latest/api/database.html#alot.db.manager.DBManager.untag) but which I didn't follow:

> tags (list of str) – a list of tags to be added

`DBManager` should though throw some exception when it is not able interpret the writequeue.  Shouldn't it? Below is the log output when **failing**

```log
DEBUG:root:write-out item: ('untag', None, 'tag:notify', 'notify')
DEBUG:root:cmd created
DEBUG:root:got write lock
DEBUG:root:got atomic
DEBUG:root:ended atomic
DEBUG:root:ended atomic
DEBUG:root:closed db
DEBUG:root:flush finished
```

and this is the successful log which is not really distinguishable

```log
DEBUG:root:write-out item: ('untag', None, 'tag:notify', ['notify'])
DEBUG:root:cmd created
DEBUG:root:got write lock
DEBUG:root:got atomic
DEBUG:root:ended atomic
DEBUG:root:ended atomic
DEBUG:root:closed db
DEBUG:root:flush finished
```

**Comment by pazz** [comment]
Thanks for the bughunt.
I'm not sure that it'd be a good idea to add a check and raise an exception here
(after all strings behave like lists of chars) and the function is
inteded for internal use mostly and documented..
Let's leave it as it is for now.
Best,
P

Quoting Fabian (2016-10-15 18:21:35)
