### ISSUE TITLE
Message header ordering isn't preserved from the editor

### ISSUE THREAD

**Issue by BlacklightShining** [pazz/alot#898]
Okay, so this is _really_ minor. It's also (probably) really easy to change, though! Headers are currently stored internally in a `dict`, which doesn't preserve ordering; Python provides `collections.OrderedDict`, which does. As far as I know, you can just use it as a drop-in replacement.

**Comment by pazz** [comment]
Quoting Blacklight Shining (2016-10-02 15:28:24)
>    Okay, so this is really minor. It's also (probably) really easy to change,
>    though! Headers are currently stored internally in a dict, which doesn't
>    preserve ordering; Python provides collections.OrderedDict, which does. As
>    far as I know, you can just use it as a drop-in replacement.

Yes but why would you want to? The header ordering is completely
irrelevant is it not?

**Comment by BlacklightShining** [comment]
For the most part, yeah, at least before the message goes through MTAs and gets trace headers added to it (which [MUST NOT](https://tools.ietf.org/html/rfc2119) be reordered). Like I said, really minor issue.

**Comment by pazz** [comment]
ok, I'm open for pull requests on this of course :)

**Comment by pacien** [comment]
Standard `dict`s are now officially ordered since Python 3.7.
For some reason, headers still seem to be shuffled when composing a message, even with this version of the Python interpreter.

**Comment by pazz** [comment]
can you be a little more precise as to which two header lists you are comparing? pre/post edit header values listed in envelope buffers?

**Comment by pacien** [comment]
envelope buffer -> `:edit` -> editor: headers are shuffled
editor -> save and quit -> envelope buffer: the order is kept

Headers seem to be randomly re-ordered each time I compose a new message, either with `:compose` or using the command line sub-command:

```
❯ alot compose --sender 1 --to 2 --subject 3
To: 2
From: 1
Subject: 3

❯ alot compose --sender 1 --to 2 --subject 3
Subject: 3
To: 2
From: 1

❯ python --version     
Python 3.7.4

❯ alot --version                            
0.8
```

**Comment by pazz** [comment]
gotya. I don't have a solution for you but I can point to the code that results in the observed behaviour:
https://github.com/pazz/alot/blob/master/alot/commands/envelope.py#L385
and
https://github.com/pazz/alot/blob/master/alot/db/envelope.py#L322.

What happens is that alot will determine, based on your config, which headers will be edited. Those will be removed from the dictionary, turned into part of the template send to the editor, and afterwards re-interpreted and added to the dictionary (at the end).
