### ISSUE TITLE
Unit Tests

### ISSUE THREAD

**Issue by dcbaker** [pazz/alot#917]
Okay, lets discuss writing unit tests, since it sounds like we agree that is probably the next major milestone for alot.

Here's some thoughts I have from experience writing a lot of unit tests, and writing unit tests for a fairly mature project. Writing a ton of new unit tests is a daunting amount of work, but writing them incrementally here and there is much easier. I'd suggest that new features should be required to come with unit tests immediately, and that the tests are reviewed and part of the review process. I also suggest that we turn on unit tests in travis immediately, and enforce a policy of no unit test breaks across a series (since that makes bisecting hard). It may also be worth breaking out the unit test milestone into smaller chunks if we want to track it (say per module or per feature) with a milestone target, though I don't know how much of that kind of tracking we want to do.

The second thing I'll suggest is not using the built in unittest module for writing the tests. I've written a *lot* of tests, with unittest, nose, nose2 and pytest. I will say of those pytest is by far the best, nose2 is next (though last time I used it it was immature), nose, and then the builtin unittest module. The thing that makes pytest the best is that it is the most "batteries included" of the ones I've used, and removes the need to write a lot of boilerplate. I don't think its a problem (within reason) to pull in dependencies for testing. Mock is another module that is *incredibly* useful for writing good unit tests, though it's a bit tricky to know when to use mock.

Also, I think it would be worth while for some of us newer contributers to work on the unit tests since it will force us to learn more of the code base.

**Comment by zenhack** [comment]
Quoting Dylan Baker (2016-12-12 14:30:42)

>    The second thing I'll suggest is not using the built in unittest module
>    for writing the tests. I've written a lot of tests, with unittest,
>    nose, nose2 and pytest. I will say of those pytest is by far the best,
>    nose2 is next (though last time I used it it was immature), nose, and
>    then the builtin unittest module. The thing that makes pytest the best
>    is that it is the most "batteries included" of the ones I've used, and
>    removes the need to write a lot of boilerplate. I don't think its a
>    problem (within reason) to pull in dependencies for testing. Mock is
>    another module that is incredibly useful for writing good unit tests,
>    though it's a bit tricky to know when to use mock.

I'm actually *really* not a fan of pytest. I've used it for a number of
projects, including things that I've maintained for years, and my
experience is that while it's really nice when you're getting started,
it gets to be a pain as you try to do more with it. There is generally
too much magic. It breaks namespacing in a number of places, which makes
maintaining fixtures in a module a pain. If the library itself doesn't
have a thing you need, it's often a real pain to build it and get it to
work with everything else.

I can't comment on nose/nose2 as I haven't really used them, though
nose(1) looks to be unmaintained.

`unittest` is rather verbose, and basically feels like someone blindly
copied what java was doing. I do like that there's rather less magic
than pytest though.

[Attest][1] looks nice from the outside, but I haven't spend much time
with it.

[1]: https://pythonhosted.org/Attest/

**Comment by dcbaker** [comment]
> I'm actually *really* not a fan of pytest. I've used it for a number of projects, including things that I've maintained for years, and my experience is that while it's really nice when you're getting started, it gets to be a pain as you try to do more with it. There is generally too much magic. It breaks namespacing in a number of places, which makes maintaining fixtures in a module a pain. If the library itself doesn't have a thing you need, it's often a real pain to build it and get it to work with everything else.

I haven't used it for as long as you have clearly, but I've never run into any of the problems you have. I know that there is a lot of... disagreement about the level of magic in pytest. Maybe I just haven't used enough of the more magical features to have problems.

> I can't comment on nose/nose2 as I haven't really used them, though nose(1) looks to be unmaintained. 

Yes, nose1 is unmaintained, and nose2 is still fairly immature and (IMHO) is trying too hard to copy ruby's rspec without the language features that make rspec really nice to work with. I'm really not impressed.

>`unittest` is rather verbose, and basically feels like someone blindly copied what java was doing. I do like that there's rather less magic than pytest though.

Actually, that's exactly what `unittest` is. And that's part of what makes it so painful to deal with. The camal case names annoy me, but they're not the end of the world; but the boilerplate is frustrating, and the lack of nose1 generators or pytest.mark.parametrize for tests is also quite frustrating.

I'll have a look at atest.

**Comment by toogley** [comment]
What about the naming schema? For instance: in Java,  I personally liked tests like:

```
public void DeleteData_InvalidTableName(){
``` 

because it clearly shows the difference between what kind of unit is currently tested and what scenario of that unit is tested.

**Comment by dcbaker** [comment]
> What about the naming schema? For instance: in Java, I personally liked tests like:

In pytest I like using classes (and nested classes) as namespaces that describe the module, class, method and scenario, which looks something like this:

```python
class TestGPG(object):
    class TestEncrypt(object):
        class TestTo(object):
            def test_key(self): pass
            def test_no_key(self): pass
            def test_invalid_key(self): pass
        def test_is_encrypted(self): pass
```

Honestly whatever scheme we pick though is fine with me, as long as we're consistent and the naming scheme is descriptive somehow (no "test1", "test2" kind of stuff). I'm not sure how well nested classes work in `unittest` or `atest`.

**Comment by lucc** [comment]
I have heard that pytest can run unit tests. So would it be possible to use pytest (and mostly write pytests) and in some cases where the magic bites us we throw in a unittest?

I started to rebase the old travis PR. Soon I can offer you a new one on top of master (which already checks the docs on travis). I think the tests should run in a different travis job than the doc checks (long install times and potentially long test runs). Or what do you think?

**Comment by zenhack** [comment]
Quoting Lucas Hoffmann (2016-12-13 03:21:58)
>    I have heard that pytest can run unit tests. So would it be possible to
>    use pytest (and mostly write pytests) and in some cases where the magic
>    bites us we throw in a unittest?

The main thing that gets annoying is the clumsiness of trying to build
reusable fixtures. But yes, it will pick up unittest style tests and run
them.

**Comment by dcbaker** [comment]
It's been rather quiet here. I'm hoping to bump the conversation a bit, since gettings tests landed is important.. I've submitted a pull request that implements some tests as unittests and then ports them to pytest as a second commit. Does anyone have thoughts or comments on which they like better or issues with either approach?

**Comment by lucc** [comment]
Can we take [@pazz comment](https://github.com/pazz/alot/pull/934#issuecomment-268881982) as authoritative? As [I said](https://github.com/pazz/alot/pull/934#issuecomment-268761662) I can not help with this decision much but will support any outcome.

**Comment by lamarpavel** [comment]
A bit of input from someone who has not contributed much to alot, but uses it all day:

As important as a (nearly) complete coverage with tests is, the priority right now should be to get the essential and critical parts of alot tested without much hassle. Another project, I'm following closely and that I have contributed some tests to was pretty much on hold for about one year trying to get good test coverage and much has been learned in that time. You can get a pretty good picture of that that looks like by browsing the [related issues](https://github.com/The-Compiler/qutebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20tests). This is python as well and due to the nature of the project, some of the tests were very difficult to get right. Unfortunately, my main insight gained from following the development there is that automated tests can create a huge amount of friction that has less to do with writing the actual tests and more with the proper execution of multiple tools for multiple stages of testing.

For alot we can avoid the trouble of testing on Windows and also don't have to worry about a Qt-GUI. And since alot delegates fetching and sending mail to other tools, we also don't have to deal with connection issues for now. We should consider that part of alot might also be to give helpful feedback when those other tools fail, which might require setting up some dummy mail server etc, but that is not essential right now.

The point I'm trying to make is that there is value in doing something not the best possible way imaginable with all the tools available, but starting simple and building up a base that does not cause too much friction. Even with the knowledge that eventually we might have to switch to a different testing suite and re-write some tests, starting simple can be more productive long term. As such, I very much share the sentiment of @pazz in the above linked comment.

P.S.: I encourage you to look through the issues of qutebrowser that I linked, @The-Compiler has spent so much time setting up tests and it's all documented.

**Comment by The-Compiler** [comment]
Hi! As @lamarpavel said, I spent a lot of time writing tests for qutebrowser and think it was really worth it.

FWIW, I can really suggest using [pytest](https://www.pytest.org/) - it makes writing tests a lot (hah!) easier, and I ended up liking it enough to contribute to it and ended up being one of its maintainers. It also comes with a lot of [third-party plugins](http://plugincompat.herokuapp.com/) which might come in handy.

**Comment by lucc** [comment]
I reviewed the discussion and it seems that these are the main points (I checked those that are decided):

* [x] we want test (we start to have some :)
* [x] decide which framework; currently we use `unittest`; any change to that has to go into a new discussion
* [ ] a plan what has to be tested and who has to write tests when
  * [x] incrementally add tests for the current code base (we are doing it)
  * [ ] require new features to come with tests? (not yet officially mentioned anywhere)
  * [ ] require all new series of commits to never fail a test? (to ease bisecting)
  * [ ] some coding/naming style for tests?

So the open points are about the organizational matters how we write tests.

**Comment by pazz** [comment]
"require all new series of commits to never fail a test?"  I think this is just common sense. yes. new PR's should not break existing tests unless there is a good reason and the PR itself comes with a replacement test.

" require new features to come with tests?"  This would certainly put people (like me) off. I'd welcome tests but not make them a formal requirement. 

"some coding/naming style for tests?" no opinion on that.

**Comment by lucc** [comment]
@pazz you mention the "never fail" and "add new tests". I understood @dcbaker in the initial comment the other way round as you list them: Every new feature PR should be covered with tests. The tests should be added as early as possible in the series of commits. As soon as they are added they must not fail on any following commit in that PR (including the commit that introduced the tests).

The rationale behind this is that using `git bisect run python2 setup.py test` with code that breaks the tests in one commit just to fix them one or two commits later can lead to wrong answers about which commit introduced a failure.

**Comment by pazz** [comment]
Yes, I agree with this. All I'm saying is that PR's *should* but not *must* come with tests.
If they do, then I agree that tests should come upfront.
But I personally would not reject a great PR for the lack of tests, but that's just me.

**Comment by dcbaker** [comment]
Requiring tests is a good idea, but I understand where pazz is coming from. Some things are very hard to test and writing good tests is an art. I think we might want to update the developer docs that tests are strongly recomended and that providing tests will probably help your code land faster.

No patch should regress a test. If the test is wrong include a patch to remove or fix it, then fix the code. If the test is obsoleted by the patch, it should be removed.

As for style, we're using PEP8 now, so lets just keep doing that.

**Comment by pazz** [comment]
Cool, so we seem to agree here. Should we update the docs as to guiding
future collaborators and then close this issue?

**Comment by lamarpavel** [comment]
>Should we update the docs as to guiding future collaborators and then close this issue?

I would create a new issue with a checklist of all modules that require testing, as seen here: https://github.com/The-Compiler/qutebrowser/issues/999

Marking some as `easy` helps motivating contributers to write their first test or even profive an entry point for new contributers.

**Comment by lucc** [comment]
@lamarpavel go for it!

**Comment by lamarpavel** [comment]
Can do, but it will take some time since I don't have any overview of the code.

**Comment by lamarpavel** [comment]
So, I've created such a list, but I do need a bit of help marking those, that would be easy. Also, I'd like to give a measurement of progress so that one can see which modules are close to complete, any suggestions? Qutebrowser is using tools to analyze this, but setting up CI toolchains is not a domain I am familiar with at all. Maybe there could be a simpler measurement like "_Is every function of every class covered by at least one test?_".

**Comment by dcbaker** [comment]
With #1021 opened, lets move any further discussion there.
