### ISSUE TITLE
Migration to python-gpg

### ISSUE THREAD

**Issue by toddy15** [pazz/alot#950]
Hi,

the python wrapper "pygpgme" is abandoned upstream and unmaintained. It would be better to switch to the new python wrapper maintained by the gpgme upstream developers. This wrapper has been released just a few months ago in September 2016. You'll find more information in their blogpost:

https://www.gnupg.org/blog/20160921-python-bindings-for-gpgme.html

... and this is the package on pypi:

https://pypi.python.org/pypi/gpg

Thanks for considering!

**Comment by lucc** [comment]
Thanks for the info but pazz already started it some time ago: #915

**Comment by toddy15** [comment]
Oh, that's great, thanks for the pointer. I've just searched in the issues, not the pull requests, so I did not spot there's already an effort going on. All the better!
