### ISSUE TITLE
update zsh completion

### ISSUE THREAD

**Issue by pazz** [pazz/alot#960]
https://github.com/pazz/alot/blob/master/extra/completion/alot-completion.zsh#L11

to propose the newly exposed subcommands in #944 
IIRC, this could be done better now that we use argparse (there was some way to let zsh inspect the argparse code itself)..

**Comment by lucc** [comment]
I am not sure about autogenerating zsh completion form argparse code. All I have found until now are some third party modules that can be used as a drop in for argparse and then do the completion for you. Is there really something vanilla way?

I will open a small PR to fix the completion manually as I consider that important for 0.5. But we can still discuss automation ideas.

**Comment by pazz** [comment]
Quoting Lucas Hoffmann (2017-01-24 10:38:29)
>    I am not sure about autogenerating zsh completion form argparse code. All
>    I have found until now are some third party modules that can be used as a
>    drop in for argparse and then do the completion for you. Is there really
>    something vanilla way?

I thought so, but after some research I also found nothing nice. So
let's hardcode stuff for now shall we?

**Comment by lucc** [comment]
ok
