### ISSUE TITLE
'd' and subcommands

### ISSUE THREAD

**Issue by dcbaker** [pazz/alot#968]
If alot is started with a subcommand (I noticed this with compose), and `d` is pressed, it will prompt to close without saving, but doesn't actually close. Presumably either we shouldn't allow `d` or we should make it work correctly.

**Comment by pazz** [comment]
Quoting Dylan Baker (2017-01-13 23:48:15)
>    If alot is started with a subcommand (I noticed this with compose), and d
>    is pressed, it will prompt to close without saving, but doesn't actually
>    close. Presumably either we shouldn't allow d or we should make it work
>    correctly.

This is a bug that I cannot reproduce.
If I start `alot compose`, and get through to a singel envelope buffer
in the ui, and then press `d`, I get the prompt you mention
and upon confirming I get a new prompt:

```
quit without sending message? [y]:yes (n):no
```

Confirming this, the UI terminates.

**Comment by dcbaker** [comment]
Interesting, I get the prompt, but when I type 'y' the UI doesn't quit, although pressing 'q' does cuase it to quit, as expected. I can reproduce this in the 0.4 release as well.

For reference, here is the commandline I'm using:
```
python2 alot/__main__.py -l dev.log -d debug compose --sender=me@example.com --subject=to --to=foo@example.com 
```

**Comment by dcbaker** [comment]
Looking through my logs this seems relevant:
```
DEBUG:ui:Got key (['d'], [100])
DEBUG:ui:cmdline: 'bclose'
DEBUG:ui:envelope command string: "bclose"
DEBUG:__init__:mode:envelope got commandline "bclose"
DEBUG:__init__:ARGS: [u'bclose']
DEBUG:__init__:cmd parms {'redraw': None, 'force': False}
DEBUG:ui:Got key (['y'], [121])
INFO:globals:not closing last remaining buffer as global.quit_on_last_bclose is set to False
DEBUG:ui:Got key (['d'], [100])
DEBUG:ui:cmdline: 'bclose'
DEBUG:ui:envelope command string: "bclose"
DEBUG:__init__:mode:envelope got commandline "bclose"
DEBUG:__init__:ARGS: [u'bclose']
DEBUG:__init__:cmd parms {'redraw': None, 'force': False}
DEBUG:ui:Got key (['y'], [121])
INFO:globals:not closing last remaining buffer as global.quit_on_last_bclose is set to False
```

So, it looks like to fix this issue we should force `global.quit_on_last_bclose`to True when using a subcommand?

**Comment by pazz** [comment]
Ah ok, that makes sense. This is also the behaviour I expect, so not really a bug.
Maybe there should be a `ui.notify` that tells you that  `global.quit_on_last_bclose` is set to False and that therefore, this buffer is not closed..
I actually set it to true in my config and incorrectly assumed this was the default.

In any case, if that config setting is set to true, I actually get asked twice, once by `BufferCloseCommand` and once by `ExitCommand`. There is probably a nicer way to do this.

**Comment by dcbaker** [comment]
Maybe if we're on the last buffer and `BufferCloseCommand` is called it notifies if `global.quit_on_last_blclose` is `False`, otherwise it just calls `ExitCommand`? I could work on that change if you like.

**Comment by pazz** [comment]
Quoting Dylan Baker (2017-01-17 22:21:25)
>    Maybe if we're on the last buffer and BufferCloseCommand is called it
>    notifies if global.quit_on_last_blclose is False, otherwise it just calls
>    ExitCommand? I could work on that change if you like.

Be my guest :)
It should be nice to prevent the "double nagging" described above as
well..
