### ISSUE TITLE
__future__ imports

### ISSUE THREAD

**Issue by dcbaker** [pazz/alot#969]
In order to get ready for python3.x support, it would be usful to enable some of the __future__ imports in alot, there are 3 that should be fairly trivial to implement correctly: `__future__.division`, `__future__.absolute_import` and `__future__.print_statement`.

**Comment by lucc** [comment]
I have a patch for \_\_future\_\_.print_**function**. I did not know there was a print_statemant in `__future__` as well. But if there is such a thing I still think it is better to use print_funtion as it will make the transition easier later.

**Comment by lucc** [comment]
It is #971.

In general I am all for splitting the py3 work across multible PRs and even merge all the stuff that is also py2 compatible as soon as possible! So good idea.

I did some work on imports not so long ago in fe748a7f47fb61d46dd88c270c2329e6ff19a895 and 571422a079ce235eba738ccfeac1ca2f043ece23. Maybe that will make the absolute_import stuff as simple as adding one line to each file that imports something. (Or should we only add the line to files that import stuff from our code base or to all files, even empty ones?)

**Comment by dcbaker** [comment]
Lol, yes print_function

I'm on mobile, please excuse autocorrect fail.

**Comment by pazz** [comment]
Right: we don't use prints, future division is #1012 and future.absolute_imports is #984.
Can we close this issue?

**Comment by lucc** [comment]
According to https://docs.python.org/2/library/__future__.html there also is the bytes literal stuff. Do we have any use for that?

(The 3 @dcbaker mentioned where only the easy ones as I read it, but it might also be all of them)

**Comment by pazz** [comment]
BTW: I created a new milestone for the py3k stuff. Since I don't really know what else is necessary to port, feel free to add issues to that milestone as you see fit.

**Comment by dcbaker** [comment]
I don't think that we want to use unicode_literals. It's nice for pojects that need to support python 2 and python 3 and want to have python2 behave like python 3. I'm going to close this since I think this is done.
