### ISSUE TITLE
str, bytes, and unicode

### ISSUE THREAD

**Issue by dcbaker** [pazz/alot#970]
Of all the changes between python 2 and 3 the bytes/unicode/str change is the hardest and the most obnoxious to port if care hasn't been taken to ensure that they are not interchanged in a python 2 code base. Alot unfortunately relies on python2's coercion of types in this regard. Preparing for python 3 we should stop that, each function that takes a string type should only accept one type or the other, and we should use asserts to guard against passing the other type.

My experience from porting other complex code bases is that this is going to be by far the hardest thing to get right, and the most time consuming.

**Comment by pazz** [comment]
sorry to be forgetful/ignorant: This seems to be the last hurdle for python3 support. where do we stand here? I recall some people mentioning that they already successfully run alot on py3k..

**Comment by dcbaker** [comment]
This is the last big hurtle for py3k yes, there may be some small ones other than this, but those should be pretty easy to iron out.

**Comment by lucc** [comment]
but 2to3 fixes stringio for me. If I run 
```sh
git checkout master
2to3 -wn alot
PYTHONPATH=. python3 -m alot
```
I get this traceback:
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/luc/vcs/alot/alot/__main__.py", line 137, in <module>
    main()
  File "/home/luc/vcs/alot/alot/__main__.py", line 128, in main
    UI(dbman, cmdstring)
  File "/home/luc/vcs/alot/alot/ui.py", line 121, in __init__
    self.apply_commandline(initialcmdline)
  File "/home/luc/vcs/alot/alot/ui.py", line 253, in apply_commandline
    for cmdstring in split_commandline(cmdline):
  File "/home/luc/vcs/alot/alot/helper.py", line 50, in split_commandline
    return list(lex)
  File "/usr/lib/python3.6/shlex.py", line 295, in __next__
    token = self.get_token()
  File "/usr/lib/python3.6/shlex.py", line 105, in get_token
    raw = self.read_token()
  File "/usr/lib/python3.6/shlex.py", line 136, in read_token
    nextchar = self.instream.read(1)
AttributeError: 'bytes' object has no attribute 'read'
```

**Comment by dcbaker** [comment]
Yeah, and there's more than 2to3 will handle, that's one of them. I have a py3k branch I pushed to github that gets further along (In that case it needs a `str` not a `bytes`, but there are a lot of cases where we accept either `bytes` or `str` (python 3 types) that need to explicitly accept only `str`.

**Comment by lucc** [comment]
I think that can be closed now. Or do we still want some asserts about string types?

**Comment by pazz** [comment]
I'll close this here. #1055  is merged and we can open new issues when they arise.
