### ISSUE TITLE
Tip for iTerm users: Mouse button bindings work with mouse tracking is disabled

### ISSUE THREAD

**Issue by fnurl** [pazz/alot#974]
I just noticed that even with mouse tracking disabled, the mouse ~~buttons bindings (mouse 4, 5 to up/down)~~ works when I use `alot` directly under iTerm2 (Mac OS). Using `alot` through tmux does not retain this behaviour.

*Update: I discovered that this is because you can set (and it is set as default) that the scroll wheel sends arrow keys in "alternate mode" whatever that is.*

This means that you can get both the possibility to select text and use the scroll wheel. The down side is that in iTerm2 (at least for me) I have to turn off mouse tracking since the "hold the shift key" workaround for selecting text does not seem to work.

You can turn off mouse tracking by adding

```
handle_mouse = False
```

to your config file

**Comment by pazz** [comment]
OK? good to know I suppose :)
