### ISSUE TITLE
Missing warning or notice on missing mailcap command

### ISSUE THREAD

**Issue by lucc** [pazz/alot#987]
Put this in your mailcap file:
```mailcap
text/html; command_to_render_html_not_found %s; copiousoutput;
```
and then open alot and try to read a mail that is html. For me I get the header in the thread view but the body is empty (zero lines). 

I would prefer it if alot would display a warning or notification if the command can not be found. Maybe we should only display the error once when the thread buffer is opened as it might be a little intrusive on long threads with lots of html mail.

The mailcap entry is executed with `alot.commands.globals.ExternalCommand` and there already is a code path for failed commands in [line 256](https://github.com/pazz/alot/blob/master/alot/commands/globals.py#L256) but it seems to have no effect or is not reached in this case.

**Comment by dcbaker** [comment]
There's some pretty strange handling of `subprocess.Popen` in there, since we're calling both `.wait` and `.communicate`, which is strange.

**Comment by dcbaker** [comment]
This problem is in `alot.utils.extract_body` which has no access to the UI (since the HTML conversion isn't done by calling ExternalCommand. I looked over it a bit and there wasn't an immediately obvious fix.

**Comment by pazz** [comment]
close due to #1187. Although the solution is not ideal, the original issue (here) is fixed.
