### ISSUE TITLE
Regression: cannot paste with middle mouse button anymore

### ISSUE THREAD

**Issue by josch** [pazz/alot#995]
Hi,

often I want to paste some text into the alot command bar from somewhere else. On linux I use the Xorg paste buffer for that purpose where I copy by selecting and paste with my middle mouse button.

Unfortunately it seems that commit 83826eedcc14205fb3a14402c704ecbfd64d7466 removed that ability.

Please consider restoring it.

**Comment by pazz** [comment]
You can disable this behaviour per config setting!
I believe it was `hangle_mouse = False`.

#close

**Comment by josch** [comment]
For what it's worth, the configuration setting is `handle_mouse = False` and you can have the best from both worlds by leaving the setting enabled but pasting with the middle mouse button and holding shift.

**Comment by josch** [comment]
Ugh... I cannot even copypaste anything from emails anymore. Why is the default of this setting set to True?

**Comment by dcbaker** [comment]
I agree, I think handle_mouse should default to False

**Comment by josch** [comment]
Alternatively, maybe it is possible to have the best from both worlds? Marking and insertion with the mouse *and* scrolling? But a quick browse of the urwid code lets me believe that you only get all or nothing in terms of mouse button handling. Maybe somebody knows a workaround?

**Comment by dcbaker** [comment]
Well, urwid by default ignores most mouse input. I think it's possible to make handle_mouse do what we actually want (allow scrolling with the mouse but not break middle clock insert or selecting), but I haven't dug into it enough to know for sure.

**Comment by pazz** [comment]
@dcbaker: paste with middle-click could be simulated using a call to xpaste, but simulating the selection would be trickier. I'd be OK with defaulting to `handle_mouse = False`.

**Comment by dcbaker** [comment]
@pazz will calling xpaste work with wayland? My laptop has a hidpi (greater than 1080p) display, and wayland is a hard requirement for me (not to mention just all around better than X). Is it not possible to tell urwid to handle some mouse events but let others fall through unhandled?

**Comment by pazz** [comment]
Quoting Dylan Baker (2017-01-24 17:17:48)
>    [1]@pazz will calling xpaste work with wayland?

Good question, I don't know. But I'd suspect that there is a similar
tool for wayland as well.
But in any case, I think this is a user config issue and should probably
not be implemented in alot itself.

>    Is it not possible to tell urwid to handle some mouse events but let others fall through unhandled?

I don't think so.

**Comment by dcbaker** [comment]
Actually, I don't think there is a similar tool, I think the compositor has to handle the middle click becasue of the security model of wayland.
