### ISSUE TITLE
Regression: closes logfile during startup

### ISSUE THREAD

**Issue by josch** [pazz/alot#996]
Hi,

the following workflow for debugging alot used to work. In one terminal do:

    $ mkfifo myfifo
    $ cat myfifo

And then in another terminal run:

    $ PYTHONPATH=$PWD python -m alot --logfile=myfifo --debug-level=debug

Now I would get all the debug output of alot in the first terminal without any temporary files.

Unfortunately this workflow was broken by commit 2d7d048f3e2eb33b20944d307a998abe09f2329b which seems to close the logfile right after startup.

**Comment by dcbaker** [comment]
I have a patch series that addresses that problem (I think). I'll dust it off and send a pull request

**Comment by lucc** [comment]
What about doing `$ PYTHONPATH=$PWD python -m alot --logfile=plainfile --debug-level=debug` and then `$ tail -f plainfile` in the other terminal?

Or did you try to open the pipe for reading after starting alot? (The logfile is closed once after parsing the command line and then reopened for logging.)

**Comment by josch** [comment]
I open the pipe before starting alot. Doing it the other way around will probably not loose any logging data because alot will block until somebody starts reading from the other end of the pipe. But if I can freely choose which way round I start both processes, then why would I let one of them block and switch terminals one time more than I otherwise would need to?

I do understand the question you want to ask in the first part of your last message.
